### ISSUE TITLE
Question: ssh-agent and aliases

### ISSUE THREAD

**Issue by joca-bt** [billziss-gh/winfsp#101]
I am running MSYS2 so that I have some Linux tools on Windows, such as ```bash```, ```openssh```, ```ssh-agent```, etc.

Does WinFsp read my aliases from ```$HOME/.ssh/config```? That is, can I map with ```\\sshfs\foo``` instead of ```\\sshfs\foo.bar.com```?
```
ForwardAgent yes

Host foo
    HostName foo.bar.com
```

Does WinFsp integrate with ```ssh-agent```? For example, I have a service running ```ssh-agent```. Can I make WinFsp aware of its existence? (Through ```$SSH_AGENT_PID``` and ```$SSH_AUTH_SOCK```.)

I am asking this because I am trying to setup WinFsp with ```ssh-agent``` but I am having some difficulties. My setup uses an ```ssh-agent``` and every ssh connection is forwarded to the agent for authentication.

**Comment by billziss-gh** [comment]
@joca-bt You should consider asking this question at [SSHFS-Win](https://github.com/billziss-gh/sshfs-win). WinFsp is a general file system solution for Windows and does not provide any SSHFS specific functionality.

SSHFS-Win contains a version of SSHFS running on Cygwin. It is however packaged as a Windows program, so in general Cygwin is not visible to the average user. You can however find the Cygwin programs under `\Program Files\SSHFS-Win\bin`.

I have not made any effort to make `sshfs` work with `ssh-agent` under Cygwin. I am unclear whether it works. If what you are trying to do is possible on Linux, then it is likely possible under Cygwin as well, although you may have to work on it.

I am closing this. Please reopen in SSHFS-Win and I will try to help.

[Please note: I am currently on vacation and responses will be slow.]

**Comment by joca-bt** [comment]
This issue is already there, https://github.com/billziss-gh/sshfs-win/issues/10.
