### ISSUE TITLE
Windows10 unable to mount

### ISSUE THREAD

**Issue by storagXpert** [billziss-gh/winfsp#102]
Downloaded and installed. Got the following error :
---------------
C:\Program Files (x86)\WinFsp\bin>memfs-x64.exe  -u \memfs64\share -m *.
cannot mount MEMFS
The service memfs has failed to start (Status=c00000ca).
----------------
VC 2017 build resulted in following error upon launch 
Exception thrown at 0x00007FFE32243C58 (KernelBase.dll) in passthrough-x64.exe: 0x00000005: Access is denied.
The thread 0x1270 has exited with code 0 (0x0).
The thread 0xcc has exited with code 31 (0x1f).
The thread 0xee4 has exited with code 31 (0x1f).
The program '[3788] passthrough-x64.exe' has exited with code 31 (0x1f).
--------------
What setting changes on windows is required

**Comment by billziss-gh** [comment]
@storagXpert I am back from vacation. I am assuming this got resolved. Let me know if it is otherwise.

**Comment by storagXpert** [comment]
Yes it got resolved.
Thanks


On Sat, Sep 2, 2017 at 2:45 AM, Bill Zissimopoulos <notifications@github.com
