### ISSUE TITLE
Add API or configuration option to keep files off the "standby list"

### ISSUE THREAD

**Issue by billziss-gh** [billziss-gh/winfsp#104]
Consider adding an API or a configuration option to instruct the WinFsp FSD to keep files off the "standby list". This should probably be done by calling `MmForceSectionClosed` upon `IRP_MJ_CLEANUP`.

For some related information see hasse69/rar2fs#81. I invite @hasse69 and @janosek to add any additional related information they may have.

**Comment by hasse69** [comment]
I think it would be preferred to have this implemented as a fuse API extension (possibly in the fuse_file_info structure) or as a mount option passed to the fuse emulation layer. Having it as a configuration option means it becomes a global attribute and that might not be what you want.
Having it as a mount option is probably the most attractive approach since it would give user full control of the fs behavior.

**Comment by billziss-gh** [comment]
Agree. I was thinking of having it as a mount option for FUSE. For the native API it would be one of the flags passed to the kernel during file system creation.

**Comment by janosek** [comment]
I am just adding a comment to monitor this thread.  I am available for any testing.

**Comment by billziss-gh** [comment]
@ricardo-s-mendes has asked for a similar feature in #117.

I intend to add an API or configuration option to the WinFsp API to address this by `v1.3`.

**Comment by billziss-gh** [comment]
I have added the option to "flush and purge" the cache when a file is closed. When this option is enabled, kernel caching is terminated when the last file handle is closed.

This should remove one of the main reasons for keeping files on the "standby" list and thus reduce resource pressure (e.g. file descriptors) in the user mode file system. There may be other reasons that files end up in the "standby" list (e.g. memory mapped files).

Commit 5c3549c6eb829d4401dd33f782e908f8b891ec31 adds the `FlushAndPurgeOnCleanup` capability to `VolumeParams`.
Commit 5d34a3bd8c3cc85b34f633f502760728b4bfe7c8 adds the FUSE option `-o FlushAndPurgeOnCleanup`.

These changes will become available in 2018.1 B3.

**Comment by hasse69** [comment]
Have we considered the fact that the majority (if not all) FUSE based file systems would expect file descriptors to be closed when last reference to it is removed? Could this even motivate this to be the default behavior for fuse?

**Comment by billziss-gh** [comment]
> Have we considered the fact that the majority (if not all) FUSE based file systems would expect file descriptors to be closed when last reference to it is removed?

I am reasonably certain (as in: my memory of past experiments tells me, although I am not 100% certain) that this is not the default behavior on other FUSE implementations. For example, I believe that OSXFUSE will also delay `release` calls indefinitely under some circumstances.

> Could this even motivate this to be the default behavior for fuse?

I would be open to it if a good case was made that this is how other FUSE implementations behave. We would also have to take into consideration that there are FUSE file systems on Windows that do not suffer from resource exhaustion with too many open files, but would suffer an unnecessary performance degradation because of the new default.

**Comment by hasse69** [comment]
>I would be open to it if a good case was made that this is how other FUSE implementations behave. 
But is this really a question about how FUSE handles it? I would say it is more about how the Linux kernel handles it since I am rather sure native FUSE does not implement its own semantics here. Sure, OSXFUSE (as an example only) might have done something slightly different here, but I have never experienced any issues with it myself. Thissort of makes me think that even if it did delay release calls (which I actually doubt) it is still within reasonable limits to not cause a resource shortage.

**Comment by billziss-gh** [comment]
I understood your request to change the default as an attempt to achieve behavioral parity between different FUSE implementations on this aspect.

From the perspective of the user mode file system it does not matter whether it is the OS kernel, the FUSE kernel driver/extension or the FUSE user-mode library that are responsible for the different behavior. My point was that I would like to understand how the Linux FUSE system (Linux kernel, FUSE kernel driver and FUSE library) and OSX FUSE system (OSX kernel, OSX kernel extension and FUSE library) behave regarding this aspect, before considering a change.

**Comment by hasse69** [comment]
Yes, I understand your point and it makes sense of course. I was a bit wrong here mentioning how this is handled in the Linux kernel, it is not really about that.
My point here was that FUSE on Linux is the reference implementation and if other implementations on other OS:es provide FUSE compatibility (like OSX, FreeBSD, Solaris etc.) and does not also mimic the semantics it might become a problem. I think it is rather well documented that on FUSE/Linux release will be called when the last reference to a file descriptor is removed. If that also means it is in fact released as a resource internally by the OS (optimizations etc) is a different story. The original issue we have here was that open of one file by a user resulted in a lot more files being opened internally by the file system. The latter could not be released until the file system was informed they could due to the file opened by the user was closed. This caused extensive resource exhaustion on Cygwin level in this case. So it is rather this I see as a problem when reference design is not followed.

**Comment by benrubson** [comment]
Another question to understand the impact of this option, let's assume it is disabled, on which basis / trigger is the "standly list" purged ?

**Comment by janosek** [comment]
Hello.  I am ready to test a build with the enhancement to see if it fixes the issue I was having.

**Comment by billziss-gh** [comment]
I want to clarify that my use of the term "standby list" is very loose. The "standby" list is not well documented and its role is not well understood (at least by me). Others (@fsgeek ?) likely have a far better understanding of the subject than me.

What is understood is that NTOS (the Windows kernel) may keep files open indefinitely and it does so for good reasons. One of the best reasons is caching. Consider a program that constantly opens, reads/writes and closes the same file (a rather common pattern). If Windows keeps the file open (despite what the program thinks) it will have a cache-miss on the first read and subsequent I/O will be satisfied from cache (until the cache gets purged for whatever reason).

This is accomplished on Windows by maintaining both a `HandleCount` and an `OpenCount` for every file. When an "Open" (`IRP_MJ_CREATE`) arrives the file system driver increments both the `HandleCount` and `OpenCount` of the file. When a "Close" (`IRP_MJ_CLEANUP`) arrives the file system driver decrements the `HandleCount`, but does not touch the `OpenCount`. Thus the OS can keep a "reference" to the file indefinitely and can perform memory-mapped I/O to it. When it is done with the file it sends an `IRP_MJ_CLOSE`, which decrements the `OpenCount` and potentially makes the in-memory file object go away.

The commits I referenced above purge the cache when the last `IRP_MJ_CLEANUP` arrives. This has the benefit of removing some extraneous NTOS references, but of course it affects performance. If this solution is considered too big of a hammer (it may be) an alternative is to actively purge the cache of files that have been inactive for some time (say 1 minute), although in general I dislike trying to be cleverer than the OS.

@benrubson 
> Another question to understand the impact of this option, let's assume it is disabled, on which basis / trigger is the "standly list" purged ?

This is not clearly documented anywhere that I know of. Some people say "under memory pressure". Supposedly the OS has a view of overall resources and decides when it is time to purge. Of course it does not understand resources that live inside user mode file systems.

There is an undocumented method for emptying the "standby list" and a sysinternals tool called [RAMMap](https://docs.microsoft.com/en-us/sysinternals/downloads/rammap) which can do it.

@janosek
> Hello. I am ready to test a build with the enhancement to see if it fixes the issue I was having.

It may be a few more weeks before I release 2018.1 B3 as there are some other enhancements I want to add. I will ping when it is time.

**Comment by billziss-gh** [comment]
@hasse69 

> EDIT: A question here is thus if WinFSP/FUSE really has the means of telling the user file system that close was made on the file in question (and trigger the release API callback) unless Windows basically tells it that is the case. If not then this new options you added is of course the best you can provide and it should definitely help in this specific case.

Actually, yes, WinFsp knows when `CloseHandle` is made on the file in question because it receives `IRP_MJ_CLEANUP`. (Nitpick: I am ignoring duplicated `HANDLE`'s here.)

In the current implementation if this is the last `HANDLE` being `CloseHandle`'d, it instructs the OS to "flush" and "purge" the cache". This effectively tells the file system to release any references that it has on the file for caching purposes (see above writeup).

**Comment by billziss-gh** [comment]
I did a bit of research on how linux FUSE handles this and found this thread:

http://fuse.996288.n3.nabble.com/fuse-when-are-release-requests-queued-td14761.html

The most interesting message in this thread is this:

http://fuse.996288.n3.nabble.com/fuse-when-are-release-requests-queued-tp14761p14767.html

From this I gather that `release` is potentially asynchronous and MAY be delayed, but will be delivered within a finite time to the user mode file system (as opposed to Windows keeping the file open indefinitely).

So this argues for making `-o FlushAndPurgeOnCleanup` default and making the opposite condition an option for FUSE.

**Comment by billziss-gh** [comment]
I am trying to find related information about OSXFUSE, but not succeeding. The most relevant issue that I can find is this: https://github.com/osxfuse/osxfuse/issues/202. Unfortunately I do not have time for a deeper dive into the OSXFUSE code.

In any case I am inclined to change this and make `-o FlushAndPurgeOnCleanup` the default. I think this should make things easier for other file systems, such as EncFs (@benrubson).

Any ideas on what we should call the opposite condition (`-o NoFlushAndPurgeOnCleanup`)?

**Comment by hasse69** [comment]
The naming of the option sounds good to me, in the end what matters is how it is documented, right?

**Comment by billziss-gh** [comment]
I ended up naming it `-o KeepFileCache` with the usage comment below in a commit that I will be pushing soon:

```
    -o KeepFileCache           do not discard cache when files are closed
```

**Comment by billziss-gh** [comment]
Commit 498ab91123e6d7c33972e3962972eb4511a525a2 changes the default (for FUSE only) and introduces the `-o KeepFileCache` option.

Since this is a change in the default behavior of WinFsp-FUSE I need to test with some additional FUSE file systems before merging into master.

**Comment by billziss-gh** [comment]
I have merged this into master. The change will appear in release 2018.1 B3. I will ping when it is ready.

**Comment by benrubson** [comment]
> I ended up naming it `-o KeepFileCache`

👍 

> In any case I am inclined to change this and make `-o FlushAndPurgeOnCleanup the default`. I think this should make things easier for other file systems, such as EncFs (@benrubson).

Why Bill ?
Was EncFS just an example among the others ? :)
The [performance tests I did](https://github.com/billziss-gh/winfsp/issues/160) suffer from additional / unneeded (open) calls, I'm not sure they do because of the "standby list" (even if this list could be huge due to the nature of the tests performed). But some more tests with and without `-o KeepFileCache` would confirm 👍

**Comment by billziss-gh** [comment]
This issue was opened, because some FUSE file systems would run out of resources since Windows likes to keep files open indefinitely. In particular a file system that runs on Cygwin and uses a file descriptor per FUSE `open` would easily run into this problem (because the corresponding `release` could be delayed indefinitely under Windows and Cygwin has a max open limit of 3200).

I made a guess that EncFS might be in the same boat and wanted your input, Ben. However I am not familiar with EncFS and was likely wrong. I also forgot that you are not familiar with the history of this issue.

**Comment by benrubson** [comment]
> I made a guess that EncFS might be in the same boat

I did not encounter this issue, at least not yet !

> In particular a file system that runs on Cygwin and uses a file descriptor per FUSE `open` would easily run into this problem

EncFS reuses already existing FDs, which might certainly help here :)

**Comment by hasse69** [comment]
> EncFS reuses already existing FDs, which might certainly help here :)

Just curious, how can it reuse if it is not informed it is no longer in use by the OS?

To me a sane default should be what adheres as much as possible to the legacy/reference implementation of FUSE. If a file system then has internal optimizations that can mitigate performance problems due to this it can/should use options that change default behavior if available, like caching in this case. Or am I on the wrong track here?

**Comment by billziss-gh** [comment]
[WinFsp 2018.1 B3](https://github.com/billziss-gh/winfsp/releases/tag/v1.3B3) is out.

@janosek please let me know if this build resolves the problem for you.

**Comment by janosek** [comment]
Testing now..

**Comment by janosek** [comment]
IT WORKS!  rar2fs is still running in a steady state after my big torture test.  It never did that before!

**Comment by billziss-gh** [comment]
@janosek fantastic! I am glad that this seems to have been really resolved.

**Comment by daqqad** [comment]
Not sure if anyone is still monitoring this closed ticket, but I think I'm encountering a very similar issue with version 2019.1 of WinFSP and am looking for way to debug. Could you point me in the right direction to try to figure this out?

Specifically I'm getting access denied when I'm trying to access a directory with a large number of files (rars and others)

Thanks!
