### ISSUE TITLE
Can not mount driver using jnr-fuse when i run project with jar?

### ISSUE THREAD

**Issue by ust3000** [billziss-gh/winfsp#105]
Hello,

I have developed an application with jnr-fuse and winfsp, when i test over intelllij it works fine.
However, i packaged  my application to jar file then i run it, so i am getting : 
`>>>>>> statfs:  /   W i n F s p . N e t
>>>>>> getattr:         /   W i n F s p . N e t
The service java has failed to start (Status=c0000034).
Exception in thread "main" ru.serce.jnrfuse.FuseException: Unable to mount FS
        at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:277)
        at ru.serce.jnrfuse.Mountable.mount(Mountable.java:20)`

I cant figure out why i am getting "/   W i n F s p . N e t" as root but when i have run through intellij i am getting "/" as root.
Please could you let me know what is the problem ? and if i can force using only WinFsp.disk

**Comment by billziss-gh** [comment]
This looks to me more like a java and jnr-fuse problem rather than a WinFsp problem. I am sorry but I do not believe I can be of much help.

**Comment by philrykoff** [comment]
From https://github.com/SerCeMan/jnr-fuse/blob/master/INSTALLATION.md:

If you see the service java has failed to start error or corrupted file names/content, setting the explicit file encoding -Dfile.encoding=UTF-8 might help.
