### ISSUE TITLE
What happened when right click the file? How to speed up the process?

### ISSUE THREAD

**Issue by wesley1975** [billziss-gh/winfsp#109]
Firstly, thanks for the great software,it is awesome. I encounter some issues when use winfsp with jnr-fuse. The mount, copy delete work well, but the response is quite slow. My issue is when I right click the file in the file explore, it will cost a lot of time. I check the winfsp log, seems that winfsp need to read the whole file and then it can popup the context menu: below is the log:

javaw[TID=1cd8]: FFFFBA8811D108F0: >>Create [UT---C] "\07_End_to_End_DevOps.pptx", FILE_OPEN, CreateOptions=200000, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=0000000000000670[PID=2de4], DesiredAccess=20000, GrantedAccess=0, ShareAccess=7
javaw[TID=1cd8]: FFFFBA8811D108F0: <<Create IoStatus=0[1] UserContext=0000000000000000:0000000000D0ED50, GrantedAccess=20000, FileInfo={FileAttributes=0, ReparseTag=0, AllocationSize=0:227000, FileSize=0:226e9b, CreationTime=1970-01-01T00:00:00.000Z, LastAccessTime=2017-10-09T09:49:07.000Z, LastWriteTime=2017-10-09T09:49:07.000Z, ChangeTime=2017-10-09T09:49:07.000Z, IndexNumber=0:0}
javaw[TID=1cd8]: FFFFBA8811D108F0: >>QuerySecurity 0000000000000000:0000000000D0ED50
javaw[TID=1cd8]: FFFFBA8811D108F0: <<QuerySecurity IoStatus=0[0] Security="O:BAG:AUD:P(A;;0x1f01bf;;;BA)(A;;0x1201af;;;AU)(A;;0x120088;;;WD)"
javaw[TID=1cd8]: FFFFBA880E1651E0: >>Close 0000000000000000:0000000000D0ED50
javaw[TID=2a64]: FFFFBA880E8C4810: >>Create [UT---C] "\07_End_to_End_DevOps.pptx", FILE_OPEN, CreateOptions=200000, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=00000000000005EC[PID=2de4], DesiredAccess=20000, GrantedAccess=0, ShareAccess=7
javaw[TID=1cd8]: FFFFBA880E1651E0: <<Close IoStatus=0[0]
javaw[TID=2a64]: FFFFBA880E8C4810: <<Create IoStatus=0[1] UserContext=0000000000000000:0000000000D3A210, GrantedAccess=20000, FileInfo={FileAttributes=0, ReparseTag=0, AllocationSize=0:227000, FileSize=0:226e9b, CreationTime=1970-01-01T00:00:00.000Z, LastAccessTime=2017-10-09T09:49:07.000Z, LastWriteTime=2017-10-09T09:49:07.000Z, ChangeTime=2017-10-09T09:49:07.000Z, IndexNumber=0:0}
javaw[TID=2a64]: FFFFBA880E8C4810: >>QuerySecurity 0000000000000000:0000000000D3A210
javaw[TID=2a64]: FFFFBA880E8C4810: <<QuerySecurity IoStatus=0[0] Security="O:BAG:AUD:P(A;;0x1f01bf;;;BA)(A;;0x1201af;;;AU)(A;;0x120088;;;WD)"
javaw[TID=2a64]: FFFFBA8811611B00: >>Close 0000000000000000:0000000000D3A210
javaw[TID=2a64]: FFFFBA8811611B00: <<Close IoStatus=0[0]
javaw[TID=2a64]: FFFFBA8813326AF0: >>Create [UT---C] "\07_End_to_End_DevOps.pptx", FILE_OPEN, CreateOptions=200000, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=0000000000000660[PID=2de4], DesiredAccess=80, GrantedAccess=0, ShareAccess=7
javaw[TID=2a64]: FFFFBA8813326AF0: <<Create IoStatus=0[1] UserContext=0000000000000000:0000000000D39CA0, GrantedAccess=80, FileInfo={FileAttributes=0, ReparseTag=0, AllocationSize=0:227000, FileSize=0:226e9b, CreationTime=1970-01-01T00:00:00.000Z, LastAccessTime=2017-10-09T09:49:07.000Z, LastWriteTime=2017-10-09T09:49:07.000Z, ChangeTime=2017-10-09T09:49:07.000Z, IndexNumber=0:0}
javaw[TID=2a64]: FFFFBA8811611B00: >>Close 0000000000000000:0000000000D39CA0
javaw[TID=2a64]: FFFFBA8811611B00: <<Close IoStatus=0[0]
javaw[TID=6464]: FFFFBA8807BEA270: >>Create [UT---C] "\07_End_to_End_DevOps.pptx", FILE_OPEN, CreateOptions=200000, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=0000000000000660[PID=2de4], DesiredAccess=80, GrantedAccess=0, ShareAccess=7
javaw[TID=6464]: FFFFBA8807BEA270: <<Create IoStatus=0[1] UserContext=0000000000000000:0000000000D3A210, GrantedAccess=80, FileInfo={FileAttributes=0, ReparseTag=0, AllocationSize=0:227000, FileSize=0:226e9b, CreationTime=1970-01-01T00:00:00.000Z, LastAccessTime=2017-10-09T09:49:07.000Z, LastWriteTime=2017-10-09T09:49:07.000Z, ChangeTime=2017-10-09T09:49:07.000Z, IndexNumber=0:0}
javaw[TID=6464]: FFFFBA8813326AF0: >>Close 0000000000000000:0000000000D3A210
javaw[TID=6464]: FFFFBA8813326AF0: <<Close IoStatus=0[0]
javaw[TID=6464]: FFFFBA8813326AF0: >>Create [UT---C] "\07_End_to_End_DevOps.pptx", FILE_OPEN, CreateOptions=60, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=0000000000000684[PID=2de4], DesiredAccess=120089, GrantedAccess=0, ShareAccess=7
javaw[TID=6464]: FFFFBA8813326AF0: <<Create IoStatus=0[1] UserContext=0000000000000000:0000000000D3A120, GrantedAccess=120089, FileInfo={FileAttributes=0, ReparseTag=0, AllocationSize=0:227000, FileSize=0:226e9b, CreationTime=1970-01-01T00:00:00.000Z, LastAccessTime=2017-10-09T09:49:07.000Z, LastWriteTime=2017-10-09T09:49:07.000Z, ChangeTime=2017-10-09T09:49:07.000Z, IndexNumber=0:0}
javaw[TID=6464]: FFFFBA880D354C50: >>Read 0000000000000000:0000000000D3A120, Address=0000000022180000, Offset=0:0, Length=1048576, Key=0
javaw[TID=6464]: FFFFBA880D354C50: <<Read IoStatus=0[1048576]
javaw[TID=2858]: FFFFBA880F14FD70: >>Read 0000000000000000:0000000000D3A120, Address=0000000000DC0000, Offset=0:100000, Length=1048576, Key=0
javaw[TID=2858]: FFFFBA880F14FD70: <<Read IoStatus=0[1048576]
javaw[TID=6464]: FFFFBA880479F530: >>Read 0000000000000000:0000000000D3A120, Address=0000000000DC0000, Offset=0:200000, Length=159744, Key=0
javaw[TID=6464]: FFFFBA880479F530: <<Read IoStatus=0[159387]
javaw[TID=6464]: FFFFBA880A32B600: >>QueryInformation 0000000000000000:0000000000D3A120
javaw[TID=6464]: FFFFBA880A32B600: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=0, ReparseTag=0, AllocationSize=0:227000, FileSize=0:226e9b, CreationTime=1970-01-01T00:00:00.000Z, LastAccessTime=2017-10-09T09:49:07.000Z, LastWriteTime=2017-10-09T09:49:07.000Z, ChangeTime=2017-10-09T09:49:07.000Z, IndexNumber=0:0}
javaw[TID=6464]: FFFFBA8813326AF0: >>Read 0000000000000000:0000000000D3A120, Address=000000001F5E0000, Offset=0:0, Length=4096, Key=0
javaw[TID=6464]: FFFFBA8813326AF0: <<Read IoStatus=0[4096]
javaw[TID=6464]: FFFFBA880CC63120: >>QueryInformation 0000000000000000:0000000000D3A120
javaw[TID=6464]: FFFFBA880CC63120: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=0, ReparseTag=0, AllocationSize=0:227000, FileSize=0:226e9b, CreationTime=1970-01-01T00:00:00.000Z, LastAccessTime=2017-10-09T09:49:07.000Z, LastWriteTime=2017-10-09T09:49:07.000Z, ChangeTime=2017-10-09T09:49:07.000Z, IndexNumber=0:0}
javaw[TID=6464]: FFFFBA880CC63120: >>Read 0000000000000000:0000000000D3A120, Address=000000001F5E0000, Offset=0:0, Length=4096, Key=0

Any ideas for this issue? thanks in advance.

**Comment by billziss-gh** [comment]
WinFsp will not cause I/O that is not asked for by the operating system. In general the operating system will only ask on behalf of applications although some times some system component might also for I/O.

So I cannot explain why you are getting this `Read` when you right click. Are you some there is not some application on your system that is not causing the I/O?

**Comment by wesley1975** [comment]
Yes, it currently will read the whole file before it can popup the windows, i test a file with 50MB, this will cost about 10-15 minutes. and with the same file, I put it in the MS One Driver, the response is quite quick within seconds.

**Comment by billziss-gh** [comment]
10-15 minutes?!

Ok, this indicates to me that there may be something else that is seriously wrong in your system. Even when using the debug version of WinFsp with full diagnostics enabled and running it under the verifier, it would take a few seconds to complete a `Read` of 50MB. [Of course the `Read` should never happen for simply "right-clicking" on the Explorer anyway.]

- Does this happen when accessing a smaller file?
- Can you run `diag.bat` found under `\Program Files (x86)\WinFsp\bin` and attach the output?

**Comment by wesley1975** [comment]
Yes to for the small file, it do read all the content.
C:\Program Files (x86)\WinFsp\bin>diag.bat
WINFSP INSTALLATION DIRECTORY AND LAUNCHER REGISTRATIONS

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp
    InstallDir    REG_SZ    C:\Program Files (x86)\WinFsp\

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services\memfs-dotnet
    Executable    REG_SZ    C:\Program Files (x86)\WinFsp\bin\memfs-dotnet-msil.exe
    CommandLine    REG_SZ    -i -F NTFS -n 65536 -s 67108864 -u %1 -m %2
    Security    REG_SZ    D:P(A;;RPWPLC;;;WD)
    JobControl    REG_DWORD    0x1

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services\memfs32
    Executable    REG_SZ    C:\Program Files (x86)\WinFsp\bin\memfs-x86.exe
    CommandLine    REG_SZ    -i -F NTFS -n 65536 -s 67108864 -u %1 -m %2
    Security    REG_SZ    D:P(A;;RPWPLC;;;WD)
    JobControl    REG_DWORD    0x1

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services\memfs64
    Executable    REG_SZ    C:\Program Files (x86)\WinFsp\bin\memfs-x64.exe
    CommandLine    REG_SZ    -i -F NTFS -n 65536 -s 67108864 -u %1 -m %2
    Security    REG_SZ    D:P(A;;RPWPLC;;;WD)
    JobControl    REG_DWORD    0x1


WINFSP DLL REGISTRATIONS

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order
    ProviderOrder    REG_SZ    LanmanWorkstation,RDPNP,webclient,WinFsp.Np


HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinFsp.Np\NetworkProvider
    Name    REG_SZ    Windows File System Proxy
    ProviderPath    REG_SZ    C:\Program Files (x86)\WinFsp\bin\winfsp-x64.dll


HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\WinFsp
    EventMessageFile    REG_SZ    C:\Program Files (x86)\WinFsp\bin\winfsp-x64.dll
    TypesSupported    REG_DWORD    0x7


WINFSP FSD CONFIGURATION AND STATUS

SERVICE_NAME: WinFsp
        TYPE               : 2  FILE_SYSTEM_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1077  (0x435)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
[SC] QueryServiceConfig 成功

SERVICE_NAME: WinFsp
        TYPE               : 2  FILE_SYSTEM_DRIVER
        START_TYPE         : 3   DEMAND_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : \??\C:\Program Files (x86)\WinFsp\bin\winfsp-x64.sys
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : WinFsp
        DEPENDENCIES       :
        SERVICE_START_NAME :

D:(A;;LCRP;;;WD)(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)

WINFSP LAUNCHER SERVICE CONFIGURATION AND STATUS

SERVICE_NAME: WinFsp.Launcher
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
[SC] QueryServiceConfig 成功

SERVICE_NAME: WinFsp.Launcher
        TYPE               : 10  WIN32_OWN_PROCESS
        START_TYPE         : 2   AUTO_START
        ERROR_CONTROL      : 0   IGNORE
        BINARY_PATH_NAME   : "C:\Program Files (x86)\WinFsp\bin\launcher-x64.exe"
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : WinFsp.Launcher
        DEPENDENCIES       :
        SERVICE_START_NAME : LocalSystem

D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)

**Comment by billziss-gh** [comment]
Everything looks in order in the `diag.bat` output.

I do not know why you receive `Read` upon Explorer right-click. And it should not take 10-15 minutes to complete the `Read` unless your file system is really slow (e.g. running on a slow network it may take a long time to read the whole file).

Consider installing [FileSpy](http://www.zezula.net/en/fstools/filespy.html) and logging all IRP (I/O Request Packets) sent to your file system. This should some more light into this issue.

BTW, do you run any anti-virus software?

**Comment by fsgeek** [comment]
If there is a registered context handler it might also do this.

**Comment by wesley1975** [comment]
thanks, I will check this

**Comment by billziss-gh** [comment]
@wesley1975 did you have the chance to install FileSpy and see if that answers the question of the component that issues the `Read`?

**Comment by wesley1975** [comment]
@billziss-gh ,  
I got log from the  winfsp ,are there any issue?
javaw[TID=0d38]: FFFFBC0F1E884620: >>QueryInformation 0000000000000000:000000000079F600
javaw[TID=0d38]: FFFFBC0F1E884620: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=0, ReparseTag=0, AllocationSize=0:121c000, FileSize=0:121bdfd, CreationTime=1970-01-01T00:00:00.000Z, LastAccessTime=2017-10-09T09:49:50.000Z, LastWriteTime=2017-10-09T09:49:50.000Z, ChangeTime=2017-10-09T09:49:50.000Z, IndexNumber=0:0}
javaw[TID=0d38]: FFFFBC0F1E884620: >>Read 0000000000000000:000000000079F600, Address=0000000000850000, Offset=0:0, Length=4096, Key=0
javaw[TID=3a60]: FFFFBC0F20AC3C00: <<Read IoStatus=0[4096]
javaw[TID=3a60]: FFFFBC0F252BDE10: >>QueryInformation 0000000000000000:00000000007A2860
javaw[TID=3a60]: FFFFBC0F252BDE10: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=0, ReparseTag=0, AllocationSize=0:227000, FileSize=0:226e9b, CreationTime=1970-01-01T00:00:00.000Z, LastAccessTime=2017-10-09T09:49:07.000Z, LastWriteTime=2017-10-09T09:49:07.000Z, ChangeTime=2017-10-09T09:49:07.000Z, IndexNumber=0:0}
javaw[TID=3a60]: FFFFBC0F252BDE10: >>Read 0000000000000000:00000000007A2860, Address=0000000000A60000, Offset=0:226e85, Length=4096, Key=0
javaw[TID=3a60]: FFFFBC0F252BDE10: <<Read IoStatus=0[22]
javaw[TID=3a60]: FFFFBC0F252BDE10: >>Read 0000000000000000:00000000007A2860, Address=0000000000A60000, Offset=0:220d68, Length=4096, Key=0
javaw[TID=3a60]: FFFFBC0F252BDE10: <<Read IoStatus=0[4096]
javaw[TID=3a60]: FFFFBC0F1FC19970: >>Read 0000000000000000:00000000007A2860, Address=0000000000A60000, Offset=0:220d6c, Length=4096, Key=0
javaw[TID=3a60]: FFFFBC0F1FC19970: <<Read IoStatus=0[4096]
javaw[TID=3a60]: FFFFBC0F20AC3C00: >>Read 0000000000000000:00000000007A2860, Address=0000000000A60000, Offset=0:220d96, Length=4096, Key=0
javaw[TID=3a60]: FFFFBC0F20AC3C00: <<Read IoStatus=0[4096]
javaw[TID=3a60]: FFFFBC0F2958BE10: >>Read 0000000000000000:00000000007A2860, Address=0000000000A60000, Offset=0:220da9, Length=4096, Key=0
javaw[TID=3a60]: FFFFBC0F2958BE10: <<Read IoStatus=0[4096]
javaw[TID=3a60]: FFFFBC0F28F452C0: >>Read 0000000000000000:00000000007A2860, Address=0000000000A60000, Offset=0:220dad, Length=4096, Key=0
javaw[TID=3a60]: FFFFBC0F28F452C0: <<Read IoStatus=0[4096]
javaw[TID=3a60]: FFFFBC0F1B513310: >>Read 0000000000000000:00000000007A2860, Address=0000000000A60000, Offset=0:220dd7, Length=4096, Key=0
javaw[TID=3a60]: FFFFBC0F1B513310: <<Read IoStatus=0[4096]
javaw[TID=3a60]: FFFFBC0F28F452C0: >>Read 0000000000000000:00000000007A2860, Address=0000000000A60000, Offset=0:220de2, Length=4096, Key=0
javaw[TID=3a60]: FFFFBC0F28F452C0: <<Read IoStatus=0[4096]
javaw[TID=3a60]: FFFFBC0F28F452C0: >>Read 0000000000000000:00000000007A2860, Address=0000000000A60000, Offset=0:220de6, Length=4096, Key=0
javaw[TID=3a60]: FFFFBC0F28F452C0: <<Read IoStatus=0[4096]
javaw[TID=3a60]: FFFFBC0F28F452C0: >>Read 0000000000000000:00000000007A2860, Address=0000000000A60000, Offset=0:220e10, Length=4096, Key=0
javaw[TID=3a60]: FFFFBC0F28F452C0: <<Read IoStatus=0[4096]

======================
and the result from filespy
271	23:37:44.162	114	explorer.exe	IRP_MJ_READ	00060900	FFFFAC8A24C2F7B0	\Device\Volume{b50fb6f9-b7b3-11e7-8f37-e4a7a064c4e9}\API Management Deep Dive.pptx	STATUS_SUCCESS	Offset: 00000000-01215F88 ToRead: 1000 Read: 1000 
272	23:37:44.230	112	explorer.exe	IRP_MJ_READ	00060900	FFFFAC8A210B85C0	\Device\Volume{b50fb6f9-b7b3-11e7-8f37-e4a7a064c4e9}\07_End_to_End_DevOps.pptx	STATUS_SUCCESS	Offset: 00000000-00222DC6 ToRead: 1000 Read: 1000 
273	23:37:44.276	118	explorer.exe	IRP_MJ_READ	00060900	FFFFAC8A24C2F7B0	\Device\Volume{b50fb6f9-b7b3-11e7-8f37-e4a7a064c4e9}\API Management Deep Dive.pptx	STATUS_SUCCESS	Offset: 00000000-01215FA9 ToRead: 1000 Read: 1000 
274	23:37:44.343	104	explorer.exe	IRP_MJ_READ	00060900	FFFFAC8A210B85C0	\Device\Volume{b50fb6f9-b7b3-11e7-8f37-e4a7a064c4e9}\07_End_to_End_DevOps.pptx	STATUS_SUCCESS	Offset: 00000000-00222DDC ToRead: 1000 Read: 1000 
275	23:37:44.395	118	explorer.exe	IRP_MJ_READ	00060900	FFFFAC8A24C2F7B0	\Device\Volume{b50fb6f9-b7b3-11e7-8f37-e4a7a064c4e9}\API Management Deep Dive.pptx	STATUS_SUCCESS	Offset: 00000000-01215FAD ToRead: 1000 Read: 1000 
276	23:37:44.447	105	explorer.exe	IRP_MJ_READ	00060900	FFFFAC8A210B85C0	\Device\Volume{b50fb6f9-b7b3-11e7-8f37-e4a7a064c4e9}\07_End_to_End_DevOps.pptx	STATUS_SUCCESS	Offset: 00000000-00222DE0 ToRead: 1000 Read: 1000 
277	23:37:44.513	224	explorer.exe	IRP_MJ_READ	00060900	FFFFAC8A24C2F7B0	\Device\Volume{b50fb6f9-b7b3-11e7-8f37-e4a7a064c4e9}\API Management Deep Dive.pptx	STATUS_SUCCESS	Offset: 00000000-01215FD7 ToRead: 1000 Read: 1000 
278	23:37:44.554	202	explorer.exe	IRP_MJ_READ	00060900	FFFFAC8A210B85C0	\Device\Volume{b50fb6f9-b7b3-11e7-8f37-e4a7a064c4e9}\07_End_to_End_DevOps.pptx	STATUS_SUCCESS	Offset: 00000000-00222E0A ToRead: 1000 Read: 1000 
279	23:37:44.738	315	explorer.exe	IRP_MJ_READ	00060900	FFFFAC8A24C2F7B0	\Device\Volume{b50fb6f9-b7b3-11e7-8f37-e4a7a064c4e9}\API Management Deep Dive.pptx	STATUS_SUCCESS	Offset: 00000000-01215FF8 ToRead: 1000 Read: 1000

**Comment by billziss-gh** [comment]
The FileSpy logs show the `IRP_MJ_READ` coming from `explorer.exe`, which is curious. So WinFsp and your file system appear to do the correct thing here, which is to service the READ.

I do not know why Explorer issues READs. It might be an installed extension or it might be Explorer trying to build a "preview" of your file. Do you mount your file system as a disk or network drive? This may make a difference in whether Explorer tries to read the file or not (not sure).

To mount your file system as a network drive, launch it with the `--VolumePrefix=\Server\Share` option.

You might also want to enable full caching on your file system. Since you use jnr-fuse, try launching your file system with the option `-o FileInfoTimeout=-1`. This will enable the cache manager on your file system and will considerably speed things up.

**Comment by wesley1975** [comment]
greatly thanks for you quick response, --VolumePrefix works, due i mount the azure storage blobs, so i use
--VolumePrefix=\\localhost\\share,   but two issues go after this,  1.ouid=544,gid=11,umask=0007, i use above options to mount the azure, but i can not copy file from local to azure  due to permission error. 2, the performence is quite slow the block is always 4K.

**Comment by wesley1975** [comment]
3, and right click to create new folder ,it will create 3 copies.

**Comment by billziss-gh** [comment]
> 1. I use the below options to mount the azureouid=544,gid=11,umask=0007, but i can not copy file from local to azure  due to permission error. 

```
uid(544) == BUILTIN\Administrators
gid(11) == NT AUTHORITY\Authenticated Users
umask(007)=rwxrwx---
```
Are you sure that the account that is doing the copy has proper permissions? If all else fails try with `umask=000`.

> 2.the performence is quite slow the block is always 4K.

If your file system is non-cached, you will see all I/O issued to your file system. Apps often issue I/O in 4K blocks, so this makes sense.

The only way around this is to use the Cache Manager. You may then get larger chunks because of read-ahead, etc.

> 3.and right click to create new folder ,it will create 3 copies.

This is a permission problem. Weirdly enough Explorer retries directory creation when receiving an "Access Denied" error.

If you fix your permission issues, this should go away as well.

**Comment by wesley1975** [comment]
@billziss-gh  thanks,  I plan to port my java code to c#, could you give some samples?

**Comment by wesley1975** [comment]
ok, I got tip from here winfsp/tst/memfs-dotnet/Program.cs

**Comment by billziss-gh** [comment]
There is also the passthrough-dotnet file system available here:

https://github.com/billziss-gh/winfsp/blob/master/tst/passthrough-dotnet/Program.cs

**Comment by billziss-gh** [comment]
@wesley1975 I am closing this as the primary question seems to have been resolved. Please reopen if you think otherwise.
