### ISSUE TITLE
How to obtain the actual PID ?

### ISSUE THREAD

**Issue by opensite73** [billziss-gh/winfsp#111]
In version v1.2B1, I tested the function FspFileSystemOperationProcessId using passthrough.

After mounting the DATA folder as an FSP folder
When accessing files in FSP folders and folders with Notepad

In the Open () method
I obtained the ProcessId and checked it as shown below.

DWORD ProcessId = FspFileSystemOperationProcessId();

The value for ProcessID is determined by the PID value of the passthrough process, not by Notepad process

How can I get the PID value of my notepad?

**Comment by billziss-gh** [comment]
You are correct. There is a bug in the current beta, which sends the file system PID instead of the originating PID. I will get this fixed in the next beta.

**Comment by billziss-gh** [comment]
Commit 4812f5bbd08f2778d63e1ef8020d68f815db7ce3 should fix this issue.

**Comment by billziss-gh** [comment]
Closing this as I believe it resolved. Please reopen if you find that it still does not work after v1.2B2.

**Comment by billziss-gh** [comment]
@opensite73 the latest release [v1.2B2](https://github.com/billziss-gh/winfsp/releases/tag/v1.2B2) includes a fix for this issue. Please me know if it now works for you.

**Comment by opensite73** [comment]
In the WinFsp 2017.2 B2 version, the FspFileSystemOperationProcessId () method
I tested it at the time of create and open and confirmed that it works well.
Thank you.

**Comment by billziss-gh** [comment]
Thanks for confirming!
