### ISSUE TITLE
Support for BitTorrent or magnet?

### ISSUE THREAD

**Issue by combecn** [billziss-gh/winfsp#113]
Hi Sir,
I'm looking for a tool to mount a torrent as a disk under windows (to enable a p2p share folder). Is it possible that winfsp supports it in the future?

Thanks in advance.

**Comment by billziss-gh** [comment]
It is possible to fashion a file system that presents the files referenced by a torrent. A bit of googling reveals a couple of FUSE file systems that can be ported to WinFsp-FUSE for someone interested:

https://github.com/johang/btfs
https://github.com/mafintosh/torrent-mount

[I have not used any of these projects.]

It is unlikely that any such file system will become part of the standard WinFsp distribution though.

**Comment by combecn** [comment]
@billziss-gh yes but the problem is these two are only for Linux and Mac (and no plan for Windows). Actually I'm looking for similar tool that can be used in Windows.

**Comment by billziss-gh** [comment]
@combecn I understand.

The links I included are just example file systems that could be ported to Windows using WinFsp. However I do not have the time to do this porting myself. You may want to ping the individual projects and see if they would be interested in such porting. I would be happy to support such an effort.
