### ISSUE TITLE
WinFSP-FUSE: Number of opens and releases do not always match.

### ISSUE THREAD

**Issue by ricardo-s-mendes** [billziss-gh/winfsp#117]
Hello,

i am using JNR-FUSE over winfsp and I just noticed that, contrary to the definition of the fuse's release operation, i.e., there must be one and only one release operation for each open operation, this is not happening in my case.

My use case is simple, you can try it and see if it happens with you too guys:
- add prints to the open and release operations
- copy a file from your local filesystem to the winfsp-fuse filesystem.
- open the file and close it
- count the number of opens and releases, they are not matching (at least in my case).

Can someone please help me here?

Thank you

**Comment by billziss-gh** [comment]
When an application closes a file, the OS may choose to keep the file open for an indefinite amount of time. For example, the OS may keep files in a "standby list" for caching purposes; this way if a recently closed file is reopened, it may already be cached.

Related issue: #104

**Comment by ricardo-s-mendes** [comment]
Is there some way to disable that at winfsp level. A starts flag or something?

**Comment by billziss-gh** [comment]
This is what #104 is asking for. Please add your voice there.

**Comment by billziss-gh** [comment]
Closing this as I believe this need will be addressed by #104. Please follow up there.

If you believe that the solution proposed in #104 will not address this issue, please reopen.
