### ISSUE TITLE
1 "new folder" command generates 4 new folders in passthrough-fuse sample

### ISSUE THREAD

**Issue by cdarau** [billziss-gh/winfsp#119]
This is a common issue for both 1.1 & 1.2B2.

Whenever I choose to create a new folder (either by right-click - new folder or by the toolbar button), 4 new folders are created at once.

I tried to track down the cause of this (in user-mode land) but from what I could see the FspFileSystemDispatcherThread routine's infinite loop treats 4 such requests each time I generate the user action.

**Comment by billziss-gh** [comment]
My apologies for the late response. It was a long weekend (Thanksgiving) here in the US.

The reason that this is happening is that permissions are not set up correctly for the FUSE file system. Explorer does some weird things in this case, like retrying directory creation multiple times.

There are multiple ways to set up permissions in your FUSE file system. The primary method is to return valid `stat` values in `getattr`. An easy alternative is to supply valid `uid`, `gid`, `mode` in the command line. Like so:

- `-ouid=-1,gid=-1`: will use the current user as the owner user, group for all files.
- `-ouid=UID,gid=GID`: will use the supplied UID, GID as the owner user, group for all files.
- `-oumask=000`: will give rwx permissions to user, group, everyone.

If you want to get the UID, GID of a specific user/group you can use the `fsptool id` command (included in v1.2B2).

**Comment by cdarau** [comment]
Thank you, Bill. The "uid=-1,gid=-1" made the difference.

**Comment by billziss-gh** [comment]
I am glad that this resolved the issue. Keep in mind that `-ouid=-1,gid=-1` uses the owner and group of the user who runs the file system. If you intend to run the file system under an account such as SYSTEM, you may need a more sophisticated approach!
