### ISSUE TITLE
different behaviour between passthrough and passthrough-fuse samples

### ISSUE THREAD

**Issue by cdarau** [billziss-gh/winfsp#122]
Hello, Bill.

It appears that the following 2 lines of script produce 2 different behaviours between the passthrough and the passthrough-fuse samples:
```
expect("CreateFile %s\\%s GENERIC_WRITE 0 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" % (name, filename(name)), 0)
expect("CreateFile %s\\%s GENERIC_WRITE 0 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" % (name, filename(name)), "ERROR_FILE_EXISTS")
```
The difference resides in the fact that the passthrough-fuse sample fails the second test, returning 0 instead of ERROR_FILE_EXISTS.

Why is this?

Thank you.

**Comment by billziss-gh** [comment]
You are correct.

The WinFsp-FUSE layer passes a flag of 0x102 during FUSE `create`. This is equivalent to `O_CREAT|O_RDWR`. I think the correct flags to pass should have been `O_CREAT|O_EXCL|O_RDWR`:

http://pubs.opengroup.org/onlinepubs/9699919799/functions/open.html

This is an easy fix, but I need to make sure that it will not break any existing FUSE file systems. What is curious here is how this was not caught by winfsp-tests...

**Comment by cdarau** [comment]
Thank you, Bill

**Comment by billziss-gh** [comment]
Commit d02030897d702c7e96d5763f95845ca9bdfd6cdd should fix this issue.
