### ISSUE TITLE
15x time increase when serving .docx file from passthrough-fuse sample instead of NTFS

### ISSUE THREAD

**Issue by cdarau** [billziss-gh/winfsp#123]
Hello, Bill

I see a remarkable gain in ReadFile operations total time opening a .docx file (that's served by the passthrough-fuse sample) with WINWORD.EXE.

To be more precise, when opening the test file with the same program but from NTFS, the total time amounts to around 8 seconds, while when the file resides on the mounted drive, the total time amounts to around 120 seconds.

The command I used to mount the drive was:
`passthrough-fuse-x86.exe -d -ouid=-1,gid=-1 <folderpath> <driveletter>:`

The special part about this scenario is that among the I/Os needed by WINWORD.EXE to open that test file are somewhere around 400k small reads (100 bytes each to be exact). The file has a size of 36,807,074 bytes. What I see in procmon is that the program commands these hundreds of thousands of small reads until it covers the whole document. Not all are in consecutive order but most of them are. The reads are something like this:
- tens of thousands of consecutive 100-byte reads
- than a jump at an offset (after or before)
- than another set of tens of thousands of consecutive 100-byte reads
- and so on
all these ranges not superposing one another.

What can cause this? and Can this be fixed?

Thank you very much

**Comment by billziss-gh** [comment]
WinFsp supports both cached and not cached file systems.

When a file system is cached, I/O is managed by the NTOS Cache Manager. The NTOS Cache Manager uses system memory to store file contents and will often satisfy I/O directly from that memory, for example, a READ or WRITE can be a simple memory copy. The NTOS Cache Manager will also use techniques such a Read Ahead and Write Behind to improve perceived I/O into the file system.

When a file system is non cached those benefits are not there. If an application issues 10000 READ's of 100 bytes, they will **all** be sent to the user mode file system.

The passthrough-fuse file system does not use the cache by default. You can enable the Cache Manager by passing a `-oFileInfoTimeout=-1` option to it. However the file system will not work properly in many cases with the Cache Manager enabled.

The primary problem is that when the Cache Manager is enabled the OS likes to keep files open for long periods of time. Because passthrough-fuse uses the NTFS file system as its actual backend this can cause issues. (For example open file handles can inhibit some file operations.) These problems can be worked around, but I have not taken the time to do so with the passthrough (and passthrough-fuse) file systems which were intended as tutorial file systems.

**Comment by cdarau** [comment]
Hello again

I understand what you described, but in this case I was talking about the first-opening of a file. So no time for a cache whatsoever - even if I was using the Cache Manager. Let me be more precise:
- I've uploaded a test file on a drive
- then downloaded it to a location
- on top of which I run the passthrough sample
So first-time opening of that file. In this case, even NTFS - which I understand uses the Cache Manager - can't serve from cache because it isn't there. Is this assumption correct? Because based on this assumption I was very surprised by the 1:15 ratio time-wise between what it took NTFS to open this file and the time needed by the sample. Do I get it right?

**Comment by billziss-gh** [comment]
Actually the Cache Manager is beneficial even on the first open.

Consider that an application that reads a file by issuing 10000 reads of 100 bytes at a time sequentially starting at offset 0.

- In the case of a non-cached file system all 10000 reads will be sent to the user mode file system.

- In the case of a cached file system the Cache Manager will perform read-ahead of (for example) 32K upon seeing the first read. Then it will serve subsequent 100-byte chunks from the cache until all 32K are read, in which case it will issue a second read-ahead. In this case the user mode file system will see approximately 10000/328=30 reads! (32768/100=327.68)

**Comment by cdarau** [comment]
But in that case, isn't it that I should see those (for eg) 32K read-aheads with procmon? I'm asking this because procmon doesn't show any of these read-aheads that would speed-up the NTFS scenario. Are these read-aheads some other kind of operations than ReadFiles? I'm thinking maybe my procmon filter is letting them out because I was checking only the ReadFiles.

Thank you for taking the time to walk me through.

**Comment by billziss-gh** [comment]
These read-aheads happen internally to the file system. When a READ arrives the file system instructs the cache manager to service it. The cache manager attempts to copy the data into the supplied buffer and it page faults if the data is not already there. This results in a recursive READ that is marked as "Paging I/O". It is at this point that the file system hits the disk, network, etc. or in the case of WinFsp the user mode file system.

I do not know what method procmon uses to track I/O. It likely does not track IRP's. Use the excellent [FileSpy](http://www.zezula.net/en/fstools/filespy.html) tool and look for "paging" IRP_MJ_READ.

**Comment by billziss-gh** [comment]
BTW, NTFS also implements FastIO, which is a fast path into the Cache Manager that avoids the creation of a full IRP in some cases. In my tests this may improve performance by as much as 20%-30%. WinFsp does not implement the FastIO optimization at this time.

You will see FastIO calls using FileSpy as FASTIO_READ, etc.

**Comment by cdarau** [comment]
Thank you for all the explanations.

Unfortunately, I still can't see any of those read-like operations (FASTIOs or IRP_MJ_READs) being issued on the file's path. A couple of mentions:
- the FileSpy tool site says it "Its functionality is similar to the famous Filemon tool from Mark Russinovich (http://www.sysinternals.com)." - where Filemon (alongside with Regmon) is the predecessor of Procmon
- ProcMon tool is able to track all those operations that you said (FASTIOs and IRP_MJ_s) but I was filtering them out cause I didn't know
- also, ProcMon inspects processes/threads, registry, networking, profiling events alongside with all filesys activity (it is an "Activity Monitor" class minifilter)
- I inspected my file path for ReadFiles, FASTIO_s, FAST IOs, IRP_MJ_s and still no sign of those much bigger reads (than 100 in length) that would have to exist in order for NTFS to acquire such speed
- I tracked all operations from the moment I downloaded the file to a new unique location up to the moment I opened it with WINWORD.EXE

From what I can tell, it only remains one possibility: can it be that when the download is issued, and the WriteFile operations grab the file locally, the buffers used in the writing process end up being stored in the memory also (by the CacheManager), but somehow underneath IO Manager, without any operation being issued? Because if this isn't the case, then the context switches implied in the WinFsp scenario cause the 15x increase in time.

**Comment by cdarau** [comment]
I saved the Procmon session in 2 ways: a .PML file (Procmon log file) and a .CSV file. The first one can be opened with Procmon as if it would have captured all events then. Because they are large (the 1st one is 109,505,614 bytes and the 2nd one is 51,285,353 bytes), I wasn't able to upload them here, but I add here the wetransfer link which expires in a week: https://wetransfer.com/downloads/29f51962828020c71e2d72a9d5b8e23420171206154556/2fe9c1fbcefa40c94100e39009b76f3c20171206154556/9a9a24

You can see in these logs that the time elapsed between the first read-like operation and the last one needed to open the file with WINWORD.EXE is only 13.3871584 seconds, from 12/6/2017 5:39:16.2382657 PM to 12/6/2017 5:39:29.6254241 PM. It is however a little bigger than that mentioned in my initial text (I was then saying around 8 seconds) because than I was filtering out all other processes than WINWORD.EXE.

I also add here the filters used in procmon.
![filters](https://user-images.githubusercontent.com/9717639/33670648-3f4e7620-daae-11e7-9a26-f211020030ac.PNG)

**Comment by billziss-gh** [comment]
> the FileSpy tool site says it "Its functionality is similar to the famous Filemon tool from Mark Russinovich (http://www.sysinternals.com)." - where Filemon (alongside with Regmon) is the predecessor of Procmon

For file system work I find FileSpy excellent. Even if Procmon is a superset of the functionality, FileSpy's focus on file I/O is fantastic.

Note that all these tools use filter functionality, so they may still lose events if the file system accidentally or purposefully circumvents filters.

> From what I can tell, it only remains one possibility: can it be that when the download is issued, and the WriteFile operations grab the file locally, the buffers used in the writing process end up being stored in the memory also (by the CacheManager), but somehow underneath IO Manager, without any operation being issued? Because if this isn't the case, then the context switches implied in the WinFsp scenario cause the 15x increase in time.

That is a likely explanation. Simply reboot your computer and when it comes back up the cache should be empty.

> I inspected my file path for ReadFiles, FASTIO_s, FAST IOs, IRP_MJ_s and still no sign of those much bigger reads (than 100 in length) that would have to exist in order for NTFS to acquire such speed

Unfortunately I am just not very familiar with Procmon so I cannot provide real insight. However some googling shows that you have to "Enable Advanced Output" under Filter. You will also have to track `IRP_MJ_READ` on the process `System`.

When I do this on my system I start seeing some Paging I/O reads.

----

Think about it like this. If there was no cache effect NTFS would have to go to the disk for every single operation.

- The disk is a slow device and certainly slower than context switches (although in the case of passthrough it is the cost of context switch + file read).
- The disk cannot service directly 100 byte reads. It will service requests in "allocation units" (usually 4096 bytes).

**Comment by billziss-gh** [comment]
@cdarau let me know if you have additional questions here, otherwise we can close this.

**Comment by cdarau** [comment]
No, thank you for support. You can close it.
