### ISSUE TITLE
wishlist: give launcher an ability to monitor volume activity

### ISSUE THREAD

**Issue by mhogomchungu** [billziss-gh/winfsp#124]
Currently, ```launchctl list``` prints a list a managed volumes and returns immediately. This makes it hard to monitor for volume activity because it will require running the command on a specific time interval to check if a volume was added/removed from the list.

In linux, udisks has an option ```monitor``` and in macos, diskutil has an option ```activity``` and both options make their respective tools hang indefinitely until terminated by a signal and causes these tools to print to stdout when they noticed an activity.

Will it be possible to add the ability to "launchctl" to give it the above behavior?

**Comment by billziss-gh** [comment]
The launcher monitors the file system processes for various reasons. But the launcher protocol does not have a way to subscribe for such notifications currently. I think it is possible but non-trivial to modify the launcher and launchctl to provide this functionality. The alternative of having launchctl poll the launcher issuing `list` commands itself is simpler, but simply moves the problem from SiriKali to launchctl.

May I suggest an (imperfect) alternative instead. Can you listen for the [`WM_SETTINGCHANGE`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms725497(v=vs.85).aspx) message? According to [`DefineDosDevice`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363904(v=vs.85).aspx) this message gets sent when a drive is added/removed. You can use this message as a simple notification that something changed in the system and then use [`GetLogicalDrives`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364972(v=vs.85).aspx) to check whether the drive bitmask has changed and how. If the drive bitmask is changed, you have good reason to believe that a user mode file system has been mounted/unmounted and you can issue that `list` command to find out how exactly.

Caveats:

- I have not used `WM_SETTINGCHANGE` in recent memory and do not know if it works for this purpose.
- This would only catch file systems that are mounted on a drive. It would not catch file systems mounted on a directory or not at all (which is possible on Windows). This may be ok for your use case.

**Comment by mhogomchungu** [comment]
Will try your suggestion first.

**Comment by billziss-gh** [comment]
BTW, additional things to look at: [`WM_DEVICECHANGE`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363480(v=vs.85).aspx) and [`SHChangeNotifyRegister`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762120(v=vs.85).aspx).

**Comment by mhogomchungu** [comment]
I have decided to go with polling the launcher using the launcher allows me to use the same code path for two things.

1. I get notified when a volume is added/removed.
2. When a volume is added, the launcher provides all the information i need to display on the GUI and i see no reason and way of avoiding the launcher.

For now,i spin on a  two seconds intervals waiting for something to happen[1].

I am closing this one since i have found a way to do what i want.

[1] https://github.com/mhogomchungu/sirikali/blob/b2383000ebb56a8cf62125459c2fee97b393ecdb/src/mountinfo.cpp#L444

**Comment by billziss-gh** [comment]
Did handling the `WM_*` Windows messages not provide you with the information you need?

I am a bit concerned with constant polling of the launcher. The reason is that the launcher was designed as a single threaded app that would run rarely. For this reason, I have chosen a very simple design for it: for example, only a single client is allowed to connect to the launcher at a time. If a particular process connects to it all the time, it might disallow other processes from doing so.

**Comment by mhogomchungu** [comment]
I did not try the windows API path. Today was the first time i had enough time to work on this and after thinking about it, i went with the current design because it meant the same code paths are used for both monitoring and getting volume properties.

Using windows API will mean having two totally different code paths for the two functionality and i was hoping to avoid it.

Will now look into using windows API for monitoring since launcher this seems to be abusing the launcher.

**Comment by mhogomchungu** [comment]
I just noticed that its now impossible to monitor for device appearing/disappearing because securefs does not do anything at the moment.

Will revisit this when securefs can cause devices to be appear/disapper.
