### ISSUE TITLE
net use x: \\sshfs\%username%=user@server password fails on win 7 64 bit

### ISSUE THREAD

**Issue by Shaddoh** [billziss-gh/winfsp#127]
I have installed winfsp and sshfs-win. I can get win 10 devices working. On any win 7 device I have failed. 

net use x: \\\\sshfs\%username%=user@server password
The above returns "system error 67 has occurred."

The below works but does not persist on boot
Open a command prompt.
cd C:\Program Files (x86)\SSHFS-Win\bin
set CYGFUSE=WinFsp
set PATH=C:\Program Files (x86)\SSHFS-Win\bin
sshfs.exe -f -o idmap=user user@server: z:
Gives a RSA authentification error, buit lets you say yes or no to connect. 
After this it says service has started and you type in password.

Any help or advice is much appreciated. Thank you

----

Before submitting this issue please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Issue type**: Please consider posting only bug reports or enhancement requests. Questions are better in the [WinFsp Google Group](https://groups.google.com/forum/#!forum/winfsp).
- [x] **No Duplicate**: Ensure that your issue has not been filed before. (Check open and closed issues.)
- [x] **Description**: Provide a descriptive title and a detailed explanation of the problem you are experiencing (for a bug report) or you are trying to solve (for an enhancement request).
- [x] **Reproduce**: For bug reports provide detailed information on how to reproduce the problem. For enhancement requests you do not need to provide this information, unless you find it relevant.
- [x] **Behaviors**: Provide information on the expected and actual behaviors.
- [x] **Environment**: For bug reports provide information about your OS version and build (e.g. 10.0.14393) and WinFsp version and build (e.g. 2017.2 or 1.2.17341). For enhancement requests you do not need to provide this information, unless you find it relevant.

**Comment by billziss-gh** [comment]
Thank you for reporting this in the right place. This is indeed a problem with WinFsp on Windows 7.

As mentioned in billziss-gh/sshfs-win#17: The problem appears to be that the launcher service (WinFsp.Launcher) is unable to launch the SSHFS-Win file system. This is because the `CreateProcessW` Windows API fails with `ERROR_NO_SYSTEM_RESOURCES` when launched with `EXTENDED_STARTUPINFO_PRESENT`. This special invocation of `CreateProcessW` is used when launching a file system that requires credentials. Normal invocations of `CreateProcessW` work.

The `CreateProcessW` failure appears to be an OS bug, but one we must nevertheless find a work around for. The fix will likely be to not use `EXTENDED_STARTUPINFO_PRESENT` during `CreateProcessW` on Win7. This fix will appear in v1.3. Given the seriousness of the problem, I might backport this to the `release/1.2` branch.

> The below works but does not persist on boot
> ...
> sshfs.exe -f -o idmap=user user@server: z:
> Gives a RSA authentification error, buit lets you say yes or no to connect.
> After this it says service has started and you type in password.

This behavior is by design. The fact that you are able to supply a password and the file system works, proves that the problem is isolated within the launcher.

**Comment by billziss-gh** [comment]
Commit b2e474658db4bc3fd3ac92342b4aa8e867090f29 should fix this.

This commit works around the `CreateProcessW` problem on Win7. Since this is an important problem that makes SSHFS-Win unusable for most on Win7, I am planning to release an update to WinFsp 2017.2 that will include this fix soon.

**Comment by Shaddoh** [comment]
Thank you very much for working on this. I am new to using this software but it is amazing and have implemented it in several places.

**Comment by billziss-gh** [comment]
The latest [release](https://github.com/billziss-gh/winfsp/releases/tag/v1.2POST1) is out and should fix this problem. Please try it and let me know.

**Comment by Shaddoh** [comment]
The net use command now works. However, My normal procedure is to run this command and then reboot and re select the drive in the file explorer. It will error and i put in username and password and then it stays connected after reboot. 

In this case now after reboot the drive does not stay mounted. I can run a script to mount it on boot but thought you would be able to fix it with the code. 



Thank you 
Matthew Amo 
Planet Access

**Comment by billziss-gh** [comment]
I believe you have to use the `/persistent:yes` option to `net use` to have the connections persist. Have you tried that?

**Comment by Shaddoh** [comment]
I apoligize. That worked. Thank you. 


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by billziss-gh** [comment]
@Shaddoh no problem. I am glad it did.

**Comment by Shaddoh** [comment]
Hello Bill, 

On my test win 7 box, The new version worked like it should. I went to apply to the live client computer and it gets the error 53 network not found. I can manually set it and it works. BUT some weird notes. 

net use x : \\sshfs\useronpc=useronserver@server password /persistent:yes 

This is the above command i am using. 
I was copying and pasting from my notes and I forgot to change the useronpc to there local username, so it was the username from a different computer. And it actually worked when that username was not on the computer I was running the command. weird. 

The 2 computers are both win 7 pro. So I am not sure why one works and one does not. Nor do I expect you to know with limited info. But maybe point me in a trouble shooting direction. 

Steps I did was uninstall the old version of winfsp , reboot, install new version, run commands. 



Thank you 
Matthew Amo 
Placs

**Comment by Shaddoh** [comment]
ok, I apologize for so many emails. I have some pieces to the puzzle. I got it working on both computers. On the second computer I used the username of the first computer and it worked. Not sure why at all. Just giving you as much info as I know. 



Thank you 
Matthew Amo 
Placs

**Comment by billziss-gh** [comment]
> net use x : \\sshfs\useronpc=useronserver@server password /persistent:yes
> 
> This is the above command i am using.
> I was copying and pasting from my notes and I forgot to change the useronpc to there local
> username, so it was the username from a different computer. And it actually worked when that
> username was not on the computer I was running the command. weird.

The important username is the `useronserver`. This is required by SSHFS to allow authentication.

The `useronpc` username is not strictly necessary. What it does is allow full access to the file system to the Windows user `useronpc`. If that user does not exist the file system will still work, but you may get "access denied" errors in some cases.

I recommend not using the `useronpc=` part if you are using the latest versions of WinFsp and SSHFS-Win. They do a pretty go job at figuring out the right Windows user on their own.

```
net use x : \\sshfs\useronserver@server password /persistent:yes
```

**Comment by Shaddoh** [comment]
Hello Bill, 

I just wanted to give you some feed back. The below command had worked to mount the drive but gave security error when trying to save from excel. The solution was to install the latest version of winsfp. After that the commands all worked perfect. Thank you 

Thank you 
Matthew Amo 
Placs
