### ISSUE TITLE
Launcher: Add PATH env or set child's WD in CreateProcess

### ISSUE THREAD

**Issue by felfert** [billziss-gh/winfsp#130]
Hi Bill,

Currently, a "filesystem" exe **can not find** winfsp's dlls unless a PATH to winfsp's bin/ is set, the working directory is set to winfsp's bin/ or the relevant dlls are copied/bundled with the "filesystem" .exe.

This limitation should be lifted by either setting a PATH or the working directory of the newly launched executable. For security reasons, I personally would prefer the working directory solution.

Will create just another PR for that...
Cheers
 -Fritz

----

Before submitting this issue please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Issue type**: Please consider posting only bug reports or enhancement requests. Questions are better in the [WinFsp Google Group](https://groups.google.com/forum/#!forum/winfsp).
- [x] **No Duplicate**: Ensure that your issue has not been filed before. (Check open and closed issues.)
- [x] **Description**: Provide a descriptive title and a detailed explanation of the problem you are experiencing (for a bug report) or you are trying to solve (for an enhancement request).
- [N/A] **Reproduce**: For bug reports provide detailed information on how to reproduce the problem. For enhancement requests you do not need to provide this information, unless you find it relevant.
- [N/A] **Behaviors**: Provide information on the expected and actual behaviors.
- [N/A] **Environment**: For bug reports provide information about your OS version and build (e.g. 10.0.14393) and WinFsp version and build (e.g. 2017.2 or 1.2.17341). For enhancement requests you do not need to provide this information, unless you find it relevant.

**Comment by billziss-gh** [comment]
The way that a file system is supposed to find the WinFsp DLL is by using [`FspLoad`](https://github.com/billziss-gh/winfsp/blob/v1.2POST1/inc/winfsp/winfsp.h#L1716).

This is supposed to use as in these two examples:

- [passthrough](https://github.com/billziss-gh/winfsp/blob/v1.2POST1/tst/passthrough/passthrough.c#L931-L932)
- [passthrough-fuse](https://github.com/billziss-gh/winfsp/blob/v1.2POST1/tst/passthrough-fuse/winposix.h#L74-L75)

**Comment by billziss-gh** [comment]
More information on setting this up and the rationale behind it can be found in this document:

https://github.com/billziss-gh/winfsp/wiki/WinFsp-Tutorial#create-the-project-skeleton

(Scroll down a bit where delay loading is being discussed.)

**Comment by felfert** [comment]
I see.
Well, this is a little bit problematic for me, because I'm not building my stuff on windows at all. (I'm cross-compiling on linux with mingw and still building the same source for other linux targets as well).
Problem is: I currently don't know how to generate a mingw import lib, suitable for delay loading.

BTW: The rationale of compartementalizing the dll loading is good and totally ok. My suggestion of simply setting the working directory of a service process does not contradict this.
 
So: I **will** try to figure out my problem with generating a "delayloadable" import lib in mingw.
If I don't find a solution, I will submit a PR anyway.

In case that happens: Please have at least a look at my PR (almost ready, and not very intrusive). It would make things MUCH easier.

Cheers
 -Fritz

**Comment by billziss-gh** [comment]
Fritz, are you suggesting that the launcher should be able to change the working directory of a launched service? If yes, I am not opposed to this (perhaps controllable under a registry setting).

In any case I will be happy to look at your PR.

**Comment by felfert** [comment]
Yep, thats exactly what I'm suggesting (only not configurable for the Moment). By setting the working directory of a launched service to WinFSP's bin directory, it automatically enables the launched executable to find the dll (working directory is last in dll search path).

Code is ready. I just had not yet the time to actually compile/test/create PR
You can have a preliminary look here:
https://github.com/felfert/winfsp/commit/8985a200e2ad3dc5db2c9b2b38ea46b1d9f2d7e4

Apart from that: I might just have figured out the delayload thingy ... :-)

**Comment by billziss-gh** [comment]
Actually I agree with you that I should have had the launcher always set the current working directory to the `WinFsp/bin` directory. However since this was not done originally, for compatibility purposes we should make it configurable. (Perhaps an existing file system already relies on the fact that it gets launched with `C:\Windows\System32` as the current working directory.)

I am in the midst of changes in the launcher because of the ask in #126. I am almost done with them and will check them in soon. Next I am going to look in your installer PR, which I am hoping to finalize by tonight. I will look at your latest changes after that.

**Comment by billziss-gh** [comment]
Commit e6d2ef9274a8648345d5f48846366fd446ac14ca adds this functionality.

The new registry value `WorkDirectory` controls the current directory of the file system process when it is started. If no value is passed the default is the one used for Windows services (`C:\Windows\System32`). If the special value `.` is passed, the default is the `WinFsp\bin` directory. An existing directory (e.g. `C:\`) can also be used.

**Comment by felfert** [comment]
Great! Thanks a lot.
