### ISSUE TITLE
FUSE: Disable DLL logging

### ISSUE THREAD

**Issue by KevinGuancheDarias** [billziss-gh/winfsp#134]
Hello, i'm using __jnr-fuse__ and on each request to my filesystem, there are a lot of messages like `"javaw[TID=....]: ...... "`, after researching in the source code of both __jnr-fuse__ and __winfsp__ I notice that the DDL is using a function define in __debug.c__ with seems to be the one writing all this information, is there a way, an environment variable, or anything available to disable this information?

Thanks in advance!

**Comment by billziss-gh** [comment]
By default there is no logging, unless you use the `-d` option. Are you (or jnr-fuse) passing that option to `fuse_main`?

**Comment by KevinGuancheDarias** [comment]
Done, thanks, was my mistake! :smile: , the __jnr-fuse__ debug option is also passed to the winfsp
