### ISSUE TITLE
Is there winfsp server?

### ISSUE THREAD

**Issue by James1256** [billziss-gh/winfsp#14]
winfsp has driver and np code, but how to test it? where is the server?

**Comment by billziss-gh** [comment]
I am not sure I understand what you mean by server. If you are asking what server name to use when you use the UNC syntax `\\server\share\path`, then WinFsp uses the convention of using the file system name as the server name.

For example, the WinFsp installer includes the MEMFS example file system. You can map a new MEMFS file system by mapping a network drive to `\\memfs64\any-share-name` from Windows Explorer. Similarly if you download the SSHFS for Windows file system, you can map a network drive by using the syntax `\\sshfs\user@host`.

The WinFsp download page at http://www.secfs.net/winfsp/download/ includes further instructions on how to download and test the file systems provided.

Finally I would ask that such questions be directed to the [WinFsp Google Group](https://groups.google.com/forum/m/#!forum/winfsp).

**Comment by James1256** [comment]
Sorry, my mean is not so clear. I mean winfsp is client, only client can't work. But I understand you mean, winfsp use standard protocol, so the server end is in OS. In other way, winfsp can map to remote OS, as windows network map disk.

**Comment by billziss-gh** [comment]
Excellent. It looks like this has been explained. I will close this issue.
