### ISSUE TITLE
Mounted directory not suitable for some applications

### ISSUE THREAD

**Issue by laubed** [billziss-gh/winfsp#140]
I tried to use a mounted directory as a project folder in Inventor 2018.

How to reproduce:

1. Open Inventor 2018 (You can install a trial version).
2. Press Projects and New
3. Use a folder inside a network drive (sshfs) as project folder
4. When finishing it sais that it coul not create a working environment in the specified folder

Excpecations:
I excpect that a network drive acts like a normal drive. Espacially for normal file create/write/delete operations.

Environment:
Windows 10.0.16299
Winfsp 1.2.17346
Sshfs 2.7.17334

Thank you for your great software :)

----

Before submitting this issue please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Issue type**: Please consider posting only bug reports or enhancement requests. Questions are better in the [WinFsp Google Group](https://groups.google.com/forum/#!forum/winfsp). Please also consult the [WinFsp Frequently Asked Questions](https://github.com/billziss-gh/winfsp/wiki/Frequently-Asked-Questions).
- [x] **No Duplicate**: Ensure that your issue has not been filed before. (Check open and closed issues.)
- [x] **Description**: Provide a descriptive title and a detailed explanation of the problem you are experiencing (for a bug report) or you are trying to solve (for an enhancement request).
- [x] **Reproduce**: For bug reports provide detailed information on how to reproduce the problem. For enhancement requests you do not need to provide this information, unless you find it relevant.
- [x] **Behaviors**: Provide information on the expected and actual behaviors.
- [x] **Environment**: For bug reports provide information about your OS version and build (e.g. 10.0.14393) and WinFsp version and build (e.g. 2017.2 or 1.2.17341). For enhancement requests you do not need to provide this information, unless you find it relevant.

**Comment by billziss-gh** [comment]
@laubed thanks for the bug report. Let me ask a few clarification questions:

- Are You using [SSHFS-Win](https://github.com/billziss-gh/sshfs-win) or another version of sshfs?
- Are you mounting SSHFS as a network drive X: using the syntax `\\sshfs\user@server` or do you run sshfs from the command line (in which case please supply full command line)?
- When you say "mounted directory": Do you mean that you mount the file system as a drive and try to use a subdirectory of that drive? Or do actually mean that you mount the file system as a directory? (This is actually possible with WinFsp, although not directly exposed by SSHFS-Win.)

**Comment by laubed** [comment]
@billziss-gh thank you for the fast reply.

- I use SSHFS-Win from http://www.secfs.net/winfsp/download/ (x64)
- I mount SSHFS as network drive Y: using \\sshfs\user@server with "Connect to network drive..." in Windows
- I create a project folder inside the mounted drive manually (e.g. Y:\Test) and try to use it inside Inventor. SSHFS is not mounted inside an existing directory on a local drive.

**Comment by billziss-gh** [comment]
Thanks for the detailed steps. I will try to download and use Inventor to see if I can identify where SSHFS is failing.

One thing to try is to run Inventor over MEMFS. If you have installed the "Developer" component of WinFsp you should have MEMFS and should be able to mount it as `\\memfs64\share` using "Map Network Drive".

**Comment by laubed** [comment]
Using Inventor with \\memfs64\share results in the same problem.

**Comment by laubed** [comment]
Another even simpler application is using git. I use "Git extensions" so i don't know if these are raw git issues or some combination of git & git extensions.

**Comment by billziss-gh** [comment]
> Using Inventor with \\memfs64\share results in the same problem.

This is certainly interesting and points to a more general WinFsp incompatibility or problem.

> Another even simpler application is using git.

Git clone appears to work on MEMFS (see below). This latter problem looks like some kind of permission issue with SSHFS configuration.

```
Y:\>git clone https://github.com/billziss-gh/winfsp.git
Cloning into 'winfsp'...
remote: Counting objects: 15322, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 15322 (delta 2), reused 5 (delta 0), pack-reused 15310
Receiving objects: 100% (15322/15322), 5.93 MiB | 1.21 MiB/s, done.
Resolving deltas: 100% (10089/10089), done.

Y:\>dir winfsp
 Volume in drive Y is MEMFS
 Volume Serial Number is 1085-2145

 Directory of Y:\winfsp

02/02/2018  08:23 AM    <DIR>          .
02/02/2018  08:23 AM    <DIR>          ..
02/02/2018  08:23 AM    <DIR>          .github
02/02/2018  08:23 AM                93 .gitmodules
02/02/2018  08:23 AM             1,840 appveyor.yml
02/02/2018  08:23 AM    <DIR>          art
02/02/2018  08:23 AM    <DIR>          build
02/02/2018  08:23 AM            16,997 Changelog.asciidoc
02/02/2018  08:23 AM             6,082 Contributors.asciidoc
02/02/2018  08:23 AM    <DIR>          doc
02/02/2018  08:23 AM    <DIR>          ext
02/02/2018  08:23 AM    <DIR>          inc
02/02/2018  08:23 AM            36,642 License.txt
02/02/2018  08:23 AM    <DIR>          opt
02/02/2018  08:23 AM             5,264 README.md
02/02/2018  08:23 AM    <DIR>          src
02/02/2018  08:23 AM    <DIR>          tools
02/02/2018  08:23 AM    <DIR>          tst
               6 File(s)         66,918 bytes
              12 Dir(s)  4,370,464,768,000 bytes free
```

**Comment by laubed** [comment]
This might be related but i don't know. When i create a folder using Windows Explorer inside my sshfs mapped network drive i get a folder with it contents write protected (A box in the properties window indicating that folder contents are write protected)
But doing the same on menfs64 there is also a write protection for contents.

The strange thing is that i can create and edit files inside these directories with most editors just fine (memfs and sshfs)

**Comment by laubed** [comment]
The issue might be related to file permissions when using sshfs / sftp.
Creating Files and Folders via Windows (mounted as network drive) and creating files localy creates them with different permissions
```
drwxrwxr-x 2 dlaube dlaube 4096 Feb  5 01:00 TestLinux
-rw-rw-r-- 1 dlaube dlaube    0 Feb  5 01:01 TestLinux.txt
drwx------ 2 dlaube dlaube 4096 Feb  5 01:00 TestWindows
-rwx------ 1 dlaube dlaube    0 Feb  5 01:00 TestWindows.txt
```

So perhaps different umask values makes sense (or use the default supplied via the sftp server)

**Comment by laubed** [comment]
Another application that has issues: Visual Studio Code. If you try to create a file inside it, it will abort with some kind of permission error.

**Comment by billziss-gh** [comment]
@laubed I have been traveling and have not had the chance to look into the original problem more closely. I am hoping to do so this week.

Regarding the permission problems that you are experiencing: the Windows and POSIX security models are very different. There is a mapping between the two security models, but it is by no means perfect.

I am suspecting that there is a permission mismatch in your SSHFS-Win setup, which is creating these issues.

**Comment by laubed** [comment]
I installed WinFsp and SSHFS-Win with the supplied installers. Is there something i need to do afterwards to get permissions right?

**Comment by billziss-gh** [comment]
It might be that SSHFS-Win does not set up permissions right in all cases.

SSHFS-Win attempts to match the Windows client user to the SSHFS server user and give it full permissions. This is trivial if the usernames match and usually works well even if the user names do not match. Do the usernames match in your scenario (i.e. is the Windows client user name the same as the SSHFS server user name)?

An additional consideration is that on Windows the same user often has different permissions based on the context they run a particular program. For example, a user may be elevated as Administrator.

**Comment by laubed** [comment]
No they don't match. But using the `\\sshfs\locuser=user@host\` syntax does not solve the issue.
Running Visual Studio Code as Administrator does not solve the issue either.

**Comment by billziss-gh** [comment]
I am closing this although it was never resolved, because it is a very old issue.

If the problem persists against modern WinFsp, please reopen.
