### ISSUE TITLE
Enhancement: Turn files/directories beginning with dot invisible

### ISSUE THREAD

**Issue by laubed** [billziss-gh/winfsp#142]
Enhancement request:
Files and folders beginning with a dot should get the invisible flag in windows. That would keep mounted drives more organized (think of many dot folders in home directories).

Expected behaviour:
Files and folders beginning with a dot should not be visible if "Show invisible" is turned off in explorer. If "Show invisible" is turned on, these files and folders should be visible.

Thank you :)

----

Before submitting this issue please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Issue type**: Please consider posting only bug reports or enhancement requests. Questions are better in the [WinFsp Google Group](https://groups.google.com/forum/#!forum/winfsp). Please also consult the [WinFsp Frequently Asked Questions](https://github.com/billziss-gh/winfsp/wiki/Frequently-Asked-Questions).
- [x] **No Duplicate**: Ensure that your issue has not been filed before. (Check open and closed issues.)
- [x] **Description**: Provide a descriptive title and a detailed explanation of the problem you are experiencing (for a bug report) or you are trying to solve (for an enhancement request).
- [x] **Behaviors**: Provide information on the expected and actual behaviors.

**Comment by billziss-gh** [comment]
@laubed thanks for the request.

Unfortunately I cannot agree that this is a feature that belongs in WinFsp. I can imagine a file system (or file system filter) that does what you want, but I cannot see WinFsp enforcing such behavior on all file systems.

**Comment by billziss-gh** [comment]
@laubed I have reconsidered this and have added commit 8beb534340fd0232129aff6553530d1baee8731f that adds an option `-o dot_hidden` that automatically adds the Windows hidden file attribute on dot files. (This works only on FUSE file systems of course.)

This feature should be considered experimental and will be available in the next **BETA** release (likely released within a month or two). If there are no issues with the feature it will be permanently added in the next **GOLD** release.
