### ISSUE TITLE
Edit security of file/folder from windows?

### ISSUE THREAD

**Issue by Shaddoh** [billziss-gh/winfsp#144]
I apologize I did not know where to enter this. 

I was wondering if there was any thoughts on being able to edit security access from with in windows for the data on the server?

As in the owner of the file could right click on it and open up security to everyone for a file/folder they create.

Thank you

----

Before submitting this issue please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [ ] **Issue type**: Please consider posting only bug reports or enhancement requests. Questions are better in the [WinFsp Google Group](https://groups.google.com/forum/#!forum/winfsp). Please also consult the [WinFsp Frequently Asked Questions](https://github.com/billziss-gh/winfsp/wiki/Frequently-Asked-Questions).
- [ ] **No Duplicate**: Ensure that your issue has not been filed before. (Check open and closed issues.)
- [ ] **Description**: Provide a descriptive title and a detailed explanation of the problem you are experiencing (for a bug report) or you are trying to solve (for an enhancement request).
- [ ] **Reproduce**: For bug reports provide detailed information on how to reproduce the problem. For enhancement requests you do not need to provide this information, unless you find it relevant.
- [ ] **Behaviors**: Provide information on the expected and actual behaviors.
- [ ] **Environment**: For bug reports provide information about your OS version and build (e.g. 10.0.14393) and WinFsp version and build (e.g. 2017.2 or 1.2.17341). For enhancement requests you do not need to provide this information, unless you find it relevant.

**Comment by billziss-gh** [comment]
In general right-click on a file/directory, then "Properties", then "Security" should work.

Did I misunderstand your question?

**Comment by Shaddoh** [comment]
Well that is embarrassing, Someone told me it did not work and I did not test it and went straight to you as you have always been very helpful. I just tested it and it works fine on files. My apologies. 
Any suggestions on how to have a person access more then one share with just one user account? 


Thank you 
Matthew Amo 
Placs

**Comment by billziss-gh** [comment]
> Well that is embarrassing, Someone told me it did not work and I did not test it and went straight to you as you have always been very helpful. I just tested it and it works fine on files. My apologies.

No problem. I figured it must have been some kind of misunderstanding.

> Any suggestions on how to have a person access more then one share with just one user account?

I do not quite understand this question. I thought this is already possible? A single user can access multiple accounts.

**Comment by Shaddoh** [comment]
So the when you mount the drive, it opens to what you have their home destination set to. On a server where you have multiple shares to different locations, how would they access a different share? 

Thank you 
Matthew Amo 
Placs

**Comment by billziss-gh** [comment]
I am sorry, I still do not understand. I would need a lot more details in order to help.

- What file system are you using? (SSHFS-Win, something else?)

- How do you open this file system? Do you use the `\\sshfs\path` syntax with `net use` or Explorer or something else?

**Comment by Shaddoh** [comment]
ok, On the server. We create a user. The home directory of that user we set to where we want the mount command to open up to. So we enter in the path to data in /Data/shared/projectmanagers 
There is another location of /Data/Detailer that i would want them to see but I do not want them to log directly in to /Data as there as other shares there. 

the command i use is 
net use x: \\sshfs\serverusername@server password /persistent:yes 
Which then mounts the home directory of the server user to the windows box. 

Thank you 
Matthew Amo 
Placs

**Comment by billziss-gh** [comment]
The SSHFS-Win syntax allows you to specify both server and path.

So you should be able to mount two different paths under the same server as different drives. For example:

```
\\sshfs\USER@server\Data\shared\projectmanagers\USER
\\sshfs\USER@server\Data\Detailer\USER
```

Of course you will have to set up your SSHFS server accordingly.

**Comment by Shaddoh** [comment]
Sweet, I will test it out. Thanks 

Thank you 
Matthew Amo 
Placs

**Comment by billziss-gh** [comment]
Glad to be of help. Closing this.

**Comment by Shaddoh** [comment]
I got clarification from my guy. He was saying that yes you can right click on a file and grant access to everyone. But you can not click add and add a user that is on the server and then give rights to just one other user. It errors out. I was able to replicate before this time :) 


Thank you 
Matthew Amo 
Placs
