### ISSUE TITLE
Sharing mounted directory issue

### ISSUE THREAD

**Issue by jyeori** [billziss-gh/winfsp#145]
You want to share the mounted directory using your winfsp.
However, I noticed some problems.
Sample code passthrough is used.
First, when I access the mounted directory from the outside, I can not see the list.
This problem is considered a problem with GetSecurity () and you can change the option of GetKernelObjectSecurity ().
(OWNER_SECURITY_INFORMATION | GROUP_SECURITY_INFORMATION | DACL_SECURITY_INFORMATION -> PROTECTED_DACL_SECURITY_INFORMATION)
This shows the list of files, but there is another problem.
Frequently, when opening a file, a message is displayed stating that the directory path is invalid or not authorized.
I need help please.

-

**Comment by billziss-gh** [comment]
It is somewhat hard to figure out the exact problem you are experiencing. Can you please post a detailed sequence of steps that exhibits the problem you are experiencing as well as the error or errors you are seeing?

> GetKernelObjectSecurity ().
(OWNER_SECURITY_INFORMATION | GROUP_SECURITY_INFORMATION | DACL_SECURITY_INFORMATION -> PROTECTED_DACL_SECURITY_INFORMATION)

Are you saying that you are getting an error during directory listing operations unless you add the `PROTECTED_DACL_SECURITY_INFORMATION` flag?

> Frequently, when opening a file, a message is displayed stating that the directory path is invalid or not authorized.

Please post details on how you are launching the file system and which user is trying to access it. For example, it is possible to have problems if you are launching the file system as an administrator and trying to access it as a user and vice-versa.

**Comment by jyeori** [comment]
step1. I ran passthrough with the following command:
[passthrough -p C: \ WinFSP \ STORAGE -m C: \ WinFSP \ MOUNT]

step2. I created a symbolic link to share the mount directory.
[mklink / j C: \ WinFSP \ MOUNT_SYM C: \ WinFSP \ MOUNT]

step3. MOUNT_SYM directory shared on the same network

step4. There was a problem with directory listing when another PC on the same network accessed.
![image](https://user-images.githubusercontent.com/36683214/36459675-0dded838-16f8-11e8-982e-a7cea1cc6850.png)

step5. I changed the GetKernelObjectSecurity () option to PROTECTED_DACL_SECURITY_INFORMATION, so the directory listing seems to be OK.
![image](https://user-images.githubusercontent.com/36683214/36459694-26a7c690-16f8-11e8-81dd-6a9972256bd5.png)


step6. There is a problem. There was a problem opening the file.
I did not find any obvious cause when debugging.
![image](https://user-images.githubusercontent.com/36683214/36459760-62719962-16f8-11e8-9bbf-a958b59ce2ff.png)
![image](https://user-images.githubusercontent.com/36683214/36459766-71e4da8a-16f8-11e8-8ae0-e4b5917c0d59.png)

**Comment by billziss-gh** [comment]
Thank you for the details steps. I will try this tomorrow.

**Comment by jyeori** [comment]
Are you sharing the WinFSP folder?
reply : C: \ WinFSP \ MOUNT could not be shared. So the idea was to use symbolic links to share.

Does \\192.168.70.153\mount work?
Does accessing the file system locally work (either via C:\WinFSP\MOUNT or C:\WinFSP\MOUNT_SYM)?
reply : locally worked without any problems.
However, this only becomes a problem if another PC on the same network accesses it.

**Comment by billziss-gh** [comment]
I believe the issue may be that you are using junctions and network paths and the two do not play well together. I cannot recall the exact limitations right now, but I know that (for example) you cannot use a junction to expose a network file system. BTW, this is a Windows and not a WinFsp issue.

In your scenario you are going through SRV2 to a junction (`mount_sys`) to another junction (`mount`), which finally points to the real file system. Rather complicated. Is it not possible to mount the passthrough file system as a drive and then just share that drive?

Another idea is to try a directory symlink (`mklink /d`) rather than a junction.

**Comment by jyeori** [comment]
I mounted it as a drive through the following command.
[passthrough -p C: \ WinFSP \ STORAGE -m K:]

However, the drive could not share.
So I created a link through the following command.
[mklink / d C: \ WinFSP \ MOUNT_SYM K:]

And C: \ WinFSP \ MOUNT_SYM on the same network.
However, the problem still appears.

What can I do?

**Comment by billziss-gh** [comment]
WinFsp is specifically tested for the network share scenario, although only the MEMFS file system is tested. It may be that something is missing in the passthrough file system to be properly shared as a drive. I will investigate.

**Comment by billziss-gh** [comment]
Ok, I had a chance to investigate this. I was able to access the passthrough file system via the network in all scenarios (Windows 10).

- Sharing a passthrough drive: For this to work it is important the create the passthrough drive under the SYSTEM account. The reason for this is that drives on Windows are local to the user's "drive namespace" and not accessible to other users, unless they are created by the SYSTEM account. The `NetShareAdd` API (which is used to share a folder or drive) only works with "globally visible" drives (i.e. those created by the SYSTEM account).
    - I used the `psexec` utility to create the drive under the SYSTEM account. WinFsp also provides a special service (`WinFsp.Launcher`) which can be used for the same purpose.

- Sharing a passthrough directory: This was straightforward. I created a passthrough drive on my desktop using `passthrough -p PATH -m ...\Desktop\pt` and then a junction using `mklink /j jn pt`. I then shared my `Desktop`. I was able to access the file system both via the `jn` link and the `pt` link.

So it is unclear to me why you experience those errors.

**Comment by jyeori** [comment]
Thank you for your interest.

but I do not understand, I attached procedure again.

![1](https://user-images.githubusercontent.com/36683214/36518977-254f7a0c-17cc-11e8-9027-ce3d0d2fb01d.JPG)

![2](https://user-images.githubusercontent.com/36683214/36518980-28c5024c-17cc-11e8-8b63-40d6852ab096.JPG)

My account(OPENSITE) is an administrator group.
![image](https://user-images.githubusercontent.com/36683214/36519404-9ff8d30a-17ce-11e8-918a-6922f7677237.png)

![3](https://user-images.githubusercontent.com/36683214/36518981-2ab40652-17cc-11e8-9b1e-6fb422ab505a.JPG)

![4](https://user-images.githubusercontent.com/36683214/36518983-2c431116-17cc-11e8-8630-736843cdbd4d.JPG)

![5](https://user-images.githubusercontent.com/36683214/36518986-2e50f31a-17cc-11e8-8184-1bb5e465022e.JPG)

What is missing?

**Comment by billziss-gh** [comment]
A couple of thoughts:

- In my testing I shared the parent folder of `MOUNT_SYM` (i.e. `WWinFSP`). This would make the share `\\192.168.70.153\WWinFSP\MOUNT_SYM`.

- Do you by any chance start the passthrough file system as Administrator? Can you try starting it without being elevated?

    <img width="166" alt="screen shot 2018-02-22 at 12 49 55 pm" src="https://user-images.githubusercontent.com/15330948/36563456-fd703d20-17ce-11e8-8dfb-66a6b11bdcb5.png">

    While I cannot read your language, the colon (`:`) suggests that this may be translated to "Administrator: Command Prompt" rather than just "Command Prompt".

**Comment by jyeori** [comment]
Sorry,.. I was late because of another job ....

1. The same problem occurs if you share the parent folder of MOUNT_SYM.

2,3. As you said, I activated the Administrator account and logged in with the Administrator account. The privilege has not risen. And I ran passthrough. But the same problem occurs.
