### ISSUE TITLE
Enhancement: SSHFS via ssh tunnel

### ISSUE THREAD

**Issue by laubed** [billziss-gh/winfsp#146]
Hi,

one thing i would like to see is mounting a remote machine via an ssh tunnel. In my work environment i require to access some machines that are behind a firewall (won't get them forwarded). The only way to access them is via an ssh tunnel. (sshfs has a feature to support that https://superuser.com/questions/139023/how-to-mount-remote-sshfs-via-intermediate-machine-tunneling)

is it possible that this will be implemented in a future version?

----

Before submitting this issue please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Issue type**: Please consider posting only bug reports or enhancement requests. Questions are better in the [WinFsp Google Group](https://groups.google.com/forum/#!forum/winfsp). Please also consult the [WinFsp Frequently Asked Questions](https://github.com/billziss-gh/winfsp/wiki/Frequently-Asked-Questions).
- [x] **No Duplicate**: Ensure that your issue has not been filed before. (Check open and closed issues.)
- [x] **Description**: Provide a descriptive title and a detailed explanation of the problem you are experiencing (for a bug report) or you are trying to solve (for an enhancement request).
- [x] **Reproduce**: For bug reports provide detailed information on how to reproduce the problem. For enhancement requests you do not need to provide this information, unless you find it relevant.
- [x] **Behaviors**: Provide information on the expected and actual behaviors.
- [x] **Environment**: For bug reports provide information about your OS version and build (e.g. 10.0.14393) and WinFsp version and build (e.g. 2017.2 or 1.2.17341). For enhancement requests you do not need to provide this information, unless you find it relevant.

**Comment by masaeedu** [comment]
These seem to be two different problems. You can do ssh tunneling using a regular `ssh` invocation with `-L`/`-R` as appropriate to forward the remote machine's port 22 to a local port, then simply use SSHFS to connect to that.

**Comment by billziss-gh** [comment]
@laubed apologies for my late response.

This issue appears to be about the [SSHFS-Win](https://github.com/billziss-gh/sshfs-win) file system and not WinFsp. I suggest we move it there.

SSHFS-Win supports the simple use-case of connecting to an SSH server using username/password out of the box. However it also includes a Cygwin port of SSHFS which can be used from the command line or scripts more or less the same way that you would use it on Linux.

**Comment by xelra** [comment]
This has nothing to do with either winfsp, sshfs or sshfs-win. This is simply about creating an ssh tunnel. The op can do that with either putty or cygwin's openssh.

**Comment by laubed** [comment]
i don't think so. Connecting to a machine through an ssh tunnel should be made available through the gui that winfsp provides. 
I mentioned that sshfs even has a dedicated option to create a tunnel on it's own. Because of that it would be nice to integrate that in some kind of syntax for the gui to pass it to the underlying sshfs.

**Comment by xelra** [comment]
That is not a dedicated option of sshfs for wrapping the connection in an additional tunnel, it's an option to run an arbitrary ssh command.

Maybe you can do just the same thing with sshfs-win in its cygwin environment.

**Comment by DarthSpock** [comment]
Native Windows Open-SSH (in beta!) is available, could progress be made using this: https://github.com/PowerShell/Win32-OpenSSH

**Comment by billziss-gh** [comment]
I agree with @xelra that this discussion does not belong in WinFsp.
