### ISSUE TITLE
in-memory file system

### ISSUE THREAD

**Issue by daemon-7** [billziss-gh/winfsp#147]
hi, 
The memfs.exe is an in-memory file system(include MemfsDisk MemfsNet MemfsCaseInsensitive). This is a Non persistence file system. I wish such a file system like that, when I start the computer, I need to start a program that display my file system. I can read and write any files in it. When I stop the program the file system will be hidden. When I restart the computer, the original files still exists in that file system.

Is express clearly?(^-^)

[MEMFS is an in-memory file system](https://groups.google.com/forum/#!topic/winfsp/-Ff97mkfLsk)

**Comment by billziss-gh** [comment]
I think I understand your request. You want MEMFS to have the ability to persist its files and restore the state of the file system as it was when it is started again.

I use MEMFS primarily for testing WinFsp and I would therefore like to keep it as simple as possible. For this reason it is unlikely that I would be adding this functionality. Perhaps a sensible plan would be to create a new file system (e.g. MemfsEx) and add this functionality there? It is unlikely that I would have the time to do this work myself however.
