### ISSUE TITLE
Passthrough filesystem locks files

### ISSUE THREAD

**Issue by masaeedu** [billziss-gh/winfsp#149]
WinFSP version: 2018.1 B2

## Problem:
Passthrough filesystem (at least passthrough-cygfuse) locks files that are deleted from underlying filesystem.

## Repro steps
 - Build `passthrough-cygfuse.exe` from `tst/passthrough-fuse`
 - Clone a large .NET solution (e.g. https://github.com/droyad/Assent)
 - Start up `.\passthrough-cygfuse.exe -o umask=rwx -f <path to checkout> Y:`
 - `cd` to FUSE drive and run `msbuild /t:restore,build .\Assent.sln`. Ensure build completes successfully
 - `cd` to checkout location and run `git clean -xdf` to delete all generated artifacts
 - `cd` to FUSE drive and run the build again

## Expected behavior
Everything builds fine the second time.

## Actual behavior
Access denied errors that look like this:

```
Build FAILED.

"Y:\Assent.sln" (restore;build target) (1) ->
"Y:\src\Assent\Assent.csproj" (default target) (2:20) ->
"Y:\src\Assent\Assent.csproj" (Build target) (2:21) ->
(CoreCompile target) ->
  CSC : error CS2012: Cannot open 'Y:\src\Assent\obj\Debug\netstandard1.3\Assent.dll' for writing -- 'Access to the path 'Y:\src\Assent\obj\Debug\netstandard1.3\Assent.dll' is denied.' [Y:\src\Assent\Assent.csproj]


"Y:\Assent.sln" (restore;build target) (1) ->
"Y:\src\Assent\Assent.csproj" (default target) (2:20) ->
"Y:\src\Assent\Assent.csproj" (Build target) (2:22) ->
  CSC : error CS2012: Cannot open 'Y:\src\Assent\obj\Debug\net45\Assent.dll' for writing -- 'Access to the path 'Y:\src\Assent\obj\Debug\net45\Assent.dll' is denied.' [Y:\src\Assent\Assent.csproj]


"Y:\Assent.sln" (restore;build target) (1) ->
"Y:\src\Assent\Assent.csproj" (default target) (2:20) ->
"Y:\src\Assent\Assent.csproj" (Build target) (2:23) ->
  CSC : error CS2012: Cannot open 'Y:\src\Assent\obj\Debug\netstandard2.0\Assent.dll' for writing -- 'Access to the path 'Y:\src\Assent\obj\Debug\netstandard2.0\Assent.dll' is denied.' [Y:\src\Assent\Assent.csproj]

    0 Warning(s)
    3 Error(s)
```

----

Before submitting this issue please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Issue type**: Please consider posting only bug reports or enhancement requests. Questions are better in the [WinFsp Google Group](https://groups.google.com/forum/#!forum/winfsp). Please also consult the [WinFsp Frequently Asked Questions](https://github.com/billziss-gh/winfsp/wiki/Frequently-Asked-Questions).
- [x] **No Duplicate**: Ensure that your issue has not been filed before. (Check open and closed issues.)
- [x] **Description**: Provide a descriptive title and a detailed explanation of the problem you are experiencing (for a bug report) or you are trying to solve (for an enhancement request).
- [x] **Reproduce**: For bug reports provide detailed information on how to reproduce the problem. For enhancement requests you do not need to provide this information, unless you find it relevant.
- [x] **Behaviors**: Provide information on the expected and actual behaviors.
- [x] **Environment**: For bug reports provide information about your OS version and build (e.g. 10.0.14393) and WinFsp version and build (e.g. 2017.2 or 1.2.17341). For enhancement requests you do not need to provide this information, unless you find it relevant.

**Comment by billziss-gh** [comment]
Thanks for the bug report. I am currently underwater as I am working on a new file system, but I am hoping to look into this in the near future.

This may have some relation to this: #104

**Comment by bionicbee** [comment]
I'm not sure if it's exactly the same issue, but I noticed something that may be related to this issue. If I mount a passthrough-cpp file system pointing to a clean sync of UE4 and run a script `GenerateProjectFiles.bat` then the passthrough-cpp process will have a large number of file handles still open even though the batch file has finished executing.

My precise scenario:

* clone https://github.com/EpicGames/UnrealEngine
* build passthrough-cpp from v1.3B3
* Invoke passthrough-cpp in debugger with arguments `-p d:\UnrealEngine -m d:\pass1` or equivalent
* Open the d:\pass1 directory in Explorer
* Double-click on GenerateProjectFiles.bat
* Check the "Handles" tab for the `passthrough-cpp` process in Process Hacker
* Note that lots of files remain open

I haven't really dug into the code yet so have no ideas what might be wrong but it looks like maybe there's some life cycle related issue with passthrough-cpp or elsewhere?

**Comment by billziss-gh** [comment]
@bionicbee unfortunately I failed to add the new `FlushAndPurgeOnCleanup` option to the passthrough [`VolumeParams`](https://github.com/billziss-gh/winfsp/blob/v1.3B3/tst/passthrough/passthrough.c#L691). If you add this option to the code it should instruct WinFsp to aggressively close files and not cache them indefinitely.

Please note that the proposed change is against passthrough (the C version) and not passthrough-cpp (the C++ version) as I never quite finished the C++ layer.
