### ISSUE TITLE
FileInfoTimeout=0 not enforced ?

### ISSUE THREAD

**Issue by benrubson** [billziss-gh/winfsp#155]
Hi,

Using the FUSE API for Cygwin v1.2POST1 / 2017.2 (in [EncFS port](https://github.com/billziss-gh/winfsp/issues/152)), even if I set `-oattr_timeout=0`, I need to add the WinFsp option `-oFileInfoTimeout=0` to get the expected behavior (when the underlying file is modified, to get the correct stat info on FUSE side immediately).
Strange because this seems to be done [here](https://github.com/billziss-gh/winfsp/blob/v1.2POST1/src/dll/fuse/fuse.c#L610) (however `set_FileInfoTimeout` is never initialized to 0).

Many thx 👍 

Ben

**Comment by billziss-gh** [comment]
This turned out to be a silly typo and was addressed in commit d6c38491209e4c0b091e3f22660f6fc89bf5a75a.

**Comment by benrubson** [comment]
Excellent, thank you very much @billziss-gh 👍
