### ISSUE TITLE
Support EBADMSG / STATUS_DATA_ERROR ?

### ISSUE THREAD

**Issue by benrubson** [billziss-gh/winfsp#156]
Hi,

Using the FUSE API for Cygwin v1.2POST1 / 2017.2 in [EncFS port](https://github.com/billziss-gh/winfsp/issues/152), I encountered the following need.

EncFS may return `EBADMSG` if underlying data has been corrupted :
`#define EBADMSG 77 /* Bad message */`

EncFS returns this specific code when authentication of decoded data fails (when data is corrupted, even perhaps intentionally by a bad person). This allows to quickly identify an issue with data decoding, whereas the default `EIO` could refer to many other (sometimes low-level) things.

Unfortunately WinFsp does not seem to handle this return code, as `EPERM` is returned instead.
I also tested `EILSEQ`, but the calling program then receives `EINVAL`.
For the moment I then choosed `EINVAL` itself.

Could it be possible somehow to map `EBADMSG` to for example `STATUS_DATA_ERROR` ?
Goal is that when EncFS returns `EBADMSG`, calling app gets `EBADMSG`.

That said, perhaps `EILSEQ` is preferable, as we are more here in presence of an "illegal bytes sequence" than a "bad message".
Thus perhaps the `EILSEQ` existing mapping to `STATUS_INVALID_PARAMETER` could be updated, so that calling program would receive `EILSEQ`.

Thank you very much 👍 

Ben

**Comment by billziss-gh** [comment]
Ben, as I am getting close to releasing the next beta, I am looking at this issue again. Let's see if we can finalize this.

- `STATUS_DATA_ERROR` is *"{Data Error} An error occurred in reading or writing data"*. [[link](https://msdn.microsoft.com/en-us/library/cc704588.aspx)]

- `STATUS_DATA_ERROR` is mapped to the Win32 `ERROR_CRC` (according to an old Microsoft article that no longer seems to exist). WinFsp maintains these mappings here: [`ntstatus.txt`](https://github.com/billziss-gh/winfsp/blob/master/tools/gensrc/ntstatus.txt#L163).

- `ERROR_CRC` is *"Data error (cyclic redundancy check)"*. [[link](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx)]

- Neither Cygwin nor MSVCRT seem to map any Windows error/status code to `EBADMSG`. This is from a cursory examination of (an older version) of Cygwin's `winsup\cygwin\errno.cc` and Microsoft's `ucrt\misc\errno.cpp`.

- Cygwin seems to convert `ERROR_CRC` to `EIO`. Thus even if WinFsp converted `EBADMSG` to `STATUS_DATA_ERROR`, you would still end up with `EIO` on Cygwin.
    ```
    EBADMSG --FUSE-> STATUS_DATA_ERROR --Win32-> ERROR_CRC --Cygwin-> EIO
    ```

- `EILSEQ` seems quite wrong to me. It is defined by C to mean something different. [[link](https://en.wikipedia.org/wiki/Errno.h)]

**Comment by billziss-gh** [comment]
@benrubson ?

**Comment by benrubson** [comment]
Sorry Bill I was stuck far from my computer :-|
So thank you for coming back to this !

Sounds like then 'EBADMSG' can't be fully mapped, until perhaps it is mapped by Cygwin as well. Am I right ?

'EILSEQ', as per the documentation you gave, seems more appropriate to UTF8 concerns. The message "Invalid bytes sequence" sounded however good for such "encoding" errors.
Would we face same problem as with 'EBADMSG', can't it be mapped properly ?

What would you perhaps suggest ?
Goal is to distinguish between encoding errors and (low-level) IO errors.

Thank you Bill !

**Comment by billziss-gh** [comment]
I don't have a good suggestion. It seems to me that `EIO` is the right error code to return. But I understand that you want a different error code.

I am looking at the allowed `read` error codes in [opengroup.org](http://pubs.opengroup.org/onlinepubs/9699919799/functions/read.html). `EBADMSG` is there and so is `EINVAL`. Given that we cannot send `EBADMSG`, perhaps `EINVAL` (which I believe you now return) is a good option.

(BTW, do you have any "insider info" on why `EBADMSG` was chosen in the first place?)

**Comment by billziss-gh** [comment]
> We may then stick to EINVAL, or go back to EIO and refer to log messages for further details.

Currently this may be the best course of action.

> Even if it's not in read and write allowed codes, what about EILSEQ ?

`EILSEQ` has a deceptively fitting error description in POSIX: *"Illegal byte sequence"*. But it really means something else. Glibc now returns *"Invalid or incomplete multibyte or wide character"* according to [man errno](http://man7.org/linux/man-pages/man3/errno.3.html).

For example, I would probably return `EILSEQ` if [`MultiByteToWideChar`](https://msdn.microsoft.com/en-us/library/windows/desktop/dd319072(v=vs.85).aspx) failed or something.

> Cygwin does not seem to map anything to EILSEQ, as per its errno.cc.
This then prevent us from a proper mapping ?

That is my understanding, yes.

> Yes, among all the system errors, "Bad message" was the one which described the best our use case : a data block which can't be decrypted due to bad bytes, to a corrupted authentication header etc...

Although I believe `EBADMSG` was originally invented for a different purpose, I think I like this choice the most out of the ones you have presented as alternatives to `EIO`. And it is an allowed `read` error code, so presumably programs might be ready to receive it (and likely misinterpret it).

Perhaps the thing to do here is to involve Cygwin in this discussion and see if we can map any Windows error to `EBADMSG`. The full conversion would be:

    EBADMSG  ---WinFsp-->  STATUS_X  ---Win32-->  ERROR_X  ---Cygwin-->  EBADMSG

**Comment by billziss-gh** [comment]
Closing this as the effort vs reward ratio seems somewhat lopsided. Please reopen if you feel strongly about it.
