### ISSUE TITLE
Performance on Cygwin, FS_PERSISTENT_ACLS

### ISSUE THREAD

**Issue by benrubson** [billziss-gh/winfsp#158]
Hi,

I'm using the FUSE API for Cygwin v1.2POST1 / 2017.2 in [EncFS port](https://github.com/billziss-gh/winfsp/issues/152).

I focused on `readdir()` performance, and found that when `readdir()` occurs, each file of the directory is as expected stated, but also opened.
Of course, and unfortunately, this leads to an important performance impact.

I then asked for help on Cygwin list, and sounds like there should be a solution to avoid opening files.
Here is the discussion : https://cygwin.com/ml/cygwin-developers/2018-03/msg00002.html

> - Make sure the filesystem returns valid inodes and make sure to set `FS_PERSISTENT_ACLS`.
> - Also make sure that `NtQueryDirectoryFile(FileIdBothDirectoryInformation)` works on your FS, and make sure to return a valid inode number in the structure.

Could it be something possible on WinFsp side ?

Many thanks 👍 

Ben

**Comment by billziss-gh** [comment]
- WinFsp reports "persistent ACL's" for FUSE file systems: https://github.com/billziss-gh/winfsp/blob/v1.2POST1/src/dll/fuse/fuse.c#L614
- WinFsp responds correctly to `FileIdBothDirectoryInformation`. However I note that short file names are not supported, so the short name is not filled.
- WinFsp does not care about inode numbers as discussed elsewhere, but does respect them if set: https://github.com/billziss-gh/winfsp/blob/v1.2POST1/src/dll/fuse/fuse_intf.c#L435

**Comment by benrubson** [comment]
Thank you Bill for your confirmation 👍 
Sounds like then inode number should be set on FUSE FS side, so that WinFsp gets it and then sends it to the caller program, Cygwin for instance.
I'm however sorry but still a little bit lost where should I set this inode number :-|
I would say into the `stat` structure given to the `fuse_fill_dir_t` filler function of the `readdir` call ?

**Comment by billziss-gh** [comment]
> I would say into the stat structure given to the fuse_fill_dir_t filler function of the readdir call ?

Yes, I believe so.

**Comment by benrubson** [comment]
Thank you Bill for your help 👍
Closing this now.
