### ISSUE TITLE
Sharing a Drive

### ISSUE THREAD

**Issue by SammyB428** [billziss-gh/winfsp#16]
WinFSP 0.14.16197 created drive cannot be shared on Windows 10.0.10586. Steps to reproduce:

Open a CMD window as Administrator, create a memfs as my T: drive:
"\Program Files (x86)\WinFsp\bin\memfs-x64.exe" -s 10485760 -m T:

Open a CMD window as Administrator, create a share to T: so SMB clients can access it
net share MyShare=T:\

Results in error message:
The device or directory does not exist.

More help is available by typing NET HELPMSG 2116.

Trying to create the share as a normal user and you get the ever-so-informative error of "Access Denied"

**Comment by billziss-gh** [comment]
Thanks for the report.

This scenario has received no testing yet. Here are some preliminary findings:

1) The issue with the drive not being visible has to do with how DefineDosDeviceW interacts with the rest of the system. Quote from the DefineDosDeviceW docs:

> Starting with Windows XP, this function creates a device name for a caller that is not running in the "LocalSystem" context in its own Local MS-DOS device namespace. If the caller is running in the "LocalSystem" context, the function creates the device name in the Global MS-DOS device namespace.

It appears that `net share` requires sharable drives to be in the Global MS-DOS device namespace. Here is how I was able to make the drive seen by `net share`. I used `psexec` from [SysInternals](https://technet.microsoft.com/en-us/sysinternals/pxexec).

    psexec -i -s cmd.exe

A new command prompt will open up running in the "LocalSystem" context. Then you can change to the `WinFsp\bin` directory and issue the command:

    memfs-x64.exe -S "O:WDG:WDD:P(A;;FA;;;WD)" -m T:

You should now be able to share the new drive from Windows Explorer.

2) After fixing permissions on the new drive and some testing I found numerous issues, even with basic things like opening files or listing directories. At this time WinFsp cannot be used to reliably share drives over the network.

Clearly this is a critical bug and will be fixed.

**Comment by billziss-gh** [comment]
Important additional information on this NTFSD thread:

http://www.osronline.com/showThread.cfm?link=80903

**Comment by billziss-gh** [comment]
Looking into this now. I should have a progress update soon.

**Comment by billziss-gh** [comment]
Here is a long overdue update on this.

It is now possible to share a drive. The easiest way to demonstrate this is by:

    cd "\Program Files (x86)\WinFsp\bin"
    launchctl-x64 memfs64 disk "" T:
    net share memfs64=T:\ /grant:everyone,change

This will launch a new MEMFS file system under the SYSTEM account and then share it under the name "memfs64".

Here is where WinFsp currently stands with testing this scenario. Almost all tests pass. There is one persistent failure with memory mapped files, when the FILE_FLAG_NO_BUFFERING flag is being used and the test is run through a localhost share (i.e. `\\localhost\memfs64`). The interesting thing is that NTFS also seems to fail under some similar circumstances. I am trying to determine whether this is indeed a WinFsp bug, and if yes, how to resolve it.

For the time I am keeping this issue open, but I believe resolution should be close.

**Comment by billziss-gh** [comment]
I have confirmed that the memory mapped issue is an issue with the Win8 OS and not with the WinFsp FSD.

For the full details see this [NTFSD thread](http://www.osronline.com/showthread.cfm?link=279909).

I am closing this issue. WinFsp is fully functional under this scenario. There are a couple of minor issues left, but they are being tracked and will be resolved by RC1 timeframe.
