### ISSUE TITLE
Quick question: on 64 bit windows, are 32 bit clients required to use 32 bit winfsp or they can use either one?

### ISSUE THREAD

**Issue by mhogomchungu** [billziss-gh/winfsp#163]
Nothing is here because the header the full question.

Edit:
To provide context, i distribute 32 bit binaries of encfs[1] and i am unsure of what version of winfsp i should recommend for 64 bit users of windows.

[1] https://github.com/mhogomchungu/encfs/releases

**Comment by billziss-gh** [comment]
The WinFsp installer includes both 32-bit and 64-bit components. 32-bit clients use the 32-bit DLL (winfsp-x86.dll).

There is only one version of WinFsp to install.

**Comment by mhogomchungu** [comment]
I just checked and you are right!

I was in a hurry when i asked the question and i think i confused winfsp with sshfs-win because i am 100% sure i downloaded both version of one of your projects switched them around for a reason i cant remember now.

Sorry for the noise.
