### ISSUE TITLE
Ability to process "private" ioctl code

### ISSUE THREAD

**Issue by willynt** [billziss-gh/winfsp#165]
We are missing a way to exchange extra information about a file, and allow communication between client apps and filesystem server.
Typically, we used to do that by processing private ctlcode (e.g. within a predefined range).
The client app send/receive data using DeviceIoControl() windows API, specifying in and out buffers.
The usermode filesystem would expose a new function in FSP_FILE_SYSTEM_INTERFACE to process these ctlcode.
Such function could be something like:
`NTSTATUS (*IoCtl)(FSP_FILE_SYSTEM *FileSystem,
        PVOID FileContext, ULONG ctlcode,
        PVOID inBuffer, ULONG InBufferSize,
        PVOID outBuffer, ULONG outBufferSize, ULONG* pBytesReturned);`

Any chance that new feature could be implemented in a new release?
Thx!

**Comment by billziss-gh** [comment]
I agree that such a feature would be very useful and should be implemented.

Presumably this would be done using [`DeviceIoControl`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363216(v=vs.85).aspx). It should be noted that on Windows this API can be used to send both "ioctl" codes and "fsctl" codes. Only "ioctl" codes can be supported. ("Fsctl" codes are those the have a device type of `FILE_DEVICE_FILE_SYSTEM` in [`CTL_CODE`](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/defining-i-o-control-codes).)

Another consideration is the "Transfer Type" to use. I expect that only [`METHOD_BUFFERED`](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/defining-i-o-control-codes) will be supported and that buffers will be limited by the WinFsp request/response [maximums](https://github.com/billziss-gh/winfsp/blob/v1.3B3/inc/winfsp/fsctl.h#L75-L78). The maximums are close to 16K, but we should probably restrict the "ioctl" buffers to about 4K. Would these be ok for your use case @willynt?

(Aside: while 16K are the maximums for individual WinFsp requests/responses, this does not restrict the buffers passed during `Read`/`Write` which are passed using a memory mapping mechanism and can be arbitrarily big.)

A relevant libfuse [FAQ entry](https://github.com/libfuse/libfuse/wiki/FAQ#why-doesnt-fuse-forward-arbitrary-ioctl-calls-to-the-filesystem):

> **Why doesn't FUSE forward arbitrary `ioctl()` calls to the filesystem?**
>
> Because it's not possible: data passed to `ioctl()` doesn't have a well defined length and structure like `read()` and `write()`. Consider using `getxattr()` and `setxattr()` instead.

**Comment by willynt** [comment]
ioctl or fsclt, it does not really matter, no problem using ioctl only.
METHOD_BUFFERED is perfectly fine, just like the 4KB "limitations".

**Comment by billziss-gh** [comment]
Commit 894ae7b8f39940e440fd8701c147bd084f517b89 adds `Control` to `FSP_FILE_SYSTEM_INTERFACE`:

```C
    /**
     * Process control code.
     *
     * This function is called when a program uses the DeviceIoControl API.
     *
     * @param FileSystem
     *     The file system on which this request is posted.
     * @param FileContext
     *     The file context of the file or directory to be controled.
     * @param ControlCode
     *     The control code for the operation. This code must have a DeviceType with bit
     *     0x8000 set and must have a TransferType of METHOD_BUFFERED.
     * @param InputBuffer
     *     Pointer to a buffer that contains the input data.
     * @param InputBufferLength
     *     Input data length.
     * @param Buffer
     *     Pointer to a buffer that will receive the output data.
     * @param Length
     *     Output data length.
     * @param PBytesTransferred [out]
     *     Pointer to a memory location that will receive the actual number of bytes transferred.
     * @return
     *     STATUS_SUCCESS or error code.
     */
    NTSTATUS (*Control)(FSP_FILE_SYSTEM *FileSystem,
        PVOID FileContext, UINT32 ControlCode,
        PVOID InputBuffer, ULONG InputBufferLength,
        PVOID OutputBuffer, ULONG OutputBufferLength, PULONG PBytesTransferred);
```

This change is currently in the [pvt-devctl](https://github.com/billziss-gh/winfsp/tree/pvt-devctl) branch. It will be included in the v1.4 (2018.2) update.

**Comment by billziss-gh** [comment]
Commit 637a1dac7ec32a2aba81d6221a78af238c1c9e5e also adds `Control` to the .NET layer (currently untested).

**Comment by billziss-gh** [comment]
This functionality has now been merge into the master branch.

**Comment by willynt** [comment]
Awesome, thx Bill!
