### ISSUE TITLE
Failed to mount disk, error 0xc0000022

### ISSUE THREAD

**Issue by sploid** [billziss-gh/winfsp#167]
I have tried to use memfx-x86 but failed to mount a disk with error 0xc0000022.
Error text: "The service memfs has failed to start (Status=0xc0000022)".

Diagnostic log from PC:
[out.log](https://github.com/billziss-gh/winfsp/files/1984794/out.log)
Screenshot:
![image](https://user-images.githubusercontent.com/5768411/39769684-8a41b376-52f5-11e8-9ebb-783c5c66b543.png)

Environment: OS - Win7 x64 bit. WinFSP version - WinFsp 2017.2

**Comment by billziss-gh** [comment]
Status `0xc0000022` is `STATUS_ACCESS_DENIED`. This usually happens when a Win32 API fails because a bad buffer is passed; the API catches the exception and converts it into a status code.

The 32-bit MEMFS on 64-bit Windows is tested on every AppVeyor build (for example in [this log](https://ci.appveyor.com/project/billziss-gh/winfsp/build/1067/job/wdoge6u2009a0kuc) many of the `-x86` logs are such tests).

So this problem is not easily reproducible. Is it possible to debug this problem on the machine that exhibits it and find the API that fails?

**Comment by billziss-gh** [comment]
BTW, I also notice that you have copied the DLL in the same folder as MEMFS. Please make sure that you do not mix and match DLL and FSD (File System Driver) versions.

**Comment by sploid** [comment]
Unfortunately, we cannot debug soft on the user PC. It is our customer, we can only give to him custom build with additional debug logs.
What do you think if we rebuild dll and change function FspNtStatusFromWin32 to macros and print file:line number where it was called with fail?
Can it help us to detect where is the problem?

**Comment by billziss-gh** [comment]
@sploid that is actually a great idea!

You may get a bit of noise in the logs, because errors can happen during normal processing, but this should pinpoint the API that fails.

**Comment by sploid** [comment]
1. I have found that "memfs-x86.exe -m M: -u \memfx\share" start correctly, but "memfs-x86.exe -m M:" fail.
2. the problem is in this method "FspFsctlCreateVolume", here:
    VolumeHandle = CreateFileW(DevicePathBuf,
        0, FILE_SHARE_READ | FILE_SHARE_WRITE, 0, OPEN_EXISTING, FILE_FLAG_OVERLAPPED, 0);
this method failed with result ERROR_ACCESS_DENIED.

**Comment by billziss-gh** [comment]
When you use the `-u` switch you create a "network" drive. Without it you create a "disk" drive.

In the case of the "network" drive, the `\Device\WinFsp.Net` control device is opened. In the case of a "disk" drive the `\Device\WinFsp.Disk` control device is opened.

A possibility is that the "Access Denied" error happens immediately during the `CreateFileW` security check done by the IO Manager. Both control devices should have the same permissions, (based on [this device class GUID](https://github.com/billziss-gh/winfsp/blob/v1.1/inc/winfsp/fsctl.h#L39)). For this reason I find it unlikely that one should succeed where the other should fail at the IO Manager level.

Continuing down the creation of the file system eventually [`FspVolumeCreateNoLock`](https://github.com/billziss-gh/winfsp/blob/v1.1/src/sys/volume.c#L89) gets called. This performs different tasks depending on whether a "network" or "disk" drive is created. In the case of a "network" drive we register with the [MUP](https://github.com/billziss-gh/winfsp/blob/v1.1/src/sys/volume.c#L249-L269). In the case of a "disk" drive we create [an additional device](https://github.com/billziss-gh/winfsp/blob/v1.1/src/sys/volume.c#L89) that will serve as the "disk" for our file system. I also find it unlikely that this would fail with "access denied".

Immediately after creation of the file system devices, but before `CreateFileW` returns, there is also the possibility that some additional requests are sent to the newly created devices by the OS or some filter. These could fail with "access denied", although it would be hard to speculate why.

The driver itself returns `STATUS_ACCESS_DENIED` in a few areas and only when the Windows file system protocol requires it (e.g. during some `Rename`'s). I doubt that it is the driver itself that is failing the requests.

For me, this leaves some unknown filter as the primary culprit. (A possibility is also a corrupt OS or installation.) Can you use the [`fltmc`](https://ss64.com/nt/fltmc.html) command with `filters` and `instances` parameters to determine what filters run on the system exhibiting this behavior?
