### ISSUE TITLE
Cannot unmap drive

### ISSUE THREAD

**Issue by carlreinke** [billziss-gh/winfsp#17]
Testing on Windows 7 Enterprise (Build 7601, x64).

I am not able to disconnect mapped drives.  It claims success, but the mapped drive persists and continues to function.  (Using Windows Explorer produces similar results.)

```
C:\>mkdir y:\foo

C:\>net use y: /delete
y: was deleted successfully.


C:\>dir y:
 Volume in drive Y is MEMFS
 Volume Serial Number is 0DAC-2CB8

 Directory of Y:\

07/29/2016  12:08    <DIR>          .
07/29/2016  12:08    <DIR>          ..
07/29/2016  12:17    <DIR>          foo
               0 File(s)              0 bytes
               3 Dir(s)  17,146,314,752 bytes free
```

Normal SMB-based mapped drives disconnect normally.

**Comment by billziss-gh** [comment]
Ok, this does not happen on Windows 10 which is my primary system. I will retest and see if it's a problem on Windows 7. I am currently traveling and may be unable to resolve this in a timely manner.

**Comment by carlreinke** [comment]
No worries. :)

**Comment by billziss-gh** [comment]
I am unable to reproduce this on Win7 32-bit (or Win 10 64-bit). I tried from both elevated and non-elevated command prompts:

    C:\Users\billziss>net use Y: \\memfs32\share
    The command completed successfully.
    
    
    C:\Users\billziss>mkdir y:\foo
    
    C:\Users\billziss>dir y:
     Volume in drive Y is MEMFS
     Volume Serial Number is 0DAE-2CA1
    
     Directory of Y:\
    
    07/30/2016  11:33 PM    <DIR>          .
    07/30/2016  11:33 PM    <DIR>          ..
    07/30/2016  11:33 PM    <DIR>          foo
                   0 File(s)              0 bytes
                   3 Dir(s)  17,146,314,752 bytes free
    
    C:\Users\billziss>net use y: /delete
    y: was deleted successfully.
    
    
    C:\Users\billziss>dir y:
    The system cannot find the path specified.

Can you please post a detailed list of steps to reproduce the problem?

**Comment by carlreinke** [comment]
In a non-elevated command prompt, I followed the commands you used, and the mapped drive persisted through the delete.

In an elevated command prompt, I cannot map the drive.
```
C:\WINDOWS\system32>net use y: \\memfs32\share
System error 85 has occurred.

The local device name is already in use.


C:\WINDOWS\system32>net use x: \\memfs32\share
System error 67 has occurred.

The network name cannot be found.
```
(I couldn't use `Y:` here because it remains mapped from the non-elevated command prompt.)

I guess unless you have some diagnostics that I can try, we may have to wait for someone else to have this issue and then try to find the commonality.

**Comment by carlreinke** [comment]
I am able to reuse drive mappings if I delete the `memfs-*.exe` process that created it.

Ignore what I said about not being able to map the drive from the elevated prompt.  I wasn't able to map it because it was already mapped to `Y:`.  Mapping a different MEMFS UNC path worked from the elevated prompt.

**Comment by billziss-gh** [comment]
@carlreinke I am looking into this again.

I just tested it using the upcoming RC1 against:

- Win10 Pro x64
- Win8 x64
- Win7 x86

I tested from both elevated and non-elevated prompts. [In all cases I used an account in the Administrators group.] I tested using the following commands:

    net use y: \\memfs64\share # or \\memfs32\share when on x86
    mkdir y:\foo
    dir y:
    net use y: /delete
    dir y:

In all cases things worked as expected: The network share was created. The `mkdir` and first `dir` commands worked as expected. The network share was successfully deleted and the second `dir` command reported that the drive did not exist.

Are you still experiencing this issue? Since I have never been able to reproduce it I am hesitant to close it without understanding what the problem was (or is).

**Comment by carlreinke** [comment]
I did some more testing.  It appears to be a bug in the Dokan filesystem driver.  Reordering WinFSP above DokanNP in Network Connections→Advanced→Advanced Settings...→Provider Order makes the issue go away.  (I had no idea this settings dialog existed when I filed this bug.)

I guess DokanNP is swallowing operations that don't belong to it.

**Comment by carlreinke** [comment]
(This was with [Dokany 0.7.4](https://github.com/dokan-dev/dokany/releases/tag/v0.7.4) -- I haven't tested newer versions to see if the issue still exists.)

**Comment by billziss-gh** [comment]
Dokan still haunts me :)

Thanks for the heads up. BTW, where is the Network Connections dialog?

**Comment by carlreinke** [comment]
Oh, I meant the Advanced Settings dialog in the Network Connections area of Control Panel.  Network Connections in Windows 7 is reached via Control Panel→Network and Sharing Center→Change adapter settings.  The "Advanced" menu in Network Connections exposes some settings dialogs that I was previously unaware of.

**Comment by billziss-gh** [comment]
Thanks, I was not aware of this dialog either. And it is not as easy to find on Windows 10.

For future reference here is a blog article that describes how to find it:
http://blogs.interfacett.com/changing-the-network-provider-order-in-windows-10
