### ISSUE TITLE
Add missing properties and helper in the C# wrapper

### ISSUE THREAD

**Issue by FrKaram** [billziss-gh/winfsp#174]
The **FlushAndPurgeOnCleanup** option is not available in the C# wrapper (as of today) neither is the **FSPVersion** Helper class.

Would be great if those properties / helpers were available also in .net

**Comment by billziss-gh** [comment]
@FrKaram thanks. As discussed in the mailing list I am happy to accept a PR on this, but if you do not find the time to do it, then I will look at it myself in the near future.

**Comment by FrKaram** [comment]
I'll try to find time to work on that. Does the WDK version I use matter (even though it's not really important for the .net part) N

**Comment by billziss-gh** [comment]
I don't think it does. Your changes would be only in the .NET part.

**Comment by FrKaram** [comment]
Fine. Now I need to understand how you did all this :-) Never seen something like this before

**Comment by FrKaram** [comment]
OK. So I implemented **FlushAndPurgeOnCleanup**  in a way which seems logical based on what you did for other properties (I'm no interop specialist and mashalling is not what I usually do).
What should be the target of my PR (master? something else?)

Regarding FspVersion I've seen that it is already used internally in the interop class. I cannot figure out in which class it would make sense to have a matching public (static?) method.

**Comment by billziss-gh** [comment]
Sorry, I am on vacation and may not always give timely responses.

You can create a topic branch on your own fork and then create the PR against master.

Re: `Version`. I would make it a static method on `FileSystemHost`. There are already other static methods there, such as [`SetDebugLogFile`](https://github.com/billziss-gh/winfsp/blob/master/src/dotnet/FileSystemHost.cs#L346).

**Comment by FrKaram** [comment]
No worries Bill. Enjoy your vacation.

**Comment by FrKaram** [comment]
I made PR hopefully it matches your acceptance criterias. If not, just tell me what to modify.

**Comment by billziss-gh** [comment]
Closing this as #176 has now been merged in.
