### ISSUE TITLE
Can I issue a DeviceIoControl call without specifying a file?

### ISSUE THREAD

**Issue by JohnOberschelp** [billziss-gh/winfsp#179]
## Question

Is there a way to issue a `DeviceIoControl` call through `WinFsp` without specifying a file?
I have a use for `DeviceIoControl` so I am testing it in both `memfs` and `airfs`.
My call is for the volume itself, and the volume may be empty (except for good old root, of course).
But I have only been able to get it to work when the handle is to a path that specifies a file.

**Tests**

Launch `memfs` as `Z:`, and drop in a file named "`x`"
Run this adorable program I wrote to test `DeviceIoControl`...

```
#include <windows.h>
#include <stdio.h>
#include <conio.h>

/*
	Probably/possibly change the file name.
	I used this 4-line script to build:
        cd ~dp0
        call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x64
        cl Make_DeviceIoControl_Call.cpp
        pause
*/

int Call_DeviceIoControl()
{
	HANDLE Handle = CreateFileA(
		"\\\\.\\Z:\\x",
		FILE_READ_ATTRIBUTES | FILE_READ_DATA, FILE_SHARE_READ | FILE_SHARE_WRITE,
		NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
	if (Handle == INVALID_HANDLE_VALUE) return __LINE__;

	char Input[] = "\"Curiouser and curiouser!\" cried Alice.";
	char Output[256];
	ULONG Len = strlen(Input)+1;
	DWORD ControlCode = CTL_CODE(0x8000 + 'M', 'R', METHOD_BUFFERED, FILE_ANY_ACCESS);
    bool OK = DeviceIoControl(Handle, ControlCode, Input, Len, Output, Len, &Len, NULL);
    if (!OK) return __LINE__;
    printf("Input  : %s\nOutput : %s\n", Input, Output);
    return __LINE__;
}

void main()
{
	int Line = Call_DeviceIoControl();
	char Message[256];
	DWORD Flags = FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS;
	FormatMessageA(Flags, NULL, GetLastError(), MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), Message, 256, NULL);
	printf("Line %d: %s\n(paused)", Line, Message);
	getch();
}
```
So the path is "`\\\\.\\Z:\\x`", and I get the expected result of...

```
Input  : "Curiouser and curiouser!" cried Alice.
Output : "Phevbhfre naq phevbhfre!" pevrq Nyvpr.
Line 29: The operation completed successfully.
```
... but if I try to pass a path without a file, I get...

```
"\\\\.\\Z:\\"  Line 20: The system cannot find the path specified.
"\\\\.\\Z:\\." Line 27: The parameter is incorrect.
"\\\\.\\Z:"    Line 27: The parameter is incorrect.
```
Also tried the guid from `QueryDosDevice`...

```
\\?\GLOBALROOT\Device\Volume{455be5ca-9057-11e8-af42-00231413b91c}\x  works
\\?\GLOBALROOT\Device\Volume{455be5ca-9057-11e8-af42-00231413b91c}\.  doesn't
\\?\GLOBALROOT\Device\Volume{455be5ca-9057-11e8-af42-00231413b91c}\   doesn't
\\?\GLOBALROOT\Device\Volume{455be5ca-9057-11e8-af42-00231413b91c}    doesn't
```

**Comment by billziss-gh** [comment]
The FSD currently checks if the ioctl is issued on a valid file (i.e. not volume handle):

https://github.com/billziss-gh/winfsp/blob/master/src/sys/devctl.c#L61

We can probably change this. But Is issuing the ioctl against the file system root not adequate?

**Comment by billziss-gh** [comment]
BTW, you need `FILE_FLAG_BACKUP_SEMANTICS` to open directories with `CreateFile`.

**Comment by JohnOberschelp** [comment]
`Z:\` works perfectly with FILE_FLAG_BACKUP_SEMANTICS specified.
I am sorry to have bothered you with this, and thank you.

**Comment by billziss-gh** [comment]
John, no problem. I am glad this was easy to resolve.
