### ISSUE TITLE
Mounted drive is not visible to mountvol

### ISSUE THREAD

**Issue by tornaia** [billziss-gh/winfsp#182]
I am using [jnr-fuse](https://github.com/SerCeMan/jnr-fuse) on top of WinFsp they work well together however I think I found a minor thing that could improve WinFsp!

1. Start memfs
> c:\Program Files (x86)\WinFsp\bin>memfs-x64.exe -s 10485760 -m T:
> memfs -t -1 -n 1024 -s 10485760 -m T:
> The service memfs has been started.

2. Run the following Java code:
>     public static void main(String[] args) throws IOException {
>         java.nio.file.FileStore fileStore = java.nio.file.Files.getFileStore(java.nio.file.Paths.get("T:\\"));
>     }

Which will generate the following output:

> Exception in thread "main" java.nio.file.FileSystemException: T:\: Incorrect function.
> 
> 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
> 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
> 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
> 	at java.base/sun.nio.fs.WindowsFileStore.create(WindowsFileStore.java:94)
> 	at java.base/sun.nio.fs.WindowsFileSystemProvider.getFileStore(WindowsFileSystemProvider.java:483)
> 	at java.base/java.nio.file.Files.getFileStore(Files.java:1479)
> 	at XXX.main(FuseStub.java:86)

There is a [GetVolumePathNameW](https://github.com/JetBrains/jdk8u_jdk/blob/master/src/windows/native/sun/nio/fs/WindowsNativeDispatcher.c#L646) call somewhere in the deep which throws exception. Maybe it helps. :)

3. Run mountvol in command line

> C:\Users\username>mountvol
> ...
> ...
> Possible values for VolumeName along with current mount points are:
> 
>     \\?\Volume{5029553f-031b-4b76-81d1-d7a5481cb522}\
>         C:\
> 
>     \\?\Volume{7a5c3c52-f59a-499e-9175-c6fa17ca1e48}\
>         *** NO MOUNT POINTS ***
> 
>     \\?\Volume{57e590ba-87fd-4fdc-b35d-3fc5652ab5be}\
>         *** NO MOUNT POINTS ***
> 
>     \\?\Volume{7efed988-4a09-4135-817e-12ed147815f8}\
>         D:\
> 
>     \\?\Volume{526a39a1-6313-4df8-8d09-a7c041c47526}\
>         *** NO MOUNT POINTS ***
> 
>     \\?\Volume{9b6ec6bc-9f27-11e8-a1fb-e442a66bc89d}\
> The system cannot find the file specified.
>     \\?\Volume{9b6ec8e6-9f27-11e8-a1fb-e442a66bc89d}\
> The system cannot find the file specified.
>     \\?\Volume{ba1bfc5d-5314-11e7-a0f0-806e6f6e6963}\
>         E:\

and drive T:\ is not listed

After some investigation I found some info about this (or similar?) issue [here](https://github.com/dokan-dev/dokany/issues/50).

Windows 10 Pro 17134.191, WinFsp 2018.2 B2, JDK10.0.2, jnr-fuse 0.5.2.1

**Comment by billziss-gh** [comment]
WinFsp does not use the Mount Manager. It uses `DefineDosDevice`. It is unlikely that it would be changed to use the Mount Manager. (IMO the Mount Manager brings unnecessary complications with very little benefit for WinFsp use cases.)

I am not sure why `GetVolumePathName` fails. Perhaps it works for Mount Manager mounts only. I will have to investigate this further.

**Comment by billziss-gh** [comment]
WinFsp now includes support for the MountManager in the master branch. It will be part of the next beta release.

This should resolve this issue. It should be noted that `GetVolumePathName` and `GetVolumeNameForVolumeMountPoint` will work only when the MountManager is used. By default, WinFsp file systems will still use `DefineDosDevice` to create drives (i.e. **not** the MountManager). For more details see the release notes in the upcoming beta release.
