### ISSUE TITLE
Make compatible with Google Chrome

### ISSUE THREAD

**Issue by mhofman** [billziss-gh/winfsp#187]
## Enhancement Request

Google Chrome lists this application as incompatible. The page chrome://settings/incompatibleApplications is now opened automatically after a Chrome crash, and WinFSP is listed, asking the user/administrator to uninstall it. I believe this is due to the application injecting code into the Chrome process.

I don't know how WinFSP works exactly, but is there a reason it injects code into I presume all processes? You may want to avoid injecting into Chrome, as it will be blocked in the future anyway. See https://blog.chromium.org/2017/11/reducing-chrome-crashes-caused-by-third.html

![chrome incompatible app](https://user-images.githubusercontent.com/86499/44633949-36163f80-a947-11e8-8926-41e98448aa55.png)

**Comment by mhofman** [comment]
Interesting. I'll create a chromium issue, and link it here.

**Comment by mhofman** [comment]
I create [issue 877852](https://bugs.chromium.org/p/chromium/issues/detail?id=877852) against Chromium.

**Comment by billziss-gh** [comment]
BTW, WinFsp does not need to inject code into processes, because it includes a file system driver that registers itself with the Windows kernel. When a process issues a file API (e.g. `CreateFileW`) this eventually gets routed to the WinFsp driver by the kernel. Thus there is no need for code injection to provide file system functionality.

**Comment by mhofman** [comment]
So if I understand you right, the Network Provider DLL shouldn't get loaded into other random processes, even when that process opens a file dialog, or accesses a file handled by the Network Provider?
Who exactly loads that DLL then? Explorer.exe?

**Comment by billziss-gh** [comment]
I am not 100% of the circumstances under which the DLL gets loaded. It is possible that when the Open File dialog is invoked, the system loads all Network Provider DLL's automatically. This is determined by the Windows system DLL's and it is not under the control of the DLL providing Network Provider services.

**Comment by billziss-gh** [comment]
> So if I understand you right, the Network Provider DLL shouldn't get loaded into other random processes, even when that process opens a file dialog, or accesses a file handled by the Network Provider?

Some further clarification:

- When the process uses the file dialog it is possible that Network Provider DLL's are loaded implicitly (I am not certain).

- When the process opens a file using straight file API's such as `CreateFileW, `ReadFile`, etc. the DLL is **NOT** required. The call will be routed by the Windows kernel itself to the appropriate file system driver.
