### ISSUE TITLE
interop Dll looking for the native dll in the incorrect Registry Hive

### ISSUE THREAD

**Issue by abhishekchawla** [billziss-gh/winfsp#193]
On a 64 bit machine, the interop dll looks for the path of the native dll (winfsp-x64.dll) in the 32 bit registry hive. 

This isn't reproducible through WinFsp's installer as it's a 32 bit installer and puts that registry entry in the 32 bit hive, but do that through a 64 bit installer and the lookup of native dll's path fails.

The method where this lookup happens is `LoadDll()` in interop.cs

**Comment by billziss-gh** [comment]
This is by design.

WinFsp uses the 32-bit registry hive and `Program Files (x86)` because it contains both 32-bit and 64-bit components.

https://github.com/billziss-gh/winfsp/blob/master/src/dotnet/Interop.cs#L1007-L1009

**Comment by abhishekchawla** [comment]
Thanks for getting back!

Okay in that case, I'll just keep both the dlls in the same directory. One question that arises - would it matter if I register the native dll from one location, and let the interop dll load the native one from a different location?

**Comment by billziss-gh** [comment]
Technically the interop DLL can find the native DLL (via the registry) if it is in a different location. However there are two issues:

- The interop DLL and the native DLL are supposed to be the same version. There may be problems if they are different versions as this is not a supported scenario.

- If you distribute winfsp-msil.dll separately from the rest of WinFsp please ensure that you comply with the WinFsp [license](https://github.com/billziss-gh/winfsp/blob/master/License.txt).
