### ISSUE TITLE
Unable to mount drive using Explorer with Win 10 1809

### ISSUE THREAD

**Issue by ooijiyoung** [billziss-gh/winfsp#195]
## Bug Report
Unable to mount drive using Windows Explorer by using Add Network Drive

### How to Reproduce

mount a network drive with the network location "\\sshfs\user@ADDRESS\" returns "The folder you entered is not valid"  in Windows Explorer in Windows 10 1809 Update.

### Workaround 
use 'net use DRIVELETTER:  \\sshfs\user@ADDRESS\' instead of Windows Explorer to map the sshfs drive

### Environment
Windows 10 1809
WinFSP 2018.2 B3

**Comment by billziss-gh** [comment]
Did you recently upgrade to Windows 1809? Windows unfortunately resets some registry entries after the update. Try running the WinFsp installer again to repair those entries.

**Comment by billziss-gh** [comment]
No, reinstalling/repairing should have fixed it.

If you are familiar with the command line can you please run the file `diag.bat` from the directory `\Program Files (x86)\WinFsp\bin` and post the output here?

**Comment by ooijiyoung** [comment]
Hi, here's
[result.txt](https://github.com/billziss-gh/winfsp/files/2485792/result.txt)
 the output of the diag.bat
