### ISSUE TITLE
Error in renaming with passthrough example and fusepy/FUSE

### ISSUE THREAD

**Issue by touilleMan** [billziss-gh/winfsp#196]
## Bug Report

Hi, I'd like to use WinFSP for an open source project (see https://github.com/Scille/parsec-cloud/).
However I have trouble making work the provided demo so far.

I've compiled the passthrough example with MS visual studio 2017 (cl.exe indicates version 19.15.26730 for x64)

When I try to use it, renaming files doesn't work:
![cannot_find_item_passthrough](https://user-images.githubusercontent.com/3187637/47253346-91e5dc00-d451-11e8-9d92-5a4fe92c93eb.PNG)

see log file: [passthrough_rename_error.log](https://github.com/billziss-gh/winfsp/files/2497941/passthrough_rename_error.log)
and binary:  [passthrough-x64.zip](https://github.com/billziss-gh/winfsp/files/2497942/passthrough-x64.zip)

Interestingly enough, I also tried the very same binary on a VM (the [ones provided by microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and named `MSEdge on Win10 (x64) Stable (17.17134)`) and everything runs fine.

I've also tried the FUSE layer with simple in-memory python script (slightly modified version of [the fusepy example](https://github.com/fusepy/fusepy/blob/master/examples/memory.py), see enclosed) with fusepy 3.0.1 an CPython 3.6.6.
This time I can rename files, but not folders (the problem occurs on both my desktop and the VM):
![too_large_fuse](https://user-images.githubusercontent.com/3187637/47253392-0b7dca00-d452-11e8-8d58-a90a61c0a223.PNG)

logs: [fuse.log](https://github.com/billziss-gh/winfsp/files/2497944/fuse.log)
script: [fuse_memory_vanilla.zip](https://github.com/billziss-gh/winfsp/files/2497946/fuse_memory_vanilla.zip)

I suspect the `statfs` command sent to FUSE at the beginning of the operation to return incorrect data, but I couldn't tune them right so far.

### Environment

Desktop:
- Windows 10 version 1803 (OS Build 17134.345)
- WinFSP version: 1.4.18270 and 1.2.17346

VM:
- Windows 10 version 1803 (OS Build 17134.285)
- WinFSP version: 1.2.17346

**Comment by billziss-gh** [comment]
Thanks for the report. I will look into it.

**Comment by touilleMan** [comment]
Hi @billziss-gh !

> are you certain you were using WinFsp 1.4.18270? 

I've retried and failed to reproduce the error with the passthrough demo on my computer.

I've tried both mounting as a folder and a drive:
```shell
passthrough-x64.exe  -d -1 -p "exposed_dir" -m "mnt"
passthrough-x64.exe  -d -1 -p "exposed_dir" -m "K:"
```
Creating file&folder and renaming them seems all fine.

My guess is must have mixed up things while testing between different version (typically installing version `1.2.17346`, then reinstalling `1.4.18270` but previous version was active due to lack of reboot or god-knows-what post-install cleanup stage requiring two reboot instead of one...)

On the other hand I can still reproduce the "File is too large for the destination" error for in-memory FUSE-base python demo.

BTW I've started working on a winfsp binding for python (see https://github.com/Scille/winfspy/tree/follow-tuto)  in order to avoid this FUSE compatibility layer (given I couldn't figure out the issue with it, and to get a better integration with windows filesystem).
This is still work in progress but I hope it will be done soon ;-)

**Comment by billziss-gh** [comment]
> On the other hand I can still reproduce the "File is too large for the destination" error for in-memory FUSE-base python demo.

If this is an in-memory file system it likely returns `ENOSPC` (or the Windows error code `ERROR_DISK_FULL`) because it runs out of memory for the file you are intending to copy.

> BTW I've started working on a winfsp binding for python (see https://github.com/Scille/winfspy/tree/follow-tuto) in order to avoid this FUSE compatibility layer (given I couldn't figure out the issue with it, and to get a better integration with windows filesystem).
This is still work in progress but I hope it will be done soon ;-)

Fantastic. Let me know when you have it ready so that I can add it to the list here:

https://github.com/billziss-gh/winfsp/wiki/Known-File-Systems
