### ISSUE TITLE
ReadDirectory is not using STATUS_NO_SUCH_FILE?

### ISSUE THREAD

**Issue by alfaunits** [billziss-gh/winfsp#198]
Hi. This Q is related to the samples.

Should a sample ever return STATUS_NO_SUCH_FILE? I notice (at a quick glance) that the driver appears to handle a case where STATUS_NO_MORE_FILES is returned and there is nothing in the returned buffer.

But making sure this is OK (returning STATUS_NO_MORE_FILES when NO_SUCH_FILE is the correct error code), and that returning STATUS_NO_SUCH_FILE is OK?

**Comment by billziss-gh** [comment]
@alfaunits if the question has been answered, should we close this?

**Comment by alfaunits** [comment]
Yep.
