### ISSUE TITLE
Redundant WinFsp API (the original FUSE API should be enough)

### ISSUE THREAD

**Issue by dumblob** [billziss-gh/winfsp#20]
Please elaborate on the difference and (dis)advantages of the "WinFsp API" which seems redundant, because vast majority (if not all) FUSE filesystems use the "FUSE compatibility layer" API.

In README, there is only the following:

* inc/winfsp: Public headers for the WinFsp API.
* inc/fuse: Public headers for the FUSE compatibility layer.

**Comment by billziss-gh** [comment]
I disagree that the native ("WinFsp") API is redundant.

The native API is being designed to use all features available to a Windows file system. For example, a Windows file system can do the following, that cannot be (easily) made available to FUSE:

- Create and manage alternate data streams.
- Manage arbitrary security descriptors (SID's and ACL's vs POSIX permissions).
- Create and manage special files beyond what is supported through `mknod` (using reparse points).

Furthermore there are other smaller, but important, differences which nevertheless make the creation of a FUSE layer over the native API hard. For example:

- File deletion on Windows is very different from the FUSE/POSIX model.
- Symbolic links and the reparse mechanism on Windows is also very different from the POSIX/FUSE model.

For what it's worth I use the native WinFsp API for all my file systems, despite the fact that they all started as FUSE file systems (some of them using the low-level FUSE interface).

In case you have not seen this yet, there is also the native [API reference](http://www.secfs.net/winfsp/apiref/).

Finally, please consider starting such discussions on the WinFsp discussion group: https://groups.google.com/forum/#!forum/winfsp

**Comment by dumblob** [comment]
Thank you for the valuable information. I read the [API reference](http://www.secfs.net/winfsp/apiref/ ) and first then raised this issue.

>Finally, please consider starting such discussions on the WinFsp discussion group: https://groups.google.com/forum/#!forum/winfsp

This issue wasn't meant as discussion. It's a request for thorough documentation of both the differences between the two APIs, and strong reasoning for the existence of the WinFsp API.

Could you please add this elaboration and reasoning to documentation?

**Comment by billziss-gh** [comment]
I agree. I will label this as task and add this information to the documentation.

**Comment by billziss-gh** [comment]
I have written a [blog entry](http://www.secfs.net/winfsp/blog/files/native-api-vs-fuse.html) fleshing this out further. I will also add this to the project's documentation as soon as I merge the latest reparse point work.

**Comment by billziss-gh** [comment]
The "Native API vs FUSE" document has been added with commit 86d7437.

**Comment by dumblob** [comment]
Thanks.
