### ISSUE TITLE
Saving MS Office files shows 'contacting file' window many times

### ISSUE THREAD

**Issue by sganis** [billziss-gh/winfsp#201]
Excel and other office tools show an message window saying "contacting \\...\file" when saving a new file in the mounted file system.
It happens with sshfs and with my own ssh fs.
The window appears for one or two seconds several times while saving, 5 or 6 times in my machine.
- Windows 7
- WinFsp 1.4

![image](https://user-images.githubusercontent.com/2148188/48248617-2caa5880-e409-11e8-8c03-80cb6e19beed.png)

**Comment by chenzhekl** [comment]
That's reasonable since an SSH filesystem has much higher latency than a filesystem on the local disk.

**Comment by billziss-gh** [comment]
I agree with @chenzhekl. Unless I misunderstand this looks like expected behavior.

**Comment by sganis** [comment]
It does not happen in slower drives with different technology, such as nfs.
It is a bad user experience.

**Comment by billziss-gh** [comment]
You can try mounting the file system as a "disk" drive. You do this by omitting the `VolumePrefix` option.

**Comment by billziss-gh** [comment]
Closing this as I believe this is expected Windows behavior.
