### ISSUE TITLE
Can winfsp function along side dokany? thx

### ISSUE THREAD

**Issue by ccchan234** [billziss-gh/winfsp#205]
## Question
I got a win7 64b. 
Installed cppcryptfs + dokany 1.x to use with google file stream. 

Now I wanna rclone mount  M$ onedrive to my system,
and rclone mount use winfsp.

I installed winfsp by the .msi installer, installed the signed driver,
everything seems fine but I cannot rclone mount the onedrive.

The error message is 
"ERROR: local file system at C:\xxxxxx   : statfs failed: failed to read disk usage: the
system cannot find the path specified".

googled but dont found useful things.
1. in winfsp FAQ, it demo problem when dis mounting the winfsp, when there is a dokany install.
so the FAQ say both can be installed, just with problem when dismounting. ... not my case.
2. the winfsp google group ... i cant even post there.

So I ask here and hope someone could help.

thanks

_Please consider asking questions in the [WinFsp Google Group](https://groups.google.com/forum/#!forum/winfsp) instead. Before asking a question please also consult the [WinFsp Frequently Asked Questions](https://github.com/billziss-gh/winfsp/wiki/Frequently-Asked-Questions)._

**Comment by billziss-gh** [comment]
To my knowledge, yes, although it is not specifically tested.

The error message suggests that rclone fails a `statfs` call (perhaps the one during initialization, if the mount fails). This looks like an rclone usage problem. I do not know if rclone has changed the mount syntax, but you used to have to specify `M:` instead of `M$` to get the M drive.

Ping @ncw (rclone’s author) who may have some pointers.

**Comment by ccchan234** [comment]
1st thx author for quick reply.

2nd just found it's completely error.

I forgot to add a ":" in rclone mount's command.

detail is here:
https://forum.rclone.org/t/help-rclone-mount-windows/7694/23?u=ccchan234

And yes,
dokany 1.x can function alongside winfsp8.1

I didn't dismount the drives but remind others that in the FAQ, when
dismount, the order of network xxx may lead to problem.
I duno much you pls read the FAQ.
thanks all



> To my knowledge, yes, although it is not specifically tested.
> 
> The error message suggests that rclone fails a `statfs` call (perhaps the one during initialization, if the mount fails). This looks like an rclone usage problem. I do not know if rclone has changed the mount syntax, but you used to have to specify `M:` instead of `M$` to get the M drive.
> 
> Ping @ncw (rclone’s author) who may have some additional pointers.
