### ISSUE TITLE
Create sync?

### ISSUE THREAD

**Issue by alfaunits** [billziss-gh/winfsp#207]
Does WinFSP do any sync in case a second create comes while the first is in progress in user FSD? I am guessing not, but I would not want to do double sync :)

**Comment by billziss-gh** [comment]
No, multiple Create/Open's concurrently are possible.

**Comment by alfaunits** [comment]
Ah, I meant on the same file?

**Comment by billziss-gh** [comment]
They are also allowed to be concurrent I believe.

**Comment by alfaunits** [comment]
Thanks. Closing this.
