### ISSUE TITLE
Corruption when reading files >= 4G

### ISSUE THREAD

**Issue by dworkin** [billziss-gh/winfsp#218]
## Bug Report

When reading a file >= 4G in size, blocks at offset (filesize % 4G) will be zero-filled.

### How to Reproduce

Mount a filesystem containing a file >= 4G using WinFsp. The block at offset (filesize % 4G) will read as zeroes.

### Environment

- OS version and build: 10 17763.316
- WinFsp version and build: 2019.1

**Comment by billziss-gh** [comment]
Closing this as it has been addressed by your own PR. Thank you!
