### ISSUE TITLE
Run launcher as user

### ISSUE THREAD

**Issue by sganis** [billziss-gh/winfsp#220]
It could be a bug or missing some steps. I want to run the launcher service as the current user. I already added the "RunAs"="." entry in the registry under HKLM\Software\WinFsp\Services\sshfs. After rebooting, the service still runs with SYSTEM account.

**Comment by billziss-gh** [comment]
Can you clarify what you mean by "after rebooting"? The launcher does not currently support starting file systems after reboot.

Also can you please provide the full registry entries that you are using for SSHFS?

**Comment by sganis** [comment]
I rebooted as last resort, the registry change did not have effect. After mounting the drive, the launcher process was started with the SYSTEM account.
Registry:
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\WinFsp\Services\sshfs]
"Executable"="C:\\Program Files\\SSHFS-Win\\bin\\sshfs-win.exe"
"CommandLine"="%1 %2 %U"
"Security"="D:P(A;;RPWPLC;;;WD)"
"JobControl"=dword:00000001
"Credentials"=dword:00000001
"RunAs"="."
```

**Comment by billziss-gh** [comment]
The registry entries look correct and they should start sshfs-win (not the launcher) with the correct credentials. I will investigate some time later.

**Comment by sganis** [comment]
That's correct, the launcher run as SYSTEM always, sshfs.exe run as the current user. There is no bug then.
