### ISSUE TITLE
Airfs sample incorrectly returns STATUS_NOT_A_DIRECTORY

### ISSUE THREAD

**Issue by alvinhochun** [billziss-gh/winfsp#226]
## Bug Report

When trying to access a non-existent file with a part of the path being a file on airfs, `STATUS_NOT_A_DIRECTORY` is returned, causing g++ to error out.

I think it should return `STATUS_OBJECT_PATH_NOT_FOUND` instead.

```diff
diff --git a/airfs.cpp b/airfs.cpp
index 66f1a90..7156914 100644
--- a/airfs.cpp
+++ b/airfs.cpp
@@ -373,7 +373,7 @@ NTSTATUS FindNode(AIRFS_ Airfs, PWSTR Name, PWSTR *BaseName,
         {
             if (PParent) *PParent = 0;
             *PNode = 0;
-            return STATUS_NOT_A_DIRECTORY;
+            return STATUS_OBJECT_PATH_NOT_FOUND;
         }
     }
 

```

### How to Reproduce

I don't exactly have a minimal setup to reproduce it. I only checked with Process Monitor.

### Behaviors

Expected: CreateFile should return PATH NOT FOUND

Actual: CreateFile returned NOT A DIRECTORY

### Environment

- OS version and build: Windows 10 1803 (17134.648)
- WinFsp version and build: 1.4.19016

**Comment by billziss-gh** [comment]
Airfs seems to be correct here.

From a brief look this appears to protect against the case where you have a file `\path\to\file` and you try to access `\path\to\file\file2`. I think in this case the correct error code to return is `STATUS_NOT_A_DIRECTORY`.

Consider the following test under the Windows console on an NTFS drive:

```
> echo hello>foo

> type foo\bar.txt
The directory name is invalid.
```

The message the "The directory name is invalid." is `ERROR_DIRECTORY`, which is the Win32 error code for `STATUS_NOT_A_DIRECTORY`.

----

What is the exact error you are getting from g++ without your patch?

**Comment by alvinhochun** [comment]
The `type` command in cmd tries to open the path components as directories, that's when they should get `STATUS_NOT_A_DIRECTORY` and it does make sense (my change probably ignored this case).

In my case however, g++ attempted to open the file directly without checking the intermediate path components, and `STATUS_NOT_A_DIRECTORY` seems to confuse it. It literally gave the error "not a directory".

From https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55, `STATUS_NOT_A_DIRECTORY` means "A requested opened file is not a directory", which seems to be meant for when trying to open a file as a directory. However, there's also `STATUS_OBJECT_PATH_INVALID` for "The object path component was not a directory object", which seems to be the actual proper status to return.

Unfortunately I'm a bit too preoccupied to test it further at this moment

**Comment by billziss-gh** [comment]
Closing this as I believe that Airfs does the right thing here.

**Comment by carlreinke** [comment]
I've not tested airfs, but there's definitely a difference between NTFS and memfs.

NTFS:

```shell
D:\> echo foo > C:\temp\foo

D:\> echo foo > C:\temp\foo\bar
The system cannot find the path specified.

D:\> type C:\temp\foo\bar
The directory name is invalid.
```

memfs:

```shell
D:\> echo foo > M:\foo

D:\> echo foo > M:\foo\bar
The directory name is invalid.

M:\> type M:\foo\bar
The filename, directory name, or volume label syntax is incorrect.
```

**Comment by billziss-gh** [comment]
@carlreinke plz open a new issue for this. Also in your experiments with MEMFS please use the command line switches `-i -F NTFS`.
