### ISSUE TITLE
Files premission incorrectly set with create_umask.

### ISSUE THREAD

**Issue by cyberhaus** [billziss-gh/winfsp#227]
Hi,
Noticed that files are being incorrectly set. For example with a umask of 002, A new file permissions should be set to 664 and a new directory permissions set to 775. But I'm getting 775 on files and the same for directories. I was wondering if this is intentional, as windows considers all files to be executable. But for the purpose I'm using this software for its not desirable. Is it possible for you to add a new flag to apply 111 umask to only files and then apply the create_umask value to that?

**Comment by cyberhaus** [comment]
I have been looking more into this. An i have a better suggestion that you add create_file_umask and create_dir_umask flags for windows. Samba uses a similar scheme to set file permission.  umask option seems useless for windows as it only applys umask permissions on mounted filesystem and windows does not use unix file permission.

**Comment by billziss-gh** [comment]
@cyberhaus I am currently on vacation, but this is an interesting suggestion, especially if there is the Samba predecent. I will look into it when I am back.

**Comment by cyberhaus** [comment]
Samba config example
[accounting]
    comment = Accounting Department Directory
    writable = yes
    valid users = @account
    path = /home/samba/accounting
    create mode = 0660
    directory mode = 0770

**Comment by billziss-gh** [comment]
I have added commit 4f444b412e0be96ca39555c0950c729745b5210a which adds `create_file_umask` and `create_dir_umask` as per your request.

This is currently in an experimental branch, but should be available in the next beta release (within a month or two).

**Comment by cyberhaus** [comment]
Thank you, very much!

**Comment by billziss-gh** [comment]
This has now been merged into master. Please reopen if you find that it does not work as expected after the beta release.
