### ISSUE TITLE
How to debug "Cannot create WinFsp-FUSE file system."

### ISSUE THREAD

**Issue by OskarAtGitHub** [billziss-gh/winfsp#229]
I have a
```
cd C:\Program Files\SSHFS-Win\bin\
start sshfs -o create_umask=007,uid=-1,gid=-1,cache=yes,follow_symlinks,compression=no -o ssh_command="/bin/ssh.exe"....
```
working ok on two windows 7 pro machines.
However when running the same command on another machine, adding "-d", I get a
`Cannot create WinFsp-FUSE file system.`
-error. And the sshfs service fails to start.
I tried installing the newest .NET framework, but had no effect on the situation. This is a Win7 home premium install.

Any ideas on how to figure out what is causing winfsp to fail?

**Comment by billziss-gh** [comment]
A couple of questions:

- What is the status code that you see as the failure?
- What is the full command line of sshfs? (You can black out privacy-sensitive parts with `xxxx` or something.)

BTW, you do not need the .NET framework for WinFsp unless you have a .NET file system.

**Comment by OskarAtGitHub** [comment]
>     * What is the full error message that you are seeing? Is it only `cannot create WinFsp-FUSE file system` or is there an explanatory message after it?
That's the full message. (next line contains sshfs failed)
 
>     * What is the full command line of sshfs? (You can black out privacy-sensitive parts with `xxxx` or something.)
`start sshfs -o create_umask=007,uid=-1,gid=-1,cache=yes,follow_symlinks,compression=no -o ssh_command="/bin/ssh.exe" XuserX@aaa.bbb.ccc.ddd:/dir1/dir2/dir3 Z:`
This exact same command work on two other machines (they have windows 7 pro though. The problematic one has a win7 home premium. If that could influence it at all)

> BTW, you do not need the .NET framework for WinFsp unless you have a .NET file system.
Ok!

**Comment by billziss-gh** [comment]
I am looking at the code [here](https://github.com/billziss-gh/winfsp/blob/master/src/dll/fuse/fuse.c#L347) and the only reason that you would get the message without an additional explanation is if you run out of memory (which of course sounds weird).

Do you have Visual Studio or other debugger on the machine that is failing? If yes, I could give you some pointers on how to debug this with SSHFS.

**Comment by OskarAtGitHub** [comment]
It shouldn't be running out of RAM during this test. Almost nothing else running.
Ok, but sounds like I might try a fresh windows install. It's had a long life with a large amount of programs installed. But still strange!

**Comment by billziss-gh** [comment]
Yes, the memory problem sounds very unlikely, especially because the amounts of memory allocated are miniscule. I suspect that I am misdiagnosing the actual reason, perhaps only debugging the code on your machine would give us the real answer.

**Comment by OskarAtGitHub** [comment]
Re-thinking this a little.
Is it possible that some anti-virus thing or other program is causing winfsp to crash/close before it outputs anything else?
Don't get any notifications though, so a anti-virus program might be unlikely.
This problem computer did come pre-installed with windows and some anti-virus things. So who knows.

**Comment by OskarAtGitHub** [comment]
Re-thinking this a little.
Is it possible that some anti-virus thing or other program is causing winfsp to crash/close before it outputs anything else?
Don't get any notifications though, so a anti-virus program might be unlikely.
This problem computer did come pre-installed with windows and some anti-virus things. So who knows.

**Comment by billziss-gh** [comment]
I doubt that it is the anti-virus because there are no file system interactions if no explanatory message is printed.

Basically the code allocates some memory and if that fails it prints the message you saw. Once it calls `FspFileSystemPreflight` then it does do some file system interactions, but it also prints an explanatory message on failure, which you did not see.

**Comment by mhogomchungu** [comment]
In SiriKali, i have seen that error message only when winfsp is not installed.
