### ISSUE TITLE
Asynchronous support for C#

### ISSUE THREAD

**Issue by dworkin** [billziss-gh/winfsp#230]
## Enhancement Request

WinFsp supports asynchronous I/O, but not for the C# version of the API.

Additionally, I wonder if asynchronous support could be extended to create/open/cleanup/close calls?

**Comment by billziss-gh** [comment]
For asynchronous support of the C# `Read`, `Write` and `ReadDirectory` operations what is needed is a C# version of [`FspFileSystemSendResponse `](https://github.com/billziss-gh/winfsp/blob/v1.5B1/inc/winfsp/winfsp.h#L1164-L1185).

The `Create`, `Open`, `Cleanup`, `Close` operations are more complicated.

The kernel/user mode protocol in [`FSP_FSCTL_TRANSACT_REQ`](https://github.com/billziss-gh/winfsp/blob/v1.5B1/inc/winfsp/fsctl.h#L262-L450) and [`FSP_FSCTL_TRANSACT_RSP`](https://github.com/billziss-gh/winfsp/blob/v1.5B1/inc/winfsp/fsctl.h#L451-L543) is fundamentally asynchronous and the [file system dispatcher loop](https://github.com/billziss-gh/winfsp/blob/v1.5B1/src/dll/fs.c#L512-L623) knows how to handle [`STATUS_PENDING`](https://github.com/billziss-gh/winfsp/blob/v1.5B1/src/dll/fs.c#L598-L599). At the native C level it is possible for a file system to replace the [`Create`/`Open`](https://github.com/billziss-gh/winfsp/blob/v1.5B1/src/dll/fsop.c#L890), [`Cleanup`](https://github.com/billziss-gh/winfsp/blob/v1.5B1/src/dll/fsop.c#L973) and [`Close`](https://github.com/billziss-gh/winfsp/blob/v1.5B1/src/dll/fsop.c#L990) handlers and handle those operations asynchronously. (A file system that did this would have to use [`FspFileSystemSetOperation`](https://github.com/billziss-gh/winfsp/blob/v1.5B1/inc/winfsp/winfsp.h#L1255) to replace handlers. It would likely also have to reconsider user mode locking and use [`FspFileSystemSetOperationGuard`](https://github.com/billziss-gh/winfsp/blob/v1.5B1/inc/winfsp/winfsp.h#L1226) to replace the default locking.)

The higher level API (`FSP_FILE_SYSTEM_INTERFACE`) hides the asynchronous capability for most operations. I will briefly discuss the reasons for `Create`/`Open`, `Cleanup` and `Close`.

- **`Create`/`Open`**: This is operation [`FspFsctlTransactCreateKind`](https://github.com/billziss-gh/winfsp/blob/v1.5B1/inc/winfsp/fsctl.h#L97). This operation has to perform access checks and other logic which makes it hard to make it asynchronous and have a sane API. In the current API it acquires a (user-mode) namespace lock exclusively, which further argues against making it asynchronous. Furthermore the Windows `CreateFile` and `NtCreateFile` API's are fundamentally synchronous so it felt natural to handle the WinFsp equivalent operation in a synchronous manner.

- **Cleanup**: This is operation [`FspFsctlTransactCleanupKind`](https://github.com/billziss-gh/winfsp/blob/v1.5B1/inc/winfsp/fsctl.h#L99). This was done synchronously, but could possibly be allowed to run asynchronously as well. Care should be taken in that the (user-mode) namespace lock is taken exclusively, when `FspCleanupDelete` is specified.

- **Close**: This is operation [`FspFsctlTransactCloseKind`](https://github.com/billziss-gh/winfsp/blob/v1.5B1/inc/winfsp/fsctl.h#L100). As with `Cleanup` this was done synchronously, but could possibly be allowed to run asynchronously as well. There are no lock implications for `Close`. It should be noted that the FSD already posts `Close` asynchronously and does not wait for it to complete before signaling to the OS that the file has been closed, so there is perhaps little need in making this operation asynchronous (other than freeing up a dispatcher thread as fast as possible).

**Comment by dworkin** [comment]
@billziss-gh Thanks for the feedback, it is very illuminating.

I will look at adding a C# version of `FspFileSystemSendResponse`.

**Comment by billziss-gh** [comment]
@dworkin thanks!

One of the challenges would be to port the `FSP_FSCTL_TRANSACT_RSP` structure, because it contains a large union.

Perhaps the easiest way would be to create methods `SendReadResponse`, `SendWriteResponse` and `SendReadDirectoryResponse` methods on `FileSystemHost`.

**Comment by bonagerivenkatesh** [comment]
Hi @billziss-gh ,

For my application I was trying to add support for async read and writes so was looking into the wrapper for the same to dot net.

For the initial testing purpose I tried adding only required properties from `FSP_FSCTL_TRANSACT_RSP`, but I am having some trouble in getting the `FspFileSystemGetOperationContext` itself before even reaching `FspFileSystemSendResponse`.

From `FspFileSystemGetOperationContext` I am getting all values as `0`. [This](https://github.com/bonagerivenkatesh/winfsp/commit/58b02366f31597c192307a8d3395581f94003c6c) is the branch on which I made changes, 

It would  be a great help if you could take a look at those changes and see if it is even the correct approach if so where did I made mistake. (This is my first attempt of making changes to an interop so there might be some mistakes)

Any help on this is really appreciated.

Regards,
Venkatesh Bonageri

**Comment by billziss-gh** [comment]
@bonagerivenkatesh I did not carefully review all your changes, but it seems to me that you are using `struct`'s as "reference` types rather than "value" types.

For example, in your definition of:

```
            internal delegate void FspFileSystemSendResponse(
	                IntPtr FileSystem,
	                FSP_FSCTL_TRANSACT_RSP Response);
```

The `Response` argument is a `struct` and is passed by value, which is not what you want. You want to use `Ref` to pass by reference.

**Comment by dworkin** [comment]
I am working on asynchronous I/O for dotnet in this [branch](https://github.com/dworkin/winfsp/tree/feature/async-dotnet).

**Comment by billziss-gh** [comment]
@dworkin I went over the changes in your branch and they look correct and complete to me. (I did not double-check struct sizes/offsets, constant values, etc.)

A nitpick is that your:

```
internal static unsafe UInt64 FspFileSystemGetOperationRequestHint()
{
    FspFileSystemOperationContext Context = FspFileSystemGetOperationContext();
    FspFsctlTransactReq Request = *Context.Request;
    return Request.Hint;
}
```

Could probably have been written as below to avoid a struct copy:

```
internal static unsafe UInt64 FspFileSystemGetOperationRequestHint()
{
    FspFileSystemOperationContext Context = FspFileSystemGetOperationContext();
    return Context.Request->Hint;
}
```

(Another nitpick is that I would have probably made `FspFileSystemGetOperationContext` return a pointer rather than a ref, but this is probably because I am a C guy -- I am not certain what a .NET guy does in this case. The way this is written results in a copy of `FspFileSystemOperationContext` being made.)

Another issue is that of testing that this works. Ideally we should have tests for every major functionality in WinFsp to ensure quality and catch regressions. The native MEMFS includes some code for [`SLOWIO`](https://github.com/billziss-gh/winfsp/blob/v1.5B1/tst/memfs/memfs.cpp#L57-L60) that could perhaps be adapted.

Overall this looks very good. Thank you!

**Comment by dworkin** [comment]
@billziss-gh I've updated the code to use pointers, as you suggested.

I have SLOWIO tests, which have to be cleaned up before I commit them. I will do so when I submit my pull request.  That will take a few more days, first I want to be sure that I have everything I need to let [KS2.Drive](https://github.com/UtrechtUniversity/YodaDrive) asynchronous I/O.

**Comment by billziss-gh** [comment]
@dworkin, fantastic. Thank you very much for the great work!

**Comment by bonagerivenkatesh** [comment]
@dworkin I tested my application with your changes it is working as expected. Thanks a lot.
The only thing I added for my app was a try catch block around `Api.FspFileSystemSendResponse(_FileSystemPtr, ref Response);` in FileSystemHost as sometimes `FspFileSystemSendResponse` was throwing exceptions. I added exception handling to it just like other functions in the class.

**Comment by dworkin** [comment]
@bonagerivenkatesh exception handling for calls to `FspFileSystemSendResponse` should not do much, since the called C code doesn't support exceptions?

The try-catch blocks in other functions wrap C# filesystem calls. If `FspFileSystemSendResponse` is somehow throwing exceptions, it would probably not be correct to catch them at this level.

**Comment by billziss-gh** [comment]
I agree with @dworkin. It makes no sense to see exceptions from `FspFileSystemSendResponse`. Unless I am missing something I do not believe that exception handling is needed at this place.

**Comment by dworkin** [comment]
I have asynchronous I/O working with KS2.Drive, and will open a pull request for WinFsp soon.

**Comment by dworkin** [comment]
https://github.com/billziss-gh/winfsp/pull/237

**Comment by dworkin** [comment]
This can be closed now that [pull request 237](https://github.com/billziss-gh/winfsp/pull/237) has been merged.
