### ISSUE TITLE
How Winfsp Supports Mobile Disk Mounting

### ISSUE THREAD

**Issue by zhetyzyb** [billziss-gh/winfsp#233]
If I want to map mobile disks, what should I do?

**Comment by billziss-gh** [comment]
I do not know what a mobile disk is and I am uncertain that this is the right place to have this discussion.

Can you describe in detail what you are trying to do? Keep in mind that WinFsp out of the box is not useful to end users; a developer must develop a file system with WinFsp that end users can use.

**Comment by zhetyzyb** [comment]
I use winfsp to mount disks, and I mount them on local disks. If I want to mount them on removable disks, what should I do?
Can it be set in FSP_FSCTL_VOLUME_PARAMS?

**Comment by zhetyzyb** [comment]
> I do not know what a mobile disk is and I am uncertain that this is the right place to have this discussion.
> 
> Can you describe in detail what you are trying to do? Keep in mind that WinFsp out of the box is not useful to end users; a developer must develop a file system with WinFsp that end users can use.

I use winfsp to mount disks, and I mount them on local disks. If I want to mount them on removable disks, what should I do?
Can it be set in FSP_FSCTL_VOLUME_PARAMS?

**Comment by billziss-gh** [comment]
Are you saying that the file system should appear as if running on top of a removable drive? This is not supported by WinFsp, because in general WinFsp is used to create file systems and not disks.

But I am struggling to see what scenario this would enable. What problem are you trying to solve?

**Comment by zhetyzyb** [comment]
I have a storage device that uses winfsp to mount on a local disk, but I want to set it up as a removable disk.

**Comment by billziss-gh** [comment]
@zhetyzyb understood.

Unfortunately WinFsp does not support presenting a file system as if being on top of a removable disk.

**Comment by billziss-gh** [comment]
Closing this as I believe the question has been answered. Please reopen if you think otherwise.
