### ISSUE TITLE
passthrough example to handle many file systems with the same code/process

### ISSUE THREAD

**Issue by Bob590** [billziss-gh/winfsp#235]
I would like to see a real example on how to handle multiple file systems using the same code.
I suggest to use the passthrough example.
In my case I also wish to use the FUSE implementation.
Thank you!

**Comment by billziss-gh** [comment]
@Bob590 

> I would like to see a real example on how to handle multiple file systems using the same code.

While I agree it would be nice to have examples file systems for more scenarios, I only have limited time. Since you seem to have this need perhaps you would consider creating such a file system and contributing it to the project?

**Comment by Bob590** [comment]
I'll see what I can do... but I don't promise anything because also my time is very limited. :-(

Anyway, from what I have learned so far, all you have to do in order to start multiple file system is to create a thread for each one that initialize argv[], argc and the file system data abd then call fuse_main. The thread is required because fuse_main() will not return until the program will quit (CTRL-C for example). Of course this can be ok for a quick test but if you want integrate this code inside a portable program then some extra work should be done. For example you need to add a way to communicate with each started thread in order to selectively quit one of them if you want to dismiss only one file system and not all of them.
This is what I have understood so far...

**Comment by billziss-gh** [comment]
> Anyway, from what I have learned so far, all you have to do in order to start multiple file systems is to create a thread for each one...

I think you are on the right track and your comments regarding starting `fuse_main` and controlling individual threads are spot on.

**Comment by Bob590** [comment]
I don't know how to stop a fuse thread.... other than forcibly terminate it. :-(
I think that in a multi file system environment a user wants to have full control over them. So the user wants for example  start a new file system but also stop an existing one.
What, in your experience, do you suggest to stop it without to quit the application?

**Comment by billziss-gh** [comment]
I think there are a few different solutions to your problem and the answer depends on what platforms you are targeting, what language/environment you are using, etc.

- The FUSE API provides `fuse_exit`. On WinFsp `fuse_exit` can be used to terminate the file system from any thread. Unfortunately this is not true of libfuse where you can only use `fuse_exit` to terminate the file system from inside a file system operation handler.
- One way around this might be to define a special `ioctl` that performs the `fuse_exit` from inside the `ioctl` handler. You would have to come up with a permission scheme to make sure that only authorized users can issue the `ioctl`.
- An alternative way (and one that I use in [cgofuse](https://github.com/billziss-gh/cgofuse)) is to write code that knows how to terminate a file system for all different platforms. See [here](https://github.com/billziss-gh/cgofuse/blob/master/fuse/host_cgo.go#L493-L527).

I cannot help but wonder about why you need multiple file systems in the same process. I have written numerous user mode file systems and I have never encountered such a need.

**Comment by Bob590** [comment]
Thank you for your clues.
I wish to write a Qt application that should compile and run mainly on Windows and Mac.
My application need to have two file systems: one based on a file image and one in RAM. These are used as storage: the first permanent and the second temporary.
I'll try to use fuse_exit in Windows and then find a viable solution for the Mac as you suggest.
If you wish I can port the passthrough example on Qt and build a double file system. This way you can have a Qt example as well... of course if I'll succeed in my intent.
Thank you very much again for your suggestions!

**Comment by Bob590** [comment]
I have made a quick test but I have found a problem... :-(
To call fuse_exit() I need a struct fuse_context * pointer in order to reach the fuse member that I have to pass to the function.
This pointer is only available after I have called the fuse_main().
I call fuse_main() from inside a thread that will get blocked inside it.
When I call fuse_get_context()  from another thread it doesn't return valid values and thus the fuse_exit cannot be called.
Any ideas on how to solve this puzzle?

**Comment by billziss-gh** [comment]
> I wish to write a Qt application that should compile and run mainly on Windows and Mac.

It probably make less sense to include a portable file system based on Qt in this project. But I will be happy to include a link to it from WinFsp when you are done.

> To call fuse_exit() I need a struct fuse_context * pointer in order to reach the fuse member that I have to pass to the function.

You can get the `struct fuse *` pointer that you need in `init`, which is guaranteed to be the first operation you get in your file system. The `fuse_main_real` function also accepts a `data` parameter which you can use to communicate data to `init`.

**Comment by Bob590** [comment]
I was just working on that. I have checked your code to understand how it works. I'm new to fuse and I have to learn. :-)
I have stored in my user data a pointer to the fuse_context inside the init callback.
So when I want to stop the file system I have that pointer and I can call fuse_exit with a correct pointer.
It works!
I can start and stop the file system any time now.

As I'm also new to Github... Can you tell me what are the steps to create this Qt repository so that you can link at it? I suppose I have to fork your project and then add a new folder where this Qt project will be stored. Right?
I'll mainly try to make the passthrough example run in Qt and show two file systems.
Thank you for your patience and great help!

**Comment by billziss-gh** [comment]
> As I'm also new to Github... Can you tell me what are the steps to create this Qt repository so that you can link at it? I suppose I have to fork your project and then add a new folder where this Qt project will be stored. Right?

Actually because this a Qt project, I do not think it should be included with WinFsp. I recommend that you simply create a new GitHub repo and do your work in there.
