### ISSUE TITLE
Mounting multiple drives simultaneously

### ISSUE THREAD

**Issue by jorisBarkema** [billziss-gh/winfsp#242]
## Question

Hello,

I am trying to mount two drives simultaneously using C#, and while the first one works when I try to mount the second drive I get an error. 

The code looks like this:
```C#
    public class FSPService : Service;
    {
        private FileSystemHost Host1, Host2;
        private DavFS davFs1, davFs2; // DavFS : FileSystemBase
        ...

        public FSPService() : base("KS2DriveService")
        {
        }

        public void Mount(Configuration config)
        {
            Configuration config2 = ... // create config2 here to test before I implement more
            davFs1 = new DavFS(config);
            davFs2 = new DavFs(config2);

            Host1 = new FileSystemHost(davFs1);
            davFs1.Init(Host1);
            if (Host1.MountEx($"{config.DriveLetter}:", 64, null, true, 0) < 0) throw new IOException("cannot mountfile system");

            Host2 = new FileSystemHost(davFs2);
            davFs2.Init(Host2);
            if (Host2.MountEx($"{config2.DriveLetter}:", 64, null, true, 0) < 0) throw new IOException("cannot mount file system 2");
        }

        ...
    }
```

What happens is the first drive mounts correctly, but for the second drive `Host2.MountEx` returns -2147024816 and the drive does not mount.

I have also tried creating multiple FSPService objects but if I read the FAQ right that's not the right way to do this.

edit: Forgot to mention: This is for Windows 10, using the WinFsp 2019.3 B2 release.

**Comment by jorisBarkema** [comment]
Forgot to mention: This is for Windows 10, using the WinFsp 2019.3 B2 release.

**Comment by billziss-gh** [comment]
As it was mentioned in the WinFsp mailing list the error code 0x80070050 stands for error ERROR_FILE_EXISTS. (This is the Win32 error 0x50 wrapped inside an NTSTATUS (or HRESULT) by prefixing it with the prefix 0x80070000.)
 
The most likely reason for this is that you are trying to mount to a drive or directory that already exists. What are the mount points that you are trying to mount on and do they exist at the time of mounting?
 
(BTW, you may want to step into MountEx in the debugger and see what call fails. It most likely fails when calling the native Api.FspFileSystemSetMountPointEx. It is also possible to setup mixed mode debugging and debug into this call as well.)

**Comment by jorisBarkema** [comment]
Hello and thank you for your answer, I found the problem literally five minutes ago:
I did use different mounting points but hadn't changed FileSystemBase.FileSystemName and FileSystemHost.Prefix. Changing that fixed the problem.

Thank you very much for the help.

**Comment by billziss-gh** [comment]
This makes sense. You do not need to change the `FileSystemName`, but yes, you do need a different `Prefix` when mounting multiple "network drive" file systems.
