### ISSUE TITLE
OCaml port (was: FUSE filesystem over Google Drive)

### ISSUE THREAD

**Issue by ale5000-git** [billziss-gh/winfsp#249]
## Question

Hi,
is WinFsp compatible with [FUSE filesystem over Google Drive](https://github.com/astrada/google-drive-ocamlfuse)?

**Comment by billziss-gh** [comment]
It does not look like it is currently compatible.

The author of the project (@astrada) has also written [ocamlfuse](https://github.com/astrada/ocamlfuse), which seems to be FUSE bindings for OCaml. Although I am not familiar with OCaml, I would be happy to help port the bindings to Windows/WinFsp if there was interest.
