### ISSUE TITLE
Add "UserContext2" parameter in FSP_FILE_SYSTEM_INTERFACE operations

### ISSUE THREAD

**Issue by hotlog** [billziss-gh/winfsp#25]
some usermode fs need two params: "usercontext" and "userconext2 params"
thanks.

**Comment by billziss-gh** [comment]
The `UserContext` is passed to all `FSP_FILE_SYSTEM_INTERFACE` operations as the `FileNode` parameter. Alternatively if one sets `UmFileNodeIsUserContext2` in `FSP_FSCTL_VOLUME_PARAMS` the `UserContext2` parameter is passed instead.

Do you have a file system that needs both `UserContext` and `UserContext2` passed at the same time?

**Comment by hotlog** [comment]
Yes,my encrypt  file system need both context, like kernel fsd driver (fcb and ccb).

**Comment by billziss-gh** [comment]
Understood.

I will look into introducing a new flag that instructs WinFsp to pass both `UserContext` and `UserContext2` through the `FileNode` parameter.

In the meantime you can work around this by using the new `FspFileSystemGetOperationContext` API, which gives direct access to the Request/Response. Unfortunately you will have to compile your own DLL to get this API as I have not made a binary release yet.

**Comment by billziss-gh** [comment]
Working on this now.

**Comment by billziss-gh** [comment]
Commit 3e3aa7651fe7befd74ca4395e21ae6d413adb90b resolves this.

The changes in this commit are as follows:

- The FileNode parameters in the `FSP_FILE_SYSTEM_INTERFACE` have been renamed to `FileContext`.
- The `FSP_FSCTL_VOLUME_PARAMS` struct has two flags that control the meaning of the `FileContext` parameters: `UmFileContextIsUserContext2` and `UmFileContextIsFullContext`.
- There is a new struct `FSP_FSCTL_TRANSACT_FULL_CONTEXT` with `UserContext` and `UserContext2` fields. The `FileContext` parameters become a pointer to this struct when the `UmFileContextIsFullContext` flag is set.

It would be helpful if you tried this and let me know if it works for you.

**Comment by billziss-gh** [comment]
This commit has been merged into master. Let me know if you find any problems with it, as my test suites do not (yet) test the `UmFileContextIsFullContext` option.
