### ISSUE TITLE
Remove "FUSE-" prefix from file system type name

### ISSUE THREAD

**Issue by johntyner** [billziss-gh/winfsp#250]
## Enhancement Request

When specifying a file system type via the FUSE interface, WinFSP prepends "FUSE-" to the front of the specified type. Was this a conscious decision to ensure that "FUSE" is displayed? This same limitation does not exist via the "native" WinFSP interface. I'd be happy to submit a patch to remove the prefix if there is no objection.

**Comment by billziss-gh** [comment]
This was done on purpose. My rationale was that I wanted FUSE file systems to be easily identified.

As FUSE file systems have improved substantially and are now in many ways on par with native file systems, this may have been the wrong decision.

**Comment by billziss-gh** [comment]
Closing this as the PR has now been accepted.
