### ISSUE TITLE
Application crashes when mounting Memfs as local disk - works OK mounted as network device

### ISSUE THREAD

**Issue by gshenai1** [billziss-gh/winfsp#255]
## Bug Report

My application crashes when trying to create directories/files when Memfs is mounted as localdisk, but works correctly when Memfs is mounted as network device
 i.e.
memfs-x64.exe -m Y:  --- causes application to crash 
memfs-x64.exe -u \memfs64\share2 -m Y: --- works OK

### How to Reproduce

I used a custom application

### Behaviors

I would expect that the basic operations work similar whether mounted as LocalDisk or network device. 

### Environment

- OS version and build: Windows 10 Enterprise LTSC
- WinFsp version and build: WinFsp 2019.1

**Comment by billziss-gh** [comment]
@gshenai1 I agree that your application should not crash when mounted as local disk.

Can you please let me know what operations your application attempts to perform when it crashes?

**Comment by gshenai1** [comment]
Hello Bill, thanks for your reply. I am trying to get more information from the application owners as to what is happening. Meanwhile, is there a way I can capture some logs that will throw more light on this. I started memfs with -d -1 and have some logs, but not sure how to understand it

**Comment by billziss-gh** [comment]
@gshenai1 is it possible to share those logs? If you cannot share them publicly, you can also email them directly to me: billziss at navimatics dot com.

**Comment by gshenai1** [comment]
@billziss-gh, sent the logs by mail. Thanks for your help

**Comment by billziss-gh** [comment]
Closing as this was discussed privately. Please reopen if you have additional information.
