### ISSUE TITLE
Where can I find the document of the release package?

### ISSUE THREAD

**Issue by landall** [billziss-gh/winfsp#260]
## Question

I find after I install the msi file in Win10, I do not know how to use it.
Maybe there need some short documents for the usage of the release package in the post-installation or in the README.MD of this project.

**Comment by billziss-gh** [comment]
The [wiki](https://github.com/billziss-gh/winfsp/wiki) includes documentation. The included [tutorial](https://github.com/billziss-gh/winfsp/wiki/WinFsp-Tutorial) should include most of the information you need.

**Comment by landall** [comment]
thanks, i will view the tutorial again carefully.
maybe because I am not a developer of windows driver or file systems, i can not understand part of the docs immediately. for example, the native winfsp api mapping to fuse api. in my option, i think it should be fuse api mapping to native winfsp when porting a fs to winfsp.

i am seeking a way to build a multi-volume file disk to save a large mount of cold files in Onedrive.
follow rclone's code, i find this wonderful project.

**Comment by billziss-gh** [comment]
The FUSE API layer does indeed use the WinFsp native API internally.

**Comment by billziss-gh** [comment]
You may also want to consult the samples found in the WinFsp installation. There are both native and FUSE API samples.

**Comment by landall** [comment]
and is there any execute file or document about how to deploy winfsp with my own file system?
I think i can package the installer within my installer without any further action?

**Comment by landall** [comment]
> You may also want to consult the samples found in the WinFsp installation. There are both native and FUSE API samples.

I am reading the code and examples. I know a little about Dokan and FUSE, so maybe i can help this project in some way.

**Comment by billziss-gh** [comment]
> I think i can package the installer within my installer without any further action?

It is possible to bundle the installer inside a larger installation package although I do not have any documentation showing how to to do it.

**Comment by landall** [comment]
> It is possible to bundle the installer inside a larger installation package although I do not have any documentation showing how to to do it.

If it is a normal action of windows installer, I think I can handle it well. Will it need a restart after installing/updating Winfsp? or it takes effect immediately?

**Comment by billziss-gh** [comment]
It does not require restart after first installation. But it does restart after uninstallation or upgrade if the driver has been used. This is because it is impossible to cleanly unload a file system driver.

**Comment by landall** [comment]
> It does not require restart after first installation. But it does require restart after uninstallation or upgrade if the driver has been used. This is because it is impossible to cleanly unload a file system driver.
Ok, i know what i should do. Thank u.
