### ISSUE TITLE
Stat reparse point mountpoint cause ERROR_UNRECOGNIZED_VOLUME

### ISSUE THREAD

**Issue by touilleMan** [billziss-gh/winfsp#262]
## Bug Report

It seems that mounting a reparse point (by opposition of mounting a drive) doesn't support stat operation on the mountpoint folder.

### How to Reproduce

With the memfs demo:
```shell
$ memfs-main.exe -m mnt  # done in another shell
$ python -c "import os; os.stat('mnt')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'mnt'
```

This work fine when mounting as drive letter
```shell
$ memfs-main.exe -m X: # done in another shell
$ python -c "import os; os.stat('X:')"
```

I've also tried with a C to make sure Python is not doing something weird:
```c
#include <stdio.h>
#include <unistd.h>
#include <errno.h>
#include <sys/stat.h>


int main(int argc, char const *argv[])
{
	if (argc != 2) {
		return 1;
	}
	struct stat statbuf;
	int ret = stat(argv[1], &statbuf);
	if (ret != 0) {
		printf("stat error %d, errno %d\n", ret, errno);
	} else {
		printf("stat ok, dev %ld, ino %ld\n", statbuf.st_dev, statbuf.st_ino);
	}
	return 0;
}
```

```shell
$ memfs-main.exe -m mnt  # done in another shell
$ gcc stat_mountpoint.c -o stat_mountpoint # in a lsw shell
$ ./stat_mountpoint mnt # still in the lsw shell
stat error -1, errno 5
```

I don't think this is an error from the memfs demo given I also have the same trouble with my own file system project (build on top of winfspy python bindings)

### Environment

- OS version and build: windows10 build 18362.476
- WinFsp version and build: 1.4.19049

**Comment by billziss-gh** [comment]
I am assuming that you are using Cygwin or a Cygwin based environment.

It is my understanding that some versions of Cygwin do not correctly recognize mount point reparse points ("junctions"). I believe there were some patches introduced for better handling of reparse points in later versions of Cygwin, but I am not sure if they made it to the mainline.

- Which version of Cygwin are you using?
- Does the C program work if you use `lstat` instead of `stat`?

**Comment by touilleMan** [comment]
Thanks for the fast answer !

All the `$ memfs-main.exe -m mnt`  are done in a cmd.exe shell, same thing for the test using python

The test with a C binary is done within Windows Subsystem for Linux (WSL, which I wrongly wrote `lsw` in the comments)

Using `lstat` instead of `stat` in the C program seems to work:
```shell
$ memfs-main.exe -m mnt  # done in another cmd.exe shell
$ gcc stat_mountpoint.c -o stat_mountpoint # in a WSL shell
$ ./stat_mountpoint mnt # still in the WSL shell
stat ok, dev 2, ino 1688849860313951
```

I've also made a test with `GetFileAttributesA` instead of `stat` to be able to run it on cmd.exe:
```c
#include <stdio.h>
#include <errno.h>
#include <windows.h>


int main(int argc, char const *argv[])
{
	if (argc != 2) {
		return 1;
	}
	DWORD ret = GetFileAttributesA(argv[1]);
	if (ret == INVALID_FILE_ATTRIBUTES) {
		printf("stat error %ld, errno %ld\n", ret, GetLastError());
	} else {
		printf("stat ok, ret %ld\n", ret);
	}
	return 0;
}
```

And it seems to work fine:
```shell
$ memfs-main.exe -m mnt  # done in a cmd.exe shell
$  cl.exe test_mountpoint.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26730 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

test_mountpoint.c
Microsoft (R) Incremental Linker Version 14.15.26730.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test_mountpoint.exe
test_mountpoint.obj
$ test_mountpoint.exe mnt # done in another cmd.exe shell
stat ok, ret 1040
```

I'll have a look at how the `os.stat` function is implemented in Python under windows

**Comment by touilleMan** [comment]
On Python the trouble is related to this issue https://bugs.python.org/issue37834
This issue is marked as resolved with Python >= 3.8, and indeed I don't have the strange behavior when test with python 3.8:
```
$ python37.exe -c "import os; print(os.stat('mnt'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'mnt'
 $ python38.exe -c "import os; print(os.stat('mnt'))"
os.stat_result(st_mode=16895, st_ino=1, st_dev=333988485, st_nlink=1, st_uid=0, st_gid=0, st_size=0, st_atime=1574416773, st_mtime=1574416773, st_ctime=1574416773)
```

The fix seems to call a second time `CreateFileW` with the `FILE_FLAG_OPEN_REPARSE_POINT` flag if the first time failed:
python37 version: https://github.com/python/cpython/blob/5c02a39a0b31a330e06b4d6f44835afb205dc7cc/Modules/posixmodule.c#L1643-L1675
python38 version: https://github.com/python/cpython/blob/fa919fdf2583bdfead1df00e842f24f30b2a34bf/Modules/posixmodule.c#L1712-L1724

I've made a second c program to mimic what is done in Python 3.8
```c
#include <stdio.h>
#include <errno.h>
#include <windows.h>


int main(int argc, char const *argv[])
{
    if (argc != 2) {
        return 1;
    }
    char const *path = argv[1];

    HANDLE hFile;
    DWORD access = FILE_READ_ATTRIBUTES;
    DWORD flags = FILE_FLAG_BACKUP_SEMANTICS; /* Allow opening directories. */
    flags |= FILE_FLAG_OPEN_REPARSE_POINT;

    hFile = CreateFileW(path, access, 0, NULL, OPEN_EXISTING, flags, NULL);
    if (hFile == INVALID_HANDLE_VALUE) {
        DWORD error = GetLastError();
        printf("error %ld\n", error);

        if (error == ERROR_CANT_ACCESS_FILE) {
            /* bpo37834: open unhandled reparse points if traverse fails. */
            hFile = CreateFileW(path, access, 0, NULL, OPEN_EXISTING,
                        flags | FILE_FLAG_OPEN_REPARSE_POINT, NULL);
            if (hFile == INVALID_HANDLE_VALUE) {
                printf("2nd error %ld\n", GetLastError());
                return -1;
            }
        }
    }
    BY_HANDLE_FILE_INFORMATION info;
    GetFileInformationByHandle(hFile, &info);
    printf("file attribute: %ld\n", info.dwFileAttributes);
    return 0;
}
```

And things work fine
```shell
$ test_mountpoint2.exe mnt
error 2
file attribute: 8392578
```

So there was definitly something buggy on the Python side. However this doesn't explain the issue using `stat` from a C program under WSL...

**Comment by billziss-gh** [comment]
Great. This looks mostly resolved.

> However this doesn't explain the issue using stat from a C program under WSL...

Can you try with latest WinFsp beta? The latest betas include explicit support for WSL1.

(I am assuming here that memfs-main.exe is the WinFsp memfs, which enables this support via the new `WslFeatures` flag in `VolumeParams`.

**Comment by touilleMan** [comment]
I've just tried with [version 1.5B4](https://github.com/billziss-gh/winfsp/releases/tag/v1.5B4), WSL works fine:
```shell
$ ./stat_mountpoint mnt
stat ok, dev 14, ino 222083756624710288
```

So I guess we can mark this as resolved 👍

**Comment by billziss-gh** [comment]
Excellent. Closing this.
