### ISSUE TITLE
Downloading an attachment in Mozilla Thunderbird silently fails

### ISSUE THREAD

**Issue by pfrejo** [billziss-gh/winfsp#263]
## Bug Report

Downloading an attachment from a received e-mail message fails silently.
No message error is displayed but the file is not found on the destination folder.

After some initial tests it seems that Thunderbird creates the file and then immediately
deletes it (don't know why).

### How to Reproduce

 - Install Mozilla Thunderbird ant setup an email account.
 - Download an email's attachment to a network drive created with WinFSP.

### Behaviors

The exported attachment is expected to be saved on the selected destination folder.

### Environment

- OS version and build: Windows 10 Home
- WinFsp version and build: WinFsp 2019.3 B4
- Mozilla Thunderbird version: v68.2.2

**Comment by billziss-gh** [comment]
- On which file system does this happen?
- Do you have any FileSpy or Process Monitor logs?

**Comment by pfrejo** [comment]
Sorry I forgot to mention the filesystem!
Currently using SSHFS-Win 3.5.19106

I could attach a PML (Procmon) file or generate a CSV...
Let me know the most convenient way to send it to you.

Thanks!

**Comment by billziss-gh** [comment]
Thanks.

This is more than likely an SSHFS-Win (or perhaps FUSE layer problem) rather than a WinFsp problem. In general I prefer to get bug reports for WinFsp on its reference file system MEMFS.

It would be helpful if you attached the Procmon report. Be sure to enable “Advanced Output” so we can see the actual IRP’s sent.

**Comment by pfrejo** [comment]
Here you can find attached the Proccess Monitor log.
[thunderbird.zip](https://github.com/billziss-gh/winfsp/files/3898520/thunderbird.zip)

**Comment by pfrejo** [comment]
I had a bit of time for testing this issue. It does work on MEMFS so it should be an issue
with SSHFS.

### Environment
- OS version and build: Windows 10 Home (10.0.18362.476)
- WinFsp version and build: WinFsp 2019.3 B4
 - Mozilla Thunderbird version: v68.2.2
