### ISSUE TITLE
Cannot verify the digital signature on Windows Server 2008

### ISSUE THREAD

**Issue by RadoslavCap** [billziss-gh/winfsp#264]
Looks like WinFsp has issues with driver signature on Windows Server 2008.

My setup
- Windows Server 2008 R2 64bit installed as virtual machine in Virtual Machine Manager (libvirt).
- Installed WinFsp from http://www.secfs.net/winfsp/
- even intro sample from non admin Command prompt (memfs-x64 -u \memfs64\share2 -m *) doesn't work. I'm getting 

`memfs-x64 -u \memfs64\share2 -m *
'memfs-x64' is not recognized as an internal or external command,
operable program or batch file.`

When I try from Administrator Command prompt:
`sc start winfsp`
I'm getting:
`sc start winfsp`
`[SC] StartService FAILED 577:`

`Windows cannot verify the digital signature for this file. A recent hardware or`
`software change might have installed a file that is signed incorrectly or damage`
`d, or that might be malicious software from an unknown source.`

I tried to disable driver signing in this way:
Start --->> Run ---> GPEdit.msc
Enable and Ignore Code signing for drivers policy under User Configuration --->>
Administrative Templates ---->> System ---->> Driver Installation --->> Code signing for drivers

I've tried reinstall WinFsp.

I've tried disable integrity checks:
`bcdedit /set loadoptions DISABLE_INTEGRITY_CHECKS`
and also in this way:
`bcdedit.exe /set nointegritychecks ON`     

I've tried to apply KB3033929 which solved this on Win7, but I'm getting message "it's not applicable" from Windows Updater (for this one https://www.microsoft.com/en-us/download/details.aspx?id=46083).

What else I can try or check?

**Comment by billziss-gh** [comment]
> I've tried to apply KB3033929 which solved this on Win7, but I'm getting message "it's not applicable" from Windows Updater (for this one https://www.microsoft.com/en-us/download/details.aspx?id=46083).
>
> What else I can try or check?

WinFsp is signed using SHA-256 signatures, which unfortunately are not recognized by older versions of Win 7 and Server 2008. Microsoft has issued a security update which adds support for SHA-256 to these older operating systems.

AFAIK you need to download the correct version of the security update. Unfortunately I just looked and it is no longer obvious which page contains the correct download. A good page with instructions is [here](https://docs.microsoft.com/en-us/security-updates/SecurityAdvisories/2015/3033929), but the links appear to be broken.

> even intro sample from non admin Command prompt (memfs-x64 -u \memfs64\share2 -m *) doesn't work. I'm getting
>```
>memfs-x64 -u \memfs64\share2 -m *
>'memfs-x64' is not recognized as an internal or external command, operable program or batch file.
>```

This particular problem appears to be that you did not execute the command from the proper path (usually `\Program Files (x86)\WinFsp\bin`).

**Comment by RadoslavCap** [comment]
> AFAIK you need to download the correct version of the security update
I haven't find proper patch but I have mentioned SP1 as prerequisity for patch. Windows update doesn't offer installation of SP1 but the solution for Windows Server is following:

1. Install Windows Server SP1 (KB976932) manually from https://www.microsoft.com/en-us/download/details.aspx?id=5842
2. Install code signing patch (KB3033929) https://www.microsoft.com/en-us/download/details.aspx?id=46083

These steps fix all mentioned issues.

@billziss-gh thank you!

**Comment by billziss-gh** [comment]
@RadoslavCap thank you for the detailed instructions on making this work.
