### ISSUE TITLE
Windows 10 map ssh directory

### ISSUE THREAD

**Issue by JonAnder83** [billziss-gh/winfsp#265]
I don't know if this is a bug or I'm mistaken here, but when I try to mount a ssh folder on windows 10 with the "map drive" menu, I'm unable to specify the remote mount point.

\\sshfs\someuser@10.32.0.1 --> Mounts ok
\\sshfs\someuser@10.32.0.1\some\existing\directory -->Mount error
\\sshfs\someuser@10.32.0.1:\some\existing\directory -->Mount error

What am I doing wrong? I have permissions for that dir.

- OS version and build: Windows 10 1909
- WinFsp version and build: 1.4.19016

**Comment by pfrejo** [comment]
- Check that you really have access to the directory. You can use any SFTP client
to connect to the remote host.

- Please note that the remote path is relative to your home directory:
UNC: "\\sshfs\someuser@10.32.0.1\some\existing\directory"
Actual remote path: /home/someuser/some/existing/directory

**Comment by JonAnder83** [comment]
That was the issue, then: I thought I could mount any directory on the disk by giving the full path.
Thank you!

**Comment by billziss-gh** [comment]
Closing this. Thank you @pfrejo for your help!
