### ISSUE TITLE
bug with path

### ISSUE THREAD

**Issue by martijintro** [billziss-gh/winfsp#266]
Your application has a problem on my win10 x64 computer that uses "sshfs-win" with a debian 9 ssh/sftp server:

When i connect in that way...

**\sshfs\REMUSER@HOST[\PATH] (= with a path at the end)**

...i does not work, e.g. \sshfs\root@x.x.x.x\var\log, i get an error message

When i connect with...

**\sshfs\REMUSER@HOST (=no path at the end), it mounts the remote user home dir (~), in my case with root user the linux server path /root...**

So how to bypass that issue, it's not useable if it's only able to mount user home dir /home/...) or admin home dir (/root)..?

The Winfsp version i use is: winfsp-1.5.19320 (it seems there is no "x64" installer?). And it don't think it's sshfs-win-bug: https://github.com/billziss-gh/sshfs-win/issues/134

**Comment by billziss-gh** [comment]
This is not a WinFsp issue. Closing.

**Comment by jmar83** [comment]
Yes, thx: https://github.com/billziss-gh/winfsp/issues/266
