### ISSUE TITLE
FspFileSystemResolveReparsePoints don't handle Junction (IO_REPARSE_TAG_MOUNT_POINT)

### ISSUE THREAD

**Issue by HKAnth** [billziss-gh/winfsp#269]
## Bug Report
The `FspFileSystemResolveReparsePoints` function don't handle Junction reparse point, also called Mount point. `IO_REPARSE_TAG_MOUNT_POINT` is not only used for drive mounting on directory but also for directory to directory redirection. A simple work around is to convert an `IO_REPARSE_TAG_MOUNT_POINT` in `IO_REPARSE_TAG_SYMLINK` into the `GetReparsePointByName` callback.

### How to Reproduce
Start memfs with default setting mount as drive and create a directory with sub-directory and/or an EXE file, then create a Junction (mklink /j link target) to the first directory on mounted drive. As result the EXE file can't start and exploring the sub-directory loop to the parent directory.

### Behaviors
Expected to work just as Symlink.

### Environment
OS version and build: WIN10-1909 x64
WinFsp version and build: 2019.B5

**Comment by billziss-gh** [comment]
@HKAnth thanks for the bug report and I apologize for the late response.

I can confirm that junctions do not work correctly when created on a MEMFS file system. Your workaround of returning a symlink instead of a junction in `GetReparsePointByName` should work, but we should probably fix this in `FspFileSystemResolveReparsePoints` (likely by having it be able to handle both symlinks and junctions).

Before we do this I need to confirm that the Windows kernel expects the same handling for both symlink and junctions. I am not sure that this is the case at this time.

**Comment by billziss-gh** [comment]
I am looking at this with the kernel debugger and it appears that the reparse point structures returned to the OS are correct and not corrupt. Nevertheless the OS is not able to compute the correct file name to open out of them.

This suggests that there is perhaps a misunderstanding on how these structures are supposed to be communicated to the OS. To aggravate this there is no documentation that I can currently find that shows how a file system driver is supposed to communicate these during

**Comment by billziss-gh** [comment]
From https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_reparse_data_buffer:

> `Reserved`
Length, in bytes, of the unparsed portion of the file name pointed to by the FileName member of the associated file object. For more information about the FileName member, see FILE_OBJECT<. This member is only valid for create operations when the I/O fails with STATUS_REPARSE. For all other purposes, such as setting or querying a reparse point for the reparse data, this member is treated as reserved.

It may be important to set `Reserved` correctly to indicate how much of the `FileName` has been parsed when returning a junction reparse point. Currently `FspFileSystemResolveReparsePoints` simply reports whatever `GetReparsePointByName` returns; I will attempt a fix where `Reserved` is set to the length of the unparsed portion of the `FileName`, as indicated above.

**Comment by billziss-gh** [comment]
Commit 52663ec676190475ae9e666828e7877312325f1b (currently in the private branch `pvt-junction`) likely fixes this problem.

**Comment by billziss-gh** [comment]
Closing this as the fix is now merged into master.
