### ISSUE TITLE
Fuse Java NIO Binding

### ISSUE THREAD

**Issue by josephsmendoza** [billziss-gh/winfsp#275]
## Enhancement Request

I don't know a thing about filesystems or C, but I wanted to get [overlayfs](https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt) functionality in Windows. I found javafs, which would allow me to make a filesystem at a level I do currently understand, but it doesn't support Windows and hasn't had any activity since 2018. I saw that at the end of #60 jnr-fuse got windows support, but I didn't read the whole thread because it's 3am and I'd rather post this request, for help/info on either [adding Windows support to javafs](https://github.com/puniverse/javafs/issues/15) or [adding Java NIO Filesystem support to jnr-fuse](https://github.com/SerCeMan/jnr-fuse/issues/91)

**Comment by billziss-gh** [comment]
WinFsp provides a native Windows API, a FUSE API and a .NET API. It is not likely that WinFsp will ever provide a Java API directly, although very capable Java libraries like jnr-fuse already exist.

I suggest you follow up with one of those projects.
