### ISSUE TITLE
winfsp error on rclone mount

### ISSUE THREAD

**Issue by yuritry** [billziss-gh/winfsp#276]
I am using winfsp with rclone mount on a win2008 kvm vps.  I installed the newest version of winfsp and rclone.  But when I was mounting a google drive, it doesn't work.

Error as following:

C:\Temp>rclone mount -vv --debug-fuse mysite:/ g: --allow-non-empty --allow-othe
r
2020/01/05 05:34:43 DEBUG : rclone: Version "v1.50.2" starting with parameters [
"rclone" "mount" "-vv" "--debug-fuse" "mysite:/" "g:" "--allow-non-empty" "--all
ow-other"]
2020/01/05 05:34:43 DEBUG : Using config file from "C:\Users\Administrator\.c
onfig\rclone\rclone.conf"
2020/01/05 05:34:43 DEBUG : Google drive root '': Mounting on "g:"
2020/01/05 05:34:44 DEBUG : Adding path "vfs/forget" to remote control registry
2020/01/05 05:34:44 DEBUG : Adding path "vfs/refresh" to remote control registry

2020/01/05 05:34:44 DEBUG : Adding path "vfs/poll-interval" to remote control re
gistry
2020/01/05 05:34:44 DEBUG : Google drive root '': Mounting with options: ["-o" "
fsname=mysite:" "-o" "subtype=rclone" "-o" "max_readahead=131072" "-o" "attr_tim
eout=1" "-o" "atomic_o_trunc" "-o" "debug" "-o" "uid=-1" "-o" "gid=-1" "--FileSy
stemName=rclone" "-o" "volname=mysite" "-o" "nonempty" "-o" "allow_other"]
Cannot create WinFsp-FUSE file system: unspecified error.
2020/01/05 05:34:44 ERROR : Google drive root '': Mount failed
2020/01/05 05:34:44 Fatal error: failed to mount FUSE fs: mount stopped before c
alling Init: mount failed

**Comment by yuritry** [comment]
Who could give me some help?
Thanks.

**Comment by billziss-gh** [comment]
Have you asked this question in the rclone GitHub and/or forums first?
