### ISSUE TITLE
Windows Defender is reporting Trojan:Win32/Detplock on v1.6.20027

### ISSUE THREAD

**Issue by pablocarreraest** [billziss-gh/winfsp#277]
<img width="515" alt="Screen Shot 2020-02-05 at 1 12 13 PM" src="https://user-images.githubusercontent.com/4999086/73869897-2166f800-4819-11ea-9632-c5cfd8a180c0.png">

Hey any ideas why is a trojan virus alert on windows defender.

**Comment by billziss-gh** [comment]
I have no idea. However recently I had another trojan report (#271) that ended up being a false positive.

Can you please let me know:

- Does this problem happen with the latest winfsp chocolatey package (1.6.20027)?
- Does it happen with a direct installation from the winfsp release page (https://github.com/billziss-gh/winfsp/releases/tag/v1.6)?
- Which version of Windows Defender exhibits this problem?

I note that VirusTotal reports the WinFsp 2020 installer as clean:

https://www.virustotal.com/gui/url/5a0541725ed59b97c9bb4270655479ccfa1c73ff10ce12a9cf1518d4f3f2a75c/detection

**Comment by garoto** [comment]
It's always a false positive.

**Comment by nodamnway** [comment]
https://github.com/billziss-gh/winfsp/releases/download/v1.6/winfsp-1.6.20027.msi


Actually VirusTotal shows different info for URL and File upload(downloaded from link above):
https://www.virustotal.com/gui/url/5a0541725ed59b97c9bb4270655479ccfa1c73ff10ce12a9cf1518d4f3f2a75c/details
https://www.virustotal.com/gui/file/7e13aadac2e4d1ac28501891c792cbf657b0c408e2694dd2b4fe5e02b302c5af/details

SHA-256 is the same for both links:	7e13aadac2e4d1ac28501891c792cbf657b0c408e2694dd2b4fe5e02b302c5af

**Comment by billziss-gh** [comment]
@nodamnway are you saying that if you download the file and submit to VirusTotal directly it detects a trojan, but if you simply link to it, it does not?

**Comment by billziss-gh** [comment]
I will contact Microsoft directly again. I suspect that they released another update on Windows Defender, which detects it as a false positive.

**Comment by nodamnway** [comment]
> @nodamnway are you saying that if you download the file and submit to VirusTotal directly it detects a trojan, but if you simply link to it, it does not?

Exactly.

**Comment by billziss-gh** [comment]
@nodamnway understood. As mentioned above in my **EDIT**: I think this means that at the time I submitted the link, no AntiVirus engines were detecting the file, whereas now some do.

----

I am running a Windows Defender check on my local Win10 with latest "threat definitions" installed and it does not detect anything.

![Cap1](https://user-images.githubusercontent.com/15330948/73889985-c25bb000-4825-11ea-8666-f557a6ea893e.PNG)
![Cap2](https://user-images.githubusercontent.com/15330948/73889998-c8ea2780-4825-11ea-8019-e943fd480e10.PNG)

**Comment by billziss-gh** [comment]
@pablocarreraest can you please let me know the "threat definition version" that you have? This is information requested by Microsoft's malware analysis site.

**Comment by billziss-gh** [comment]
Submitted to Microsoft:

![Cap1](https://user-images.githubusercontent.com/15330948/73891170-7eb67580-4828-11ea-9b8b-991ca905eb25.PNG)
![Cap2](https://user-images.githubusercontent.com/15330948/73891180-837b2980-4828-11ea-8953-a8142a29cea4.PNG)

**Comment by billziss-gh** [comment]
Microsoft has already responded! I am very impressed! 💯 

![Screen Shot 2020-02-05 at 3 18 45 PM](https://user-images.githubusercontent.com/15330948/73892175-069d7f00-482b-11ea-89a7-5bdadb659e7d.png)

Thank you, Microsoft!

**Comment by pablocarreraest** [comment]
<img width="229" alt="Screen Shot 2020-02-05 at 8 01 15 PM" src="https://user-images.githubusercontent.com/4999086/73896916-5e9bac00-4852-11ea-8aa1-9c6f259dae19.png">

wow you move very fast I'm with the latest version **winfsp-1.6.20027**

nice love your work is amazing!

Yeah, to solve I made an exception rule on window defender.

But now I will follow the steps Microsoft send you. 

Thanks. 🙂
              🙃

**Comment by billziss-gh** [comment]
@pablocarreraest thanks!

I don't know if Microsoft has updated their "threat definitions" yet. Last I checked they were still not updated. I would give it a day or so, before trying again.

**Comment by billziss-gh** [comment]
Please note that Windows Defender should no longer flag winfsp-1.6.20027.msi as containing malware.

<img width="835" alt="Screen Shot 2020-02-06 at 2 16 54 PM" src="https://user-images.githubusercontent.com/15330948/73983545-8b4fd200-48eb-11ea-90ae-d1ea2d824dad.png">

Closing this.
