### ISSUE TITLE
Malware detected Trojan:Win32/Azden.A!cl

### ISSUE THREAD

**Issue by jeremybusk** [billziss-gh/winfsp#278]
I'm getting this in chrome download on Windows 10 from Windows Security/Defender . Failed - Virus detected - Trojan:Win32/Azden.A!cl
I know it is related to this. https://github.com/billziss-gh/winfsp/issues/277
Maybe time to recheck with Windows security to allow it

**Comment by billziss-gh** [comment]
- Which exact version of WinFsp?
- Are you certain that you have the latest Windows Defender "threat definitions" installed?

This was originally reported in #271 and has been resolved.

**Comment by MrNiceforest** [comment]
Windows Defender is reporting this detection for the following file: 
winfsp-1.7.20038.msi->WinFsp.cab->launchctl_x86.exe

Running Win10 1809 with latest Windows Defender definitions v1.309.670.0 from 2020-02-10 03:37 (no timezone given)

**Comment by billziss-gh** [comment]
Sorry for the long delay to act on this, but I was traveling overseas. I can confirm that latest Windows Defender definitions report winfsp-1.7.20038.msi as having malware. I will report to Microsoft again as false positive.

**Comment by MrNiceforest** [comment]
It's detected by 13 other engines besides Microsoft on [VirusTotal](https://www.virustotal.com/gui/file/3c4b78dc93d3a0a5729dc6fb6dde5e3b622112c1bf64fd09c2809385e418e3f3/detection) in the meantime :/

**Comment by billziss-gh** [comment]
> Thank you, but it's detected by 13 other engines besides Microsoft on VirusTotal in the meantime :/

That's pretty bad. Hopefully MSFT will act on it soon like in previous times.

![Capture](https://user-images.githubusercontent.com/15330948/74610173-6a605b80-50f9-11ea-87e8-5c843e893946.PNG)

**Comment by billziss-gh** [comment]
The detections are also rather weird this time:

- On my local machine this is detected as `Trojan:Win32/Wacatac.C!ml`.
![Capture](https://user-images.githubusercontent.com/15330948/74610278-7567bb80-50fa-11ea-9e1e-c4cc40ead050.PNG)

- On the MSFT false positive submission portal it is identified as `Trojan:Win32/Detplock` by "Cloud" and Clean by "Client":

![CaptureOnline](https://user-images.githubusercontent.com/15330948/74610293-97613e00-50fa-11ea-8b57-526ac6ce85fa.PNG)

This is the third release that I have this happen in the space of a month and a half. I am therefore hoping to find a better solution from playing whac-a-mole after every false positive.

**Comment by billziss-gh** [comment]
Microsoft has removed the detection:

![Screen Shot 2020-02-16 at 9 17 01 PM](https://user-images.githubusercontent.com/15330948/74611163-1312b900-5102-11ea-88ab-93da18fbdd14.png)

I am closing but please reopen if the problem persists after a day or two.
