### ISSUE TITLE
Credential enter window: Default do not remember password 

### ISSUE THREAD

**Issue by gaotxg** [billziss-gh/winfsp#280]
If user want to remember password, click remember and this window won't appear again.
Do not remember password should be default option.
Modify here will probably resolve this issue:
src/dll/np.c     BOOL Save = TRUE;->    BOOL Save = FALSE;

**Comment by billziss-gh** [comment]
Apologies for the long delay.

While this would be an incompatible change, it is also a UI change and therefore reasonable. Would you consider submitting a PR for it?
