### ISSUE TITLE
How to combat AntiVirus false positives

### ISSUE THREAD

**Issue by billziss-gh** [billziss-gh/winfsp#282]
There has been a slew of AntiVirus reports recently: #271, #277, #278, #281.

Every time an AntiVirus product falsely flags the WinFsp software as containing malware, it negatively affects the user base of the software and erodes user trust in it. I think it could be argued that it is a form of defamation and that it harms the reputation of the software as well as my own.

The worst part about this is that I cannot be proactive and must be reactive about the problem. In all cases so far, VirusTotal gave the software a clean bill of health at the time of release, only for an AntiVirus product to flag the software as malware a few days after release. My only recourse at that point is to submit the software as a false positive when a user reports the problem.

To make matters worse some AntiVirus products seem to be wrappers of others or otherwise share malware information. The result is that once one product flags WinFsp as malware, others begin to flag it as well. It is practically impossible to follow up with all these AntiVirus vendors and have the software removed.

I am opening this issue to explore ways to address this problem.

**Comment by billziss-gh** [comment]
VirusTotal has a sevice called VirusTotal Monitor according to this blog post:

https://blog.virustotal.com/2018/06/vtmonitor-to-mitigate-false-positives.html

**Comment by billziss-gh** [comment]
I have began to work on the [AntiVirus Monitor](https://github.com/billziss-gh/avm) project:

> The goal of the AntiVirus Monitor project is to combat AntiVirus false positives. AntiVirus Monitor runs daily and scans a number of binaries using AntiVirus products. If an AntiVirus product reports a malware detection, then the detection is logged and the AntiVirus vendor can be contacted about a potential false positive.

**Comment by billziss-gh** [comment]
The [AntiVirus Monitor](https://github.com/billziss-gh/avm) project is now a [GitHub Action](https://github.com/features/actions).

I use it in a new [workflow](https://github.com/billziss-gh/winfsp/blob/master/.github/workflows/avm.yml) that I have added to WinFsp. The workflow runs every 6 hours and scans the WinFsp MSI releases. If a false positive is found a notification is posted to my GitHub dashboard.

**Comment by michel-zimmer** [comment]
Hi @billziss-gh, just wanted to let you know, that the links show up as negative in VirusTotal. But when I upload the actual binary, then they receive a few positive ratings.

**Comment by billziss-gh** [comment]
Can you let me know which binaries? Also do you have links?

**Comment by michel-zimmer** [comment]
![winfsp-virustotal-link-vs-file](https://user-images.githubusercontent.com/4385736/77260090-085dbd80-6c86-11ea-98a7-15c7488d4d20.png)

A: That link goes to
https://www.virustotal.com/gui/url/deb6974be8c69139330623124287086143f8423fef1a31600ed2502e8801604f/detection
and tests the link
https://github.com/billziss-gh/winfsp/releases/download/v1.7B1/winfsp-1.7.20038.msi
and everything is fine.

B: Is the download and when I upload it like here
https://www.virustotal.com/gui/file/3c4b78dc93d3a0a5729dc6fb6dde5e3b622112c1bf64fd09c2809385e418e3f3/detection
it tests the actual file with the hash
3c4b78dc93d3a0a5729dc6fb6dde5e3b622112c1bf64fd09c2809385e418e3f3
and there are false positives.

It appears as if it doesn't work to give VirusTotal the download link, and instead one has to give VirusTotal the file directly.

**Comment by billziss-gh** [comment]
I think what we are seeing here is the result of the following history:

- When I originally submitted the installer link to VirusTotal it correctly did not find any positives.

- At a later time Windows Defender found some false positives, which I reported to them and they fixed.

- Unfortunately some other Anti-Virus products picked up the Windows Defender false positives and they never fixed them. It is also possible that these false positives are unrelated, although they all appeared immediately after the Windows Defender false positive.

- So now when someone submits the file independently as an upload they get false positives from those services.

I suspect that this is happening because of a lot of AntiVirus vendors appear to simply wrap other vendors engines.
