### ISSUE TITLE
Webdav support

### ISSUE THREAD

**Issue by acosonic** [billziss-gh/winfsp#284]
Can you please support webdav protocol?

Since you rely on fuse, it shouldn't be too much trouble?

**Comment by billziss-gh** [comment]
It is unlikely that WinFsp would ever support directly the webdav protocol.

WinFsp can be used to expose webdav servers as file systems. However something like that would have to be a separate project and not included with WinFsp.

**Comment by acosonic** [comment]
https://github.com/miquels/webdavfs

**Comment by billziss-gh** [comment]
Thanks for the pointer.

You may want to consider adding an issue to that project to consider adding support for Windows via WinFsp. I will be happy to support their effort if they decide to do so.

**Comment by acosonic** [comment]
Thanks! I've created issue there :)
