### ISSUE TITLE
FUSE: Support multiple Windows domains

### ISSUE THREAD

**Issue by mohankumarv2005** [billziss-gh/winfsp#285]
User-A belonging to Active Directory Domain-A wants to use memfs in Computer which is registered with Domain-B. Upon start of memfs in “X:”, when User tries to access created folder, we get “Permission Denied” Error.

![image](https://user-images.githubusercontent.com/34312022/75128375-c9b9ff00-56e9-11ea-9d39-46afe7f56075.png)

**Comment by billziss-gh** [comment]
Mohan thank you for the report.

It is possible but non-trivial to add support for multiple domains to WinFsp-FUSE. The relevant code is in the native API’s FspPosixMapSidToUid and FspPosixMapUidToSid in the WinFsp source. Domains are supported in the following 2 code fragments:

https://github.com/billziss-gh/winfsp/blob/master/src/shared/ku/posix.c#L295-L336
https://github.com/billziss-gh/winfsp/blob/master/src/shared/ku/posix.c#L412-L440

**Comment by billziss-gh** [comment]
Mohan thank you for the report.

It is possible but non-trivial to add support for multiple domains to WinFsp-FUSE. The relevant code is in the native API’s FspPosixMapSidToUid and FspPosixMapUidToSid in the WinFsp source. Domains are supported in the following 2 code fragments:

https://github.com/billziss-gh/winfsp/blob/master/src/shared/ku/posix.c#L295-L336
https://github.com/billziss-gh/winfsp/blob/master/src/shared/ku/posix.c#L412-L440

**Comment by billziss-gh** [comment]
The fix for this has now been merged into master. Closing.
