### ISSUE TITLE
WinFsp + SSHFS-Win fails

### ISSUE THREAD

**Issue by emagii** [billziss-gh/winfsp#290]
## Bug Report

Have installed the WinFsp and SSHFS-Win (x64) on my x64 system.
Connecting using \\SSHFS\user@machine fails.

If I try a CMD window (administrative mode), I can ssh into the machine.
ssh.exe ulf@narsil 
works.

sshfs ulf@narsil
results in the error message:
cygfuse: initialization failed: winfsp-x64.dll not found

I can see that it is not happy about registry for HKLM\SOFTWARE\SSHFS-Win and 
HKLM\SYSTEM\CurrentControlSet\Services\WinFsp.Launcher\Services

I have tried installing the 32 bit version as well, and I get a little further since it
is no longer complaing about missing dll's, but sshfs still does not work.

=============
@echo off

setlocal

echo WINFSP AND SSHFS-WIN INSTALLATION DIRECTORIES
reg query HKLM\SOFTWARE\WinFsp /reg:32
REG QUERY HKLM\SOFTWARE\WOW6432Node\SSHFS-Win /f InstallDir /t REG_SZ /c /e
**echo reg query HKLM\SOFTWARE\SSHFS-Win /reg:32  FAILS**
echo.

echo WINFSP NETWORK PROVIDER DLL AND SSHFS REGISTRATIONS
reg query HKLM\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order
reg query HKLM\SYSTEM\CurrentControlSet\Services\WinFsp.Np\NetworkProvider
reg query HKLM\SYSTEM\CurrentControlSet\Services\EventLog\Application\WinFsp
**echo reg query HKLM\SYSTEM\CurrentControlSet\Services\WinFsp.Launcher\Services\sshfs FAILS**
echo.

echo WINFSP FSD CONFIGURATION AND STATUS
sc query WinFsp
sc qc WinFsp
sc sdshow WinFsp
echo.

echo WINFSP.LAUNCHER CONFIGURATION AND STATUS
sc query WinFsp.Launcher
sc qc WinFsp.Launcher
sc sdshow WinFsp.Launcher
echo.

echo OS INFORMATION
systeminfo
echo.
====================
WINFSP AND SSHFS-WIN INSTALLATION DIRECTORIES

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp
    InstallDir    REG_SZ    C:\Program Files (x86)\WinFsp\

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services
### reg query HKLM\SOFTWARE\SSHFS-Win /reg:32  FAILS

WINFSP NETWORK PROVIDER DLL AND SSHFS REGISTRATIONS

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order
    ProviderOrder    REG_SZ    WinFsp.Np,RDPNP,LanmanWorkstation,webclient,npnotes64,MfeEpePcNP,PnSson
    (Default)    REG_SZ

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinFsp.Np\NetworkProvider
    Name    REG_SZ    Windows File System Proxy
    ProviderPath    REG_SZ    C:\Program Files (x86)\WinFsp\bin\winfsp-x64.dll
    DeviceName    REG_SZ    \Device\WinFsp.Mup

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\WinFsp
    EventMessageFile    REG_SZ    C:\Program Files (x86)\WinFsp\bin\winfsp-x64.dll
    TypesSupported    REG_DWORD    0x7

### reg query HKLM\SYSTEM\CurrentControlSet\Services\WinFsp.Launcher\Services\sshfs FAILS

WINFSP FSD CONFIGURATION AND STATUS

SERVICE_NAME: WinFsp
        TYPE               : 2  FILE_SYSTEM_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: WinFsp
        TYPE               : 2  FILE_SYSTEM_DRIVER
        START_TYPE         : 3   DEMAND_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : \??\C:\Program Files (x86)\WinFsp\bin\winfsp-x64.sys
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : WinFsp
        DEPENDENCIES       :
        SERVICE_START_NAME :

D:(A;;LCRP;;;WD)(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)

WINFSP.LAUNCHER CONFIGURATION AND STATUS

SERVICE_NAME: WinFsp.Launcher
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: WinFsp.Launcher
        TYPE               : 10  WIN32_OWN_PROCESS
        START_TYPE         : 2   AUTO_START
        ERROR_CONTROL      : 0   IGNORE
        BINARY_PATH_NAME   : "C:\Program Files (x86)\WinFsp\bin\launcher-x64.exe"
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : WinFsp.Launcher
        DEPENDENCIES       :
        SERVICE_START_NAME : LocalSystem

D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)

OS INFORMATION

Host Name:                 BTIS1000044641
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Bombardier Transportation
Registered Organization:   Bombardier Transportation
Product ID:                00329-00000-00003-AA779
Original Install Date:     2019-03-29, 09:32:56
System Boot Time:          2020-03-10, 12:42:51
System Manufacturer:       Dell Inc.
System Model:              Latitude E6420
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 42 Stepping 7 GenuineIntel ~2701 Mhz
BIOS Version:              Dell Inc. A26, 2018-09-14
Windows Directory:         C:\windows
System Directory:          C:\windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             sv;Swedish
Input Locale:              sv;Swedish
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     16 265 MB
Available Physical Memory: 11 783 MB
Virtual Memory: Max Size:  18 697 MB
Virtual Memory: Available: 13 693 MB
Virtual Memory: In Use:    5 004 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    bt.bombardier.net
Logon Server:              \\IAA0541
Hotfix(s):                 11 Hotfix(s) Installed.
                           [01]: KB4053577
                           [02]: KB4088785
                           [03]: KB4485448
                           [04]: KB4500641
                           [05]: KB4509093
                           [06]: KB4512575
                           [07]: KB4516115
                           [08]: KB4521860
                           [09]: KB4523202
                           [10]: KB4537759
                           [11]: KB4537789
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) 82579LM Gigabit Network Connection
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.169.194.30
                                 IP address(es)
                                 [01]: 10.160.24.33
                           [02]: Intel(R) Centrino(R) Advanced-N 6205 Driver
                                 Connection Name: Wi-Fi
                                 Status:          Media disconnected
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
================================

### How to Reproduce

_Provide detailed information on how to reproduce the problem._

I installed earlier versions of the WinFsp and then SSHFS first. Deinstalled and rebooted.
Installed the versions below, and have not been able to get anything going.

C:\Program Files\SSHFS-Win\bin>sc query WinFsp

SERVICE_NAME: WinFsp
        TYPE               : 2  FILE_SYSTEM_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

C:\Program Files\SSHFS-Win\bin>net use \\memfs64\share
System error 67 has occurred.

The network name cannot be found.

### Behaviors

_Provide information on the expected and actual behaviors._

### Environment
- Microsoft Windows 10 Enterprise
- 10.0.16299 N/A Build 16299
- winfsp-1.6.20027
- sshfs-win-3.5.20024-x64.msi

**Comment by billziss-gh** [comment]
This looks to me like your registry is corrupted for some reason. Uninstall both SSHFS-Win and WinFsp and reinstall them and see if this fixes your problem.

**Comment by roman-sitewits** [comment]
Still happening on the latest version. Same message. The linux machines all instantly connected on boot, while windows fails as consistently.

**Comment by BioComSoftware** [comment]
Same problem here. Tried at both the command line and SSHFS-Win Manager


--------------------------------------------------------------------------------
date: 2021-04-23T12:58:23.891Z
conn: {4b165d02-f710-470b-b1e4-002b219f5114} (xnat)
conntype: key-file
cmd: "C:\Program Files\SSHFS-Win\bin\sshfs.exe" <user>@<server>:/home/ubuntu/data/xnat E: -p22 -ovolname=xnat -odebug -ologlevel=debug1 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oidmap=user -ouid=-1 -ogid=-1 -oumask=000 -ocreate_umask=000 -omax_readahead=1GB -oallow_other -olarge_read -okernel_cache -ofollow_symlinks -oPreferredAuthentications=publickey -oIdentityFile="C:/Users/right/Documents/.ssh/<privkey>"
{4b165d02-f710-470b-b1e4-002b219f5114} stderr: cygfuse: initialization failed: winfsp-x64.dll not found
{4b165d02-f710-470b-b1e4-002b219f5114} exit: 1

**Comment by mainguyenanhvu** [comment]
@BioComSoftware have you fix it successfully? Could you please share it with me?

Thank you so much.

**Comment by billziss-gh** [comment]
@BioComSoftware your problem appears to be that you do not have winfsp installed. Notice the message: `cygfuse: initialization failed: winfsp-x64.dll not found`. You will need this DLL that is installed when WinFsp is installed to use SSHFS-Win.

**Comment by mgarg1** [comment]
I had the same problem and installing winfsp fixed it right away.
So, make sure you have both(sshfs & winfsp) these softwares installed:

https://github.com/evsar3/sshfs-win-manager/release
https://github.com/billziss-gh/winfsp/releases

**Comment by gnalbandian** [comment]
Thanks @mgarg1.
Updating winfst to 2023 version solved my issues!

**Comment by huenguyen1988** [comment]
Install with guide after
https://drive.google.com/file/d/1ZkbHWBilydm_tO-nZyCVXJB73PMU4A6q/view?usp=sharing
