### ISSUE TITLE
Filter manager and WinFsp query

### ISSUE THREAD

**Issue by alfaunits** [billziss-gh/winfsp#296]
Hi, Bill,

   Is there anything a minifilter can use to distinguish that a volume is a WinFSP volume? We are looking for a way for our minifilter NOT to attach to WinFSP volumes. It appears that they show as regular local drives.

Dejan.

**Comment by billziss-gh** [comment]
Good question.

There is no foolproof way to detect WinFsp in all cases and I have been meaning to add one for a while.

If you are using local ("disk") drives only then you should be able to do it using `FltQueryVolumeInformationFile` with `FileFsDriverPathInformation` and see if WinFsp appears in the stack.

You might also be able to walk the Device Object stack yourself and see if the WinFsp driver appears in the stack although such tricks are probably frowned upon for filters :)

**Comment by billziss-gh** [comment]
Hey, @alfaunits. Did you ever come up with a solution for this? I am looking to add this functionality and it might be redundant if there is already a good method that works.

**Comment by alfaunits** [comment]
Heya, Bill.

   We simply ignored non MS File Systems :)
if((VolumeFilesystemType != FLT_FSTYPE_NTFS) &&
       (VolumeFilesystemType != FLT_FSTYPE_FAT) &&
       (VolumeFilesystemType != FLT_FSTYPE_EXFAT))
    {
return FLT_DO_NOT_ATTACH

**Comment by billziss-gh** [comment]
Thanks for the update.

I am not sure how `FltGetFileSystemType` determines the file system type, but I suspect that it issues an `IRP_MJ_QUERY_VOLUME_INFORMATION/FileFsAttributeInformation` and then assigns a type based on the returned file system name. Given that user mode file systems can set their own file system name (e.g. to "NTFS") this may not be foolproof.

I am looking into adding an alternative method that should work in all circumstances.

**Comment by billziss-gh** [comment]
Commit 2ffb8a1c97f6e6d39d3e34c86366e4859ac51656 should address this issue.
