### ISSUE TITLE
move virtio-win/winfsp to virtio-win/winfsp-old and move billziss-gh/winfsp to virtio-win/winfsp

### ISSUE THREAD

**Issue by Neustradamus** [billziss-gh/winfsp#297]
Can you move this repository to?
- https://github.com/virtio-win

Of course you must move the fork before to winfsp-old.
- https://help.github.com/articles/about-repository-transfers/

**Comment by billziss-gh** [comment]
I do not intend to change the project's location at this point.

However if anyone from the virtio-win project believes I can be of help, feel free to reach out.
