### ISSUE TITLE
Non-standart ssh port

### ISSUE THREAD

**Issue by pavelsr** [billziss-gh/winfsp#301]
## Enhancement Request

Hi, if I create network drive on `\\sshfs\username@host:port` uri ( with `:port`) seems like WinFSP can not parse such notation - `0x800704b3` Windows error code, that means network path is wrong

**Comment by billziss-gh** [comment]
This is not a WinFsp issue.

According to the SSHFS-Win [README](https://github.com/billziss-gh/sshfs-win#unc-syntax) you should be using `\\sshfs\username@host!port` (notice the exclamation mark).
