### ISSUE TITLE
memfs-fuse cannot be used as network device

### ISSUE THREAD

**Issue by davies** [billziss-gh/winfsp#305]
## Bug Report

We'd like to port a network file system to windows using FUSE API. It works as disk device, but not network device.

### How to Reproduce

Mount memfs from cgofuse

./memfs.exe X: -o VolumePrefix=\memfs\share

### Behaviors

Cannot create WinFsp-FUSE file system.
The service memfs has failed to start (Status=c000000d).

### Environment

- OS version and build: Windows service 2012 R2
- WinFsp version v1.6
- cgofuse : latest

**Comment by billziss-gh** [comment]
Use the syntax:

    ./memfs.exe X: -o VolumePrefix=/memfs/share

Or

    ./memfs.exe X: -o VolumePrefix=\\memfs\\share

The backslash is used as an escape character when used in FUSE options.

Please reopen if the problem persists.

**Comment by davies** [comment]
It works as you suggested, thanks. 

There is another issue that it can't be used with "net use X:  \\memfs\share" after I registered it using fsreg.bat, because '\\memfs\share' will be past to memfs.exe. It could be fixed by replacing it to "/memfs/share" in os.Args.

**Comment by billziss-gh** [comment]
You can use the `--VolumePrefix=%1` option, which accepts backslashes. Another trick is to to use `-oVolumePrefix=%\/_1` instead of `-oVolumePrefix=%1`. The special syntax `%\/_1` will convert all backslashes `\` to slashes `/`.

**Comment by davies** [comment]
@billziss-gh got it, thanks!
