### ISSUE TITLE
How to increase the read size in windows?

### ISSUE THREAD

**Issue by davies** [billziss-gh/winfsp#307]
## Question

We see lots of small read (4096 bytes) when scanning a big file, how to tell kernel to read with bigger buffer size?

**Comment by billziss-gh** [comment]
Where do these reads come from? From the kernel or from user mode applications?

If you enable kernel caching (`FileInfoTimeout==-1`) then reads will come primarily from the kernel as it will be caching data for you. If kernel caching is not enabled then reads will come directly from user mode applications and there is nothing you can do to change the buffers that they request.

**Comment by davies** [comment]
@billziss-gh we set FileInfoTimeout to 1, what's the behavior in this case? From debug logging, it seems that the read come from user mode application. Just like FUSE in Linux, we still have a chance to keep a read-ahead buffer (1MB should be enough) in WinFSP for sequential read.

Is this on the roadmap?

**Comment by billziss-gh** [comment]
If you set `FileInfoTimeout==1` you get file metadata caching for 1 millisecond and no data caching.

I recommend setting it to at least 1000 milliseconds (1 second).

If you do not enable data caching (i.e. `FileInfoTimeout==-1`, that is "minus one") then you will not get read-ahead from the kernel.

**Comment by davies** [comment]
@billziss-gh It seems that the size of read-ahead from kernel is 8KB, is there anyway we could increase it?

**Comment by billziss-gh** [comment]
I seem to recall that the kernel will issue larger read aheads than 8K.

There is a standing issue on what you are asking: #243
