### ISSUE TITLE
can not build winfsp

### ISSUE THREAD

**Issue by tracymacding** [billziss-gh/winfsp#309]
what does these mean?

C:\Users\Administrator\source\repos\winfsp-master\build\VStudio\tools\launcher.vcxproj : error  : 无法计算表达式“[System.IO.File]::ReadAllText(/.git/HEAD)”。未能找到路径“C:\.git\HEAD”的一部分。  C:\Users\Administrator\source\repos\winfsp-master\build\VStudio\version.properties

**Comment by billziss-gh** [comment]
For me to explain the error message, it would have to be in a language that I understand.

In any case the build process assumes that you are building WinFsp in a git repository and will likely fail if you do not (I have not tried it).
