### ISSUE TITLE
SignTool Error: No certificates were found that met all the given criteria.

### ISSUE THREAD

**Issue by tracymacding** [billziss-gh/winfsp#310]
i got error like when run build.bat

SignTool Error: No certificates were found that met all the given criteria.

how to solve this?

**Comment by billziss-gh** [comment]
Windows drivers need to be signed in order to run in a production Windows system. However you can run unsigned drivers in a Windows system with test signing enabled.

See these notes:

https://github.com/billziss-gh/winfsp#building-and-running
