### ISSUE TITLE
Does WinFsp support silent installation 

### ISSUE THREAD

**Issue by hemantaltair** [billziss-gh/winfsp#313]
## Question

Does WinFsp support silent installation ?

**Comment by hemantaltair** [comment]
I am trying to automate using salt, if so what is the silent installation option?

**Comment by billziss-gh** [comment]
In general all MSI can be installed silently.

For example:

    msiexec /i winfsp-x.x.x.msi /qn INSTALLLEVEL=1000

This will install all components silently. Omit the `INSTALLLEVEL` to only install core components.
