### ISSUE TITLE
Slow behavior with concurrency

### ISSUE THREAD

**Issue by rubarax** [billziss-gh/winfsp#315]
## Question

Hi, 

I am trying the driver (dotnet wrapper) to implement some a service that is able to download files on demand (it's more complex than that but enough info for the question :).

The service downloads the files from a remote place in the Open method , so it slows down the Open operation when the file is not locally cached. This is totally expected, no problem.

This way, If I run a build from scratch that uses that files, it needs to download all the files from the server. This is slow, as expected, No problem.

**The problem comes when I try to open some other files/directories (that are already downloaded, they should be fast) while the build is running and downloading files on demand. The performance is awful, it's very slow to open them or list them although they are local and there is nothing else to process. So, it seems I hit some kind of bottleneck or throttle.**

Is there any limit of concurrent operations working against the file system?

I decided to try the `mHost.MountEx(mountPoint, 16, null, true, 0);` method to increase the number of available threads (after I took a look to the FspFileSystemDispatcherThreadCount values) but it didn't improve the performance.

Thanks,
   Rubén.

**Comment by rubarax** [comment]
I think I saw the problem: tThe code I used had the Synchronized field to true `mHost.MountEx(mountPoint, 16, null, **true**, 0);`

I set it to false and now it works like a charm: `mHost.MountEx(mountPoint, 16, null, **false**, 0);`

Just a last question, could you tell me the advantages of  set it to true so _file system operations are synchronized using an exclusive lock._ ?

**Comment by billziss-gh** [comment]
> Just a last question, could you tell me the advantages of set it to true so file system operations are synchronized using an exclusive lock. ?

The advantage of an exclusive lock is that a simple file system that does not care about performance does not need to protect its data structures from concurrent accesses.

Closing this, but please reopen if you find that this problem has not been solved.
