### ISSUE TITLE
How to mount a network share as local drive?

### ISSUE THREAD

**Issue by DocMAX** [billziss-gh/winfsp#317]
How do i mount a network share as local drive?

**Comment by billziss-gh** [comment]
I am not certain how this question is related to WinFsp. Please elaborate.

Also please consider asking questions in the [WinFsp group](https://groups.google.com/forum/#!forum/winfsp). GitHub issues should primarily be used for bug reports and enhancement requests.

**Comment by DocMAX** [comment]
For example i want \\server\myshare as X: (where X: is recognized by windows as a LOCAL drive)

**Comment by billziss-gh** [comment]
Are you using WinFsp for this?

**Comment by DocMAX** [comment]
From what i understand is, that WinFsp could do this.

**Comment by billziss-gh** [comment]
WinFsp is a software library that other developers can use to create a "file system". A "file system" is like a new "drive" for your computer.

I do not believe your question is related to WinFsp, so I will close it.

You likely need to read up on the [`net use`](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/gg651155(v=ws.11)) command for what you want to do.

**Comment by DocMAX** [comment]
net use creates a network drive. what i want is a (virtual) physical drive.
