### ISSUE TITLE
Request: Add possibilty to mount a volume as readonly using FUSE/ro-flag

### ISSUE THREAD

**Issue by JaniruTEC** [billziss-gh/winfsp#319]
At the moment there is neither a documented way to mount a FUSE-Filesystem as readonly nor could I find any matching flags in the sourcecode.
The Cryptomator-Project usually allows for filesystem to be RO. In each case but FUSE over WinFSP this is achieved using RO-Flags that are handed to the Filesystemprovider-API. At the moment we have work around this by not setting the GID/UIDs on mount, which seems a bit hacky. Therefore adding support for RO-Filesystems would be highly useful for this (and probably many other) projects.

**Comment by billziss-gh** [comment]
Duplicate of #84.

**Comment by JaniruTEC** [comment]
Thanks! I didn't find it, but I tried, I swear 😓 

Closing as duplicate.
