### ISSUE TITLE
Refreshing folder

### ISSUE THREAD

**Issue by 837951602** [billziss-gh/winfsp#327]
Given knowledge that the folder is changed, can I tell winfsp to refresh the folder? (API only provides FspFileSystemAddDirInfo when requesting folder)

P.S. Why can't I post on google forum?

**Comment by billziss-gh** [comment]
WinFsp recently gained functionality that allows a user mode file system to notify Windows that files have changed. This functionality is currently in the pvt-notify branch, although I should be merging into master soon. It will be a few weeks before this new feature makes it into a public beta release.

https://github.com/billziss-gh/winfsp/blob/pvt-notify/inc/winfsp/winfsp.h#L1189-L1254
