### ISSUE TITLE
please help me show how i can resolve my problem when i install winfsp 

### ISSUE THREAD

**Issue by baoson202** [billziss-gh/winfsp#329]
Hi every one !
I have a trouble when i install winfsp via choco . Please help me to solve this trouble . thank you !

please show me the name of the service for me stop it thank !
![image](https://user-images.githubusercontent.com/11453117/97679241-9bd25900-1ac7-11eb-86f8-6e3771d52772.png)

ps: i have restart my computer many time. But i can't solve the trouble .

**Comment by billziss-gh** [comment]
Are you perhaps running some software that is already using WinFsp?
