### ISSUE TITLE
Distributing WinFSP as a part of an already existing installer

### ISSUE THREAD

**Issue by SergioLuis** [billziss-gh/winfsp#332]
## Question

We developed a new feature that relies on WinFSP to work. In the near future, once we get the proper license to distribute WinFSP, we would want to distribute it as a part of our own installer. This way, customers can start using the new feature right away, do not have to look for a new installer, and we don't need to make sure WinFSP is installed to enable the feature.

Is there a preferred way to do the distribution? Can the WinFSP installer be embedded as a resource, and be executed in an unattended way, or do we need to get the binaries and replicate in our own installer the same actions the WinFSP installer performs?

**Comment by billziss-gh** [comment]
The WinFsp MSI can be installed silently.

For example:

```
msiexec /i winfsp-x.x.x.msi /qn INSTALLLEVEL=1000
```

This will install all components. Omit the INSTALLLEVEL to install only core components.
