### ISSUE TITLE
Does not work anymore after windows update

### ISSUE THREAD

**Issue by jayjupdhig** [billziss-gh/winfsp#346]
sshfs version: 3.5.20024
winfsp version: 1.7.20172
windows version: 10 Pro x64 with most current updates on 15-01-2021

Problem:

![111](https://user-images.githubusercontent.com/42765391/104747996-7d3c3f80-5751-11eb-82db-a4e3bd49d13f.jpg)

Is that a winfsp or a sshfs issue after the windows update from today?

How to solve? Is there a new version with the necessary compatibility or do i need to wait for it?

Thank you very much for your feedbacks! :-)

**Comment by billziss-gh** [comment]
Updating Windows does not (should not) break a WinFsp or SSHFS-Win installation.

I am unclear on why you may be getting this error message.

**Comment by jayjupdhig** [comment]
OK thx, i also submitted that:
https://github.com/billziss-gh/sshfs-win/issues/269

**Comment by jayjupdhig** [comment]
Now i use the most current stable versions of BOTH parts (sshfs-win AND WinFSP) and it seems to work again! :-)

So problem solved - thank you anyway.
