### ISSUE TITLE
WinFsp 1.8 won't install after uninstalling previous version and rebooting

### ISSUE THREAD

**Issue by divo1** [billziss-gh/winfsp#348]
## Bug Report
Uninstalled previous WinFsp (don't remember what version). Rebooted. Tried to install 1.8. It gives following error message: "The WinFsp service appears to be running. If you just uninstalled WinFsp please restart your computer. If you are running a development version of WinFsp please remove it before proceeding."

Rebooting several times gives same error.

### How to Reproduce
Uninstall WinFsp. Reboot. Install WinFsp (winfsp-1.6.20027.msi).

### Behaviors
Installs.

_Provide information on the expected and actual behaviors._

### Environment

- OS version and build: 10.0.18363
- WinFsp release version: winfsp-1.8.20304.msi

**Comment by billziss-gh** [comment]
Can you please run the following commands from a command prompt:

```
sc.exe query winfsp
sc.exe qc winfsp
```

**Comment by billziss-gh** [comment]
@divo1 were you able to run the above mentioned commands? I find it likely that someone has released a version of WinFsp that conflicts with the binaries as I release them here. Thanks.

**Comment by divo1** [comment]
@billziss-gh  Hey :) Sorry for delay. I restart few times computer, uninstall winfsp and do many different stuff :) 
Here is output from commands:
```
SERVICE_NAME: winfsp
        TYPE               : 2  FILE_SYSTEM_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1077  (0x435)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
PS C:\Users\divo> sc.exe qc winfsp
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: winfsp
        TYPE               : 2  FILE_SYSTEM_DRIVER
        START_TYPE         : 3   DEMAND_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : \??\C:\Program Files (x86)\WinFsp\bin\winfsp-x64.sys
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : WinFsp
        DEPENDENCIES       :
        SERVICE_START_NAME :
```

But now everything works fine :) Thanks for help :)
