### ISSUE TITLE
Unable to mount memfs on an absolute directory path

### ISSUE THREAD

**Issue by efeat** [billziss-gh/winfsp#35]
Dear Bill,

I've installed winfsp-1.0.17009.msi on windows 7.
First thanks for that good job !

On that version it's impossible to mount memfs on an absolute path, i.e
- memfs -m Y: => OK
- memfs -m test-winfsp => OK
- memfs -m C:\test-winfsp => KO

I've looked into the winfsp-1.0RC1 source code and found the bug: library.h line 76
L':' == FileName[1] **||** L'\0' == FileName[2];
should be
L':' == FileName[1] **&&** L'\0' == FileName[2];

In my example, C:\test-winfsp is reconized as a drive letter and winfsp returns an invalid handle error.

Best Regards

**Comment by billziss-gh** [comment]
Thank you for the excellent bug report and the correct resolution :)

This problem was fixed a few days after RC1 release in commit b65322c2ace2ee26259915f0862bf582f96372a3. The fix should be in RC2 hopefully out some time next week.
