### ISSUE TITLE
Originating process ID for Read/Write/Close

### ISSUE THREAD

**Issue by paratype-fonts** [billziss-gh/winfsp#350]
Based on https://github.com/billziss-gh/winfsp/issues/53, file system caching makes getting the process ID for read operations not that useful. With that, it seems that disabling caching would make obtaining the process ID quite meaningful.

If my interpretation is correct, could FileSystemBase.GetOperationProcessId and FspFileSystemOperationProcessId return the originating process ID for read, write and close operations when the file system caching is disabled?

In some usage scenarios knowing IDs of processes that are trying to read is critically important for the purpose of data protection.

**Comment by billziss-gh** [comment]
From my answer [here](https://groups.google.com/g/winfsp/c/n62EzqXA9jw/m/gi4KL4TIBAAJ):

> Every user mode file system request originates as an IRP (I/O Request Packet) that arrives to the WinFsp FSD (File System Driver). Every IRP can have an associated process ID that can be found using the DDI IoGetRequestorProcessId [1].
>
> In my experimentation (and I do not recall all the details) I found that the only times where this process ID is guaranteed to be valid is during operations where Windows needs to perform access control (i.e. Create and Open requests). At other times the process ID may or may not be valid.
>
> For example, for Read/Write operations applications will issue NtReadFile/NtWriteFile, which I believe correctly sets up the IRP's so that the originating process can be identified. However Read/Write operations may also be initiated by memory mapped operations (e.g. page faults) from inside the kernel, where I am fairly certain that the information about the originating process would not be propagated.
>
> (There is also the practical problem that the WinFsp kernel protocol (i.e. the DeviceIoControl protocol spoken between the FSD and user mode file systems) does not currently allow passing the originating process ID.)
>
> [1] https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-iogetrequestorprocessid

**Comment by paratype-fonts** [comment]
Firstly, thanks for the detailed explanation!

Secondly, understanding all the special cases described above, I still tried to come up with a "workaround." Allow me to share it. 

The Open method  in the memfs.cs sample has FileNode0 out parameter of type Object:

    public override Int32 Open(String FileName, UInt32 CreateOptions, UInt32 GrantedAccess,
        out Object FileNode0, out Object FileDesc, out FileInfo FileInfo, out String NormalizedName)  {

Instead of assigning FileNode0 the FileNode that corresponds to the given FileName, I return a composite object which has both FielNode and processId:

    var processId = GetOperationProcessId();
    FileNode0 = new FileNodeEx() { FileNode = FileNode, ProcessId = processId };

I assumed that the Read method gets the same FileNode0 as the one created during Open. So, I cast FileNode0 to the object created in Open: 

    public override Int32 Read(Object FileNode0,  Object FileDesc, IntPtr Buffer,
        UInt64 Offset,  UInt32 Length, out UInt32 BytesTransferred)
    {
        FileNode FileNode = ((FileNodeEx)FileNode0).FileNode;
        int processId = ((FileNodeEx)FileNode0).ProcessId;

So far, this trick works well for me. 

The same approach is not working with the C variant. I noticed that Read not always gets a similar composite object from the corresponding Open. Sometimes, Read gets the FileNode/processId object from Open/Close operations that happened before the most recent Open. Not sure what explains the different behavior in C# and C code. Is it something fixable?

**Comment by billziss-gh** [comment]
@paratype-fonts sorry for the late response. I intended to respond to this, but I neglected to do so.

The `FileNode` is used to uniquely identify an open file. Opening the same file name should always yield the same `FileNode` value for as long as the file with that name remains open anywhere in the system.

The `FileDesc` is used to identify an open instance of a file. Opening the same file name may yield a different `FileDesc`.

Given this I recommend that you track the process ID in the `FileDesc` rather than the `FileNode`. Otherwise the following is possible:

- Process A opens `\FILE`. Your file system returns a `FileNode` that is a pointer to your internal file node and the process id of A (`pidA`).
- Process B opens `\FILE`. Your file system should return the same `FileNode` as before. But this `FileNode` contains `pidA`, which is the "wrong" PID.

**Comment by billziss-gh** [comment]
@paratype-fonts does this discussion resolve this issue? If yes, we can close this.

**Comment by paratype-fonts** [comment]
@billziss-gh Firstly, thanks for your attention to the request! Secondly, I regret not describing my project in full. Actually, we are using the C# version of memfs for prototyping, but the final product is written in C. The Open and Read interfaces in C do not have a parameter corresponding to FileDesc:

    static NTSTATUS Open(FSP_FILE_SYSTEM* FileSystem, PWSTR FileName, UINT32 CreateOptions, UINT32 GrantedAccess,
        PVOID* PFileNode, FSP_FSCTL_FILE_INFO* FileInfo)

Am I missing something? Is there anything in the C version equivalent to FileDesc?

Thanks!

**Comment by billziss-gh** [comment]
@paratype-fonts yes, of course.

The actual prototype of the C `Open` operation is:

```C
NTSTATUS (*Open)(FSP_FILE_SYSTEM *FileSystem,
        PWSTR FileName, UINT32 CreateOptions, UINT32 GrantedAccess,
        PVOID *PFileContext, FSP_FSCTL_FILE_INFO *FileInfo);
```

The `PFileContext` parameter can be either `FileNode` or `FileDesc` or a "full context" (a `struct` containing both the `FileNode` and `FileDesc`). Please read the full details here:

https://github.com/billziss-gh/winfsp/blob/v1.8/inc/winfsp/winfsp.h#L165-L189

If your file system is based on MEMFS, but you also want to track PID's in the `FileDesc` you probably want to use `UmFileContextIsFullContext`.

**Comment by billziss-gh** [comment]
Closing this as I believe it is resolved. Please reopen if you think otherwise.
