### ISSUE TITLE
passthrough-fuse - Access denied on update of files (Windows 10)

### ISSUE THREAD

**Issue by laxnak** [billziss-gh/winfsp#354]
[Windows 10]

Example:  tst\passthrough-fuse

Changing the contents of the files does not work, gives an error **access denied**. Deleting or creating files works as expected.

![Zwischenablage01](https://user-images.githubusercontent.com/74144662/110662681-0443ec00-81c6-11eb-853f-68b0267ce7df.png)

**Comment by billziss-gh** [comment]
You should be able to get around such problems by starting passthrough-fuse with the option `-ouid=-1` and/or `-oumask=000`.

**Comment by laxnak** [comment]
Thank you, that helped. But, why not make it hardcoded in example? It would help people like me to see immediately what the cause is and not lose 3 days looking for a black cat in a dark room. Files can be created, but can't be changed immediatelly it after that and it's really confusing.

**Comment by billziss-gh** [comment]
> But, why not make it hardcoded in example?

There are a few different ways that passthrough-fuse can be used and not all of them work correctly with the `-ouid=-1` approach. For example, if you use passthrough-fuse via the Launcher, then it would run in the LocalSystem context and the `-ouid=-1` would give the wrong permissions.

**Comment by billziss-gh** [comment]
I am closing this, but please reopen if you find that the problem has not been addressed.
