### ISSUE TITLE
Microsoft SQL fails to create Backup inside Directory

### ISSUE THREAD

**Issue by Jammycrocodile** [billziss-gh/winfsp#359]
## Bug Report

Microsoft SQL is unable to create a database file, or a backup file inside a directory on a winfsp filesystem. The Issue is something similar to this Issue: https://github.com/billziss-gh/winfsp/issues/240

The latest version of Microsoft SQL, which is MSSQL 2019 CU19 (15.0.4102.2)  is able to create a sql file or a database backup inside a directory. 
MSSQL 2019 RTM (15.0.2000.5) or versions prior to to this, i.e. MSSQL 2017, 2016 etc. are unable to create a sql file inside a folder on winfsp. With every version of MSSQL a backup or database file can be created on the root of the filesystem.

The error is:

```
2021-03-30 10:29:57.66 Backup      BackupIoRequest::ReportIoError: write failure on backup device 'S:\test\test.bak'. Operating system error 87(The parameter is incorrect.).
2021-03-30 10:29:57.66 Backup      Error: 3041, Severity: 16, State: 1.
2021-03-30 10:29:57.66 Backup      BACKUP failed to complete the command BACKUP DATABASE TEST. Check the backup application log for detailed messages.
```

I mounted a AWS Bucket with Rclone, which uses Winfsp to emulate the filesystem. [https://rclone.org/commands/rclone_mount/](https://rclone.org/commands/rclone_mount/)

### How to Reproduce

1. I tested this with the MSSQL standard version, which needs a licence. I guess the problem can also be repdoduced with the free Express version: (https://www.microsoft.com/en-us/sql-server/sql-server-downloads). You may also need a client like sqlcmd, or Management Studio to connect to the db (from https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-2017).
2. Install Rclone and mount S3 Storage: https://rclone.org/downloads/
3. Create a folder in AWS S3 
4. Create a Backup with SQL inside the folder

### Behaviors

SQL is able to create a backup, or database file inside a folder on a winfsp filesystem. 

### Environment

- OS version and build: 14393.4225
- WinFsp version and build: 2020.2

**Comment by billziss-gh** [comment]
For proper operation MSSQL requires drives to be created using the MountManager.

WinFsp includes support for MountManager drives. Instead of naming the drive `X:` when starting rclone mount, name it `\\.\X:` (this requires Administrator privileges).

**Comment by billziss-gh** [comment]
@Jammycrocodile were you able to use MSSQL when using MountManager drives?

**Comment by Jammycrocodile** [comment]
Sorry for my late response, I have been away over easter. Thanks alot for helping me with my issue. 

I'm not quite sure how to set up the drive with MountManager. Are you referring to something like this: [https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/supporting-mount-manager-requests-in-a-storage-class-driver](url)

I tried to mount the drive with the following settings: 

`mount s3-bucket-sql-test:s3-bucket-sql-test/ \\.\S: --vfs-cache-mode full `

Unfortunately this did not resolve my problem. I would appreciate some guidance.
