### ISSUE TITLE
Memfs mounted on directories is unstable

### ISSUE THREAD

**Issue by efeat** [billziss-gh/winfsp#36]
Dear Bill,

I'm using winfsp-1.0.17009.msi.
memfs works nicely when it's mounted on a drive letter but is unstable when it's mounted on a directory.

Steps to reproduce:
1- memfs-x64.exe -m foobar
2- Open foobar with explorer
3- Create a new folder with explorer => OK
4- Create a new folder with explorer => KO
5- Delete the first created folder => KO

Other steps to reproduce:
1- memfs-x64.exe -m foobar
2- Open cmd
3- cd foobar
4- mkdir a => OK
5- cd a => KO (no such directory)

Tested on windows 7 & 8.1 with the same behavior.

Best regards

**Comment by billziss-gh** [comment]
Hi, @efeat.

This will work if you launch MEMFS with the `-i` option. Like so: `memfs-x64.exe -i -m foobar`. The `-i` option will launch MEMFS as a case-insensitive file system.

This is an unfortunate, but well-understood problem on Windows. When using mount points, Windows does not always preserve the case of file names that are sent to the file system. Making the file system case-insensitive overcomes this issue.

Here is a short demonstration. I run MEMFS with the options `memfs-x64.exe -d -1 -D - -m foobar`. [The `-d -1 -D -` means to enable debug logging of all file system operations and output the logs to stdout.] Then I executed the commands `mkdir a` and `cd a` from a different prompt. Here is the MEMFS log output.

    memfs-x64[TID=0514]: FFFFB482BC3D7940: >>Create [UT---C] "\a", FILE_CREATE, CreateOptions=200021, FileAttributes=10, Security=NULL, AllocationSize=0:0, AccessToken=0000000000000198, DesiredAccess=100001, GrantedAccess=0, ShareAccess=3
    memfs-x64[TID=0514]: FFFFB482BC3D7940: <<Create IoStatus=0[2] UserContext=0000023AED812910, GrantedAccess=100001, FileInfo={FileAttributes=10, ReparseTag=0, AllocationSize=0:0, FileSize=0:0, CreationTime=2017-02-01T20:08:41.845Z, LastAccessTime=2017-02-01T20:08:41.845Z, LastWriteTime=2017-02-01T20:08:41.845Z, ChangeTime=2017-02-01T20:08:41.845Z, IndexNumber=0:2}
    memfs-x64[TID=0514]: FFFFB482BD8E8230: >>Close 0000023AED812910
    memfs-x64[TID=0514]: FFFFB482BD8E8230: <<Close IoStatus=0[0]
    memfs-x64[TID=16cc]: FFFFB482B934E820: >>Create [UT---C] "\A", FILE_OPEN, CreateOptions=200000, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=0000000000000198, DesiredAccess=80, GrantedAccess=0, ShareAccess=7
    memfs-x64[TID=16cc]: FFFFB482B934E820: <<Create IoStatus=c0000034[0]

Notice that the first `Create` from `mkdir` (`FILE_CREATE`) arrives with the correct filename case `"\a"`. But the second `Create` from `cd` (`FILE_OPEN`) arrives with the incorrect filename case `"\A"`.

**Comment by efeat** [comment]
Hi Bill,

Thanks for these explainations!

Validated on Windows 7 & 8.1.

**Comment by mhofman** [comment]
Wondering if the new per-directory case sensitivity introduced in the lastest Windows 10 1803 actually changes anything? Or is it something specific to NTFS Filesystems?
https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/

**Comment by billziss-gh** [comment]
@mhofman thanks for the pointer. I will look into it.

**Comment by mhofman** [comment]
Looks like in newer versions the per directory case sensitivity flag will be inherited:
https://blogs.msdn.microsoft.com/commandline/2018/06/14/improved-per-directory-case-sensitivity-support-in-wsl/
