### ISSUE TITLE
BUG: IRP_MJ_SETINFORMATION/FileBasicInformation: -1 timestamp should not be updated

### ISSUE THREAD

**Issue by printpagestopdf** [billziss-gh/winfsp#362]
I installed Version 3.5.20024. Accessing a linux host from windows. Everything works fine, but on file save the modification date of the file will be set to some time in the past (2009-04-22).  That stops e.g. php-fpm from working correctly because it doesn't recognize filechange (after the second save).

**Comment by billziss-gh** [comment]
This problem should be fixed in commit b2e677a3d35b62ea78f5ba5c97b260f1f58c9007.
