### ISSUE TITLE
How to combine WinFSP and Win-SSHFS-Manager with the installation files

### ISSUE THREAD

**Issue by writingdeveloper** [billziss-gh/winfsp#363]
Before asking questions, I would like to thank you for using Win-SSHFS and WinFSP very well.

I am currently working on combining the GUI program Win-SSHFS-Manager into a single program.

We are using Win-SSHFS-Manager with Win-SSHFS and WinFSP in our office, but there is one problem.

When the staff installed the program, I even made a manual to install the Manager program after installing Win-SSHFS and WinFSP, but people often didn't read it more than I thought, and every time they asked me questions about the program not working.

So I'm working on combining these three programs. Combining SSHFS and Manager was easy. There was a path to SSHFS in the Manager source code, and SSHFS was recognized normally by building the Electron app after putting all SSHFS dll files in the ExtraResource folder.

However, the problem arose in the area of combining WinFSP. I thought there was a place like SSHFS where you put all the dll files into the ExtraResource folder and specify the path to WinFSP somewhere in the source code.

After a lot of trial and error, I found out that WinFSP dll was not called in from Win-SSHFS. I learned that it is registered with 'Window Service'. I realized that simply calling dll files would not be recognizable because WinFSP installation meant that there was a registration process with Windows Service.

So eventually, when I installed this Electron Manager app, I had to make sure that WinFSP could be installed together, but no matter how much I searched, there was no way I could install two installation files at once.

I searched a lot on Stackoverflow or Google, but there was no answer to this problem. So, as a developer of WinFSP, I'd like to ask you a question that you might have some advice or solutions.

**Comment by billziss-gh** [comment]
My recommendation in such cases is to use the WinFsp MSI as is distributed by this project and bundle it into your own installer.

For example, you can bundle WinFsp, SSHFS-Win and SSHFS-Win-Manager into a single installer bundle using the [WiX Burn engine](https://wixtoolset.org/documentation/manual/v3/bundle/).
