### ISSUE TITLE
Overwrite creation disposition sharing behaviour does not match NTFS

### ISSUE THREAD

**Issue by pmaxwell-iam** [billziss-gh/winfsp#364]
## Bug Report

Current behaviour of WinFSP makes it possible to truncate or supersede a file despite the presence of handles that do not grant access to write or delete the file via their share flags. This is not possible on NTFS.

### How to Reproduce

```
CreateFile(fileName.c_str(), GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
HANDLE h =
   CreateFile(fileName.c_str(), GENERIC_READ, FILE_SHARE_READ, NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
assert(h == INVALID_HANDLE_VALUE);
```

### Behaviors

On NTFS, the first call succeeds and the second has a sharing violation; this is because CREATE_ALWAYS requires other handles to grant write access. Similar behaviour exists for NtCreateFile/ZwCreateFile with read access and read sharing using the FILE_OVERWRITE and FILE_OVERWRITE_IF creation dispositions.

On memfs, CreateFile's second call does not raise a sharing violation; this is also the case with NtCreateFile. This makes it possible to truncate a file owned by a handle which has not granted write access.

On NTFS, NtCreateFile using the FILE_SUPERSEDE creation disposition require other handles to grant delete permission; if this is not granted STATUS_SHARING_VIOLATION is returned.

On memfs, STATUS_SUCCESS is returned even if other handles exist which do not grant delete permission.

### Environment

Windows version: 10.1.19041
WinFSP version: master, built from a7cfab.

**Comment by billziss-gh** [comment]
@pmaxwell-iam thanks for the report. Looking at this now.

**Comment by billziss-gh** [comment]
I can confirm that this is a problem and an incompatibility between NTFS and MEMFS.

**Comment by billziss-gh** [comment]
WinFsp performs share checks using the [IoCheckShareAccess](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-iocheckshareaccess) DDI. This DDI calculates permission to open a file based on desired access (`FILE_READ_DATA`, `FILE_WRITE_DATA`, etc.), desired share access (`FILE_SHARE_*`) and already given access and share access to prior openers.

We do not have access to the NTFS source code, but we have access to [FastFAT](https://github.com/microsoft/Windows-driver-samples/blob/master/filesys/fastfat/create.c). WinFsp follows the FastFAT method of checking for share access (but **not** file permissions); my understanding of the FastFAT code suggests that they calculate share permissions in a similar manner for OVERWRITE and SUPERSEDE. Of course I may be wrong in this assessment (or less likely NTFS and FAT differ in behavior here).

In any case I will experiment with some changes and see if I can bring WinFsp more inline with NTFS here.

**Comment by billziss-gh** [comment]
@pmaxwell-iam please try latest (commit 33c6e7ee61dba9d7da3b0a183defb0a7188c8388) from branch [pvt-fix364-3](https://github.com/billziss-gh/winfsp/tree/pvt-fix364-3) which I believe fixes this issue.

**Comment by pmaxwell-iam** [comment]
HI @billziss-gh, have tested this locally and can confirm that branch pvt-fix364-3 appears to fix the issue both on memfs and on my filesystem.

**Comment by billziss-gh** [comment]
Thanks for confirming. I have now merged these changes into master.
