### ISSUE TITLE
How can I set custom volume size?

### ISSUE THREAD

**Issue by writingdeveloper** [billziss-gh/winfsp#368]
## Bug Report

I use WinFSP (Latest) with SSHFS-Win (Latest) to connect SSH file server in Windows 10. And I use GUI Win-SSHFS-Manager to control it.

The problem is When I connect with my SSH server, it works well but, displaying volume size is wrong. I think normal servers are works well but it's only occurs in Synology SSH Server, especially When I connect root directory.

This is my synology root directory and as you see there are three volume folders under root path.
![image](https://user-images.githubusercontent.com/6832586/117595152-03eeaf80-b17b-11eb-8d2c-9bf9df0dfb6a.png)

But When I connect the server it seems that it shows the System Path. (Almost 3~4GB only)
![image](https://user-images.githubusercontent.com/6832586/117595255-4dd79580-b17b-11eb-844d-48cf2ab2d009.png)

If I add all of my volumes sizes might be ~18TB but when I connect it it only show the 3~4GB capacity. I don't care it shows the 3~4GB only but the problem is free size are set only 1.18GB So I cannot upload over 1.18GB files. But it's really weird that I can download large files from SSH file server.

I tried to set in Synology DSM but It seems that there are no solution. So I search WinFSP API's and I found 'GetVolumeInfo' part.
So I thought i fix the winfsp source code with GetVolumeInfo part to set volume capacity really high and build it and apply to Win-SSHFS. Is it possible or not

### How to Reproduce

Connect SSHFS server with Synology SSH Root Path

### Environment

- OS version and build: Windows 10 Pro
- WinFsp version and build: Latest

**Comment by billziss-gh** [comment]
My apologies for taking so long to respond, but the problem you are having seems specific to your setup.

I will close this issue, but will reopen if you can show that the problem you are experiencing is because of a bug in WinFsp.
