### ISSUE TITLE
FspFileSystemStopDispatcher does not wait for current system calls to be served 

### ISSUE THREAD

**Issue by edyadkin** [billziss-gh/winfsp#369]
## Bug Report

Call to FspFileSystemStopDispatcher can cause a crash when WinFSP threads are currently executing  FSP_FILE_SYSTEM_INTERFACE Read callback (or any other callbacks for IO operations). Apparently memory buffers are getting released while other threads are still using them in Read callback.

### How to Reproduce

Call FspFileSystemStopDispatcher while there are active read requests being served by Read callback. Typical scenario is a shut down of virtual file system application/service while client application(s) is still reading virtual files. Normally it results in consecutive calls  to FspFileSystemStopDispatcher and then to FspFileSystemDelete. Crash due to memory access violation happens in one of the the callbacks when FspFileSystemStopDispatcher is called.

### Behaviors

While not documented, it is expected that FspFileSystemStopDispatcher blocks new requests from coming and waits for existing requests to be complete before releasing operational buffers,  joining threads, etc. Now it seems that FspFileSystemStopDispatcher  does not wait for existing system calls to be served first and releases memory buffers that are potentially used in the callbacks

### Environment

- OS version and build: Windows 10 Pro
- WinFsp version and build: 2020.2

**Comment by billziss-gh** [comment]
I agree that this is a bug. Here is a brief description of what happens:

- The `FspFileSystemStopDispatcher` issues a `FSP_FSCTL_STOP` control code to the file system control device.

- The file system control device begins shutting the file system down, canceling I/O requests and releasing associated resources.

- In there is an active `Read`, `Write` or `ReadDirectory` operation, it is possible that it is using a buffer owned by the file system. During file system shut down the virtual memory backing these buffers is freed. No attempt is currently made to wait for operations to complete before freeing these buffers, which can result in an access violation in the user mode file system.

    - These buffers are managed by code in [`psbuffer.c`](https://github.com/billziss-gh/winfsp/blob/v1.9/src/sys/psbuffer.c).

    - These buffers were not part of the original WinFsp design but were added to work around the problem discussed in issue #55.

**Comment by billziss-gh** [comment]
Commit ca832988edab61a75b266ba7d73910fa1468c1a8 should hopefully fix this problem in a backwards compatible manner (i.e. older file systems that use the original `FSP_FSCTL_STOP` shutdown mechanism should continue to work):

> The original WinFsp protocol for shutting down a file system was to issue
an FSP_FSCTL_STOP control code to the fsctl device. This would set the IOQ
to the "stopped" state and would also cancel all active IRP's. Cancelation
of IRP's would sometimes free buffers that may have still been in use by
the user mode file system threads; hence access violation.
>
> To fix this problem a new control code FSP_FSCTL_STOP0 is introduced. The
new file system shutdown protocol is backwards compatible with the original
one and works as follows:
>
> - First the file system process issues an FSP_FSCTL_STOP0 control code which
sets the IOQ to the "stopped" state but does NOT cancel IRP's.
>
> - Then the file system process waits for its dispatcher threads to complete
(see FspFileSystemStopDispatcher).
>
> - Finally the file system process issues an FSP_FSCTL_STOP control code
which stops the (already stopped) IOQ and cancels all IRP's.

**Comment by billziss-gh** [comment]
This has now been merged to the master branch. Closing.
