### ISSUE TITLE
Additional Application based on WinFsp (WordpressDrive)

### ISSUE THREAD

**Issue by printpagestopdf** [billziss-gh/winfsp#373]
## Question

Don't know if it is interesting, but I added a new Application to GitHub, that ist based on this great Library. WordpressDrive, written in C#, represents a Wordpress site (by Wordpress's REST API) as a Windows Drive. 
Feedback is welcome.

Find WordpressDrive here:
[https://github.com/printpagestopdf/WordpressDrive](https://github.com/printpagestopdf/WordpressDrive)

Best Regards

**Comment by billziss-gh** [comment]
Thanks for the pointer. I have now added a link to WordpressDrive from the WinFsp [wiki](https://github.com/billziss-gh/winfsp/wiki/Known-File-Systems).
