### ISSUE TITLE
symlink using mklink /d does not support turning a directory into a symlink

### ISSUE THREAD

**Issue by pkk-code** [billziss-gh/winfsp#375]
## Enhancement Request

Need fuse layer support to make the directory into a symlink.  

https://github.com/billziss-gh/winfsp/blob/v1.9/src/dll/fuse/fuse_intf.c#L2132-L2134

When we try to use, Access is denied error is generated.

**Comment by billziss-gh** [comment]
The upcoming WinFsp 2022 Beta4 should fix this issue.
