### ISSUE TITLE
Does not work anymore after update Windows with most current M$ updates...(?)

### ISSUE THREAD

**Issue by jayjupdhig** [billziss-gh/winfsp#376]
![Unbenannt](https://user-images.githubusercontent.com/42765391/124784639-66c7b180-df46-11eb-862a-a257b65401e3.JPG)

Regards, Jan

**Comment by billziss-gh** [comment]
Do you still have this problem? I cannot reproduce this.

BTW, this appears to be related to SSHFS-Win and not WinFsp.
