### ISSUE TITLE
Is it possible to disable thumbnails on mounted drive?

### ISSUE THREAD

**Issue by A-Iskakov** [billziss-gh/winfsp#379]
## Question
Is it possible to disable thumbnail creation on a mounted drive to reduce network usage?
_Please consider asking questions in the [WinFsp Google Group](https://groups.google.com/forum/#!forum/winfsp) instead. Before asking a question please also consult the [WinFsp Frequently Asked Questions](https://github.com/billziss-gh/winfsp/wiki/Frequently-Asked-Questions)._

**Comment by billziss-gh** [comment]
My suggestion here would to be mount your file system as a network drive. The Windows shell will avoid costly operations on network drives.
