### ISSUE TITLE
Official support for windows 11?

### ISSUE THREAD

**Issue by ofersadan85** [billziss-gh/winfsp#396]
## Enhancement Request

I searched the issues and the docs but could not find any reference if this has been tested to work on windows 11 or not

> WinFsp is designed to run on Windows 7 and above. It has been tested on the following platforms:
> 
> Windows 7 Enterprise
> Windows 8 Pro
> Windows Server 2012
> Windows 10 Pro
> Windows Server 2016
> 
> 

Would be great to make it official so I thought this issue might help you track that.

**Comment by billziss-gh** [comment]
I have done some preliminary testing and found that WinFsp works in Windows 11. I am hoping to make it official in an upcoming release.

**Comment by billziss-gh** [comment]
Official support for Windows 11 arrived with release [WinFsp 2021.1 Beta3](https://github.com/billziss-gh/winfsp/releases/tag/v1.10B3).
