### ISSUE TITLE
Passing FUSE options to WinFSP service launcher in order to solve permission issues with virtiofs

### ISSUE THREAD

**Issue by ohrenkram** [billziss-gh/winfsp#400]
Is it possible to pass FUSE options to the WinFSP service launcher, via command line, Windows registry, or a configuration file? I'm specifically interested in "-o uid=-1" as I have the suspicion this could solve my current permission problems with virtiofs (following the advice in your FAQs). I understand that virtiofs relies on WinFSP for the mapping of users and permissions between a Linux host and Windows guest. I have recently described my problem on the virtiofs mailing list, see https://listman.redhat.com/archives/virtio-fs/2021-October/msg00185.html, in case the virtiofs developers can shed some light on this, but it might actually be directly related to WinFSP.

**Comment by billziss-gh** [comment]
It is certainly possible to pass desired command line options using the Launcher. You can use the `CommandLine` registry setting for this purpose. For more information, please see this [document](https://github.com/billziss-gh/winfsp/wiki/WinFsp-Service-Architecture).
