### ISSUE TITLE
Permission Denied when uploading a file via SFTP

### ISSUE THREAD

**Issue by rjpfonseca** [billziss-gh/winfsp#402]
## Bug Report

When running an OpenSSH server with a chroot directory inside a MemFS mountpoint, I get an Permission Denied error when trying to upload a text file via an SFTP client.

The text file is still uploaded but it's empty and cannot be edited afterwards.

### How to Reproduce

1. Follow these steps to configure an OpenSSH server in Windows: [https://www.youtube.com/watch?v=BR9qc_1unu8](https://www.youtube.com/watch?v=BR9qc_1unu8)

2. Configure the `sshd_config` file to point its chroot to `C:\Users\<username>\Desktop\MemFS\sshd`

3. Start MemFS with `-m C:\Users\<username>\Desktop\MemFS`

4. Create a directory named `sshd` inside the MemFS mount point

5. Start an SFTP client and connect it to the local OpenSSH server (e.g., I used [WinSCP](https://winscp.net/eng/index.php) for this)

6. After a successful connection, upload a simple text file to the server root directory

### Behaviors

Expected behavior is for the "remote" text file to show up inside the folder `C:\Users\<username>\Desktop\MemFS\sshd` with its content equal to the local file's.

Actual behavior is (see screenshots below):
1. A pop up appears, asking if you want to overwrite the file (even though it was never there in the first place)
2. After clicking "Yes", another pop up appears saying "Permission Denied"
3. The remote file is empty and cannot be edited

### Environment

- OS version and build: Win10 Pro 19043.1288
- WinFsp version and build: 2021.1 Beta3

### Screenshots

![Screenshot 2021-11-09 141652](https://user-images.githubusercontent.com/5692763/140940431-c03848c3-ad60-4ee8-9973-2feebd63796f.png)

![Screenshot 2021-11-09 141046](https://user-images.githubusercontent.com/5692763/140940129-1c8918ed-d408-4275-9656-25bf33e0436d.png)

**Comment by billziss-gh** [comment]
A couple of questions/suggestions regarding this:

- Did you run MEMFS as a case-sensitive or case-insensitive file system (i.e. using the `-i` option)?
- Does the problem still happen if you mount the file system as a drive (`-m X:`) instead of a directory?
- Does the problem still happen if you mount the file system using the mount manager (`-m \\.\X:` -- requires Administrator privileges)?

**Comment by billziss-gh** [comment]
> Mounting the file system using the mount manager as Administrator (-m \\.\Z:) works! 👍

This likely means that OpenSSH uses one of the API's that can only handle drives created by the Mount Manager. For example, `GetVolumePathNameW`.

> Does this mean we will always require Administrator privileges?

Another alternative would be to mount your file system as a network file system. I seem to recall that API's such as `GetVolumePathNameW` work in these cases.

**Comment by billziss-gh** [comment]
Closing this, but please reopen if you believe it has not been addressed.
