### ISSUE TITLE
How install winfsp in windows PE

### ISSUE THREAD

**Issue by crasybest** [billziss-gh/winfsp#404]
HI ALL,

    I need install winfsp winpe environment，But I don't know winfsp whether support or not.

**Comment by billziss-gh** [comment]
I have never tried this so I do not know if it is possible. However I believe that it is possible to load custom drivers on WinPE, so it would perhaps work.

**Comment by billziss-gh** [comment]
Please let me know if this addresses your need so we can close the issue.

**Comment by Rimits** [comment]
I use the ```tools/winfsp-winpe.bat``` to add winfsp to Hiren's WinBootCD, and try to use dwarfs to mount a image, but it failed  ```cannot create winfsp-fuse filesystem:FSD not found```
so i suspect that ```tools/winfsp-winpe.bat``` did not fully install winfsp to the PE image?
![图片](https://github.com/winfsp/winfsp/assets/42634955/a2003ec4-7bde-4eed-a86f-bd2014b28c41)

**Comment by billziss-gh** [comment]
Which version of WinFsp are you using? I have not tested this script with the v2 of WinFsp.

**Comment by Rimits** [comment]
I'm using the current release version, winfsp-2.0.23075.msi 
the dwarfs ( which depents on winfsp, https://github.com/mhx/dwarfs ) is also the current release version, 0.9.8.
