### ISSUE TITLE
"Mass storage driver" not found in device manager

### ISSUE THREAD

**Issue by davxiao** [billziss-gh/winfsp#406]
I have a win10 pro version 21H2 guest running on a ubuntu 20.04 as host using KVM/QEMU/libvirt

I have enabled virtiofsd and followed the instructions here to enable access from within windows guest. The host directory has been shared with the windows guest in QEMU configuration following this instruction here

Per the instructions I'm supposed to see a "Mass storage driver" on device manager, but it didn't come up. I also checked the status of winFsp.launcher service, it appears to be in running state.

**Comment by billziss-gh** [comment]
This does not look like a problem in WinFsp, but rather an issue with virtiofs. Please submit this issue to the appropriate repo.
