### ISSUE TITLE
trying to make it work with no installer 

### ISSUE THREAD

**Issue by kindaweirdguy** [billziss-gh/winfsp#411]
## Question

I am actually trying to make it work with the no need of an installer, so far what I accomplished was

```
sc.exe create WinFsp type= filesys displayname= WinFsp binpath= D:\env\bin\winfsp\bin\winfsp-x64.sys
sc.exe start WinFsp
new-service -name WinFsp.Launcher -displayname WinFsp.Launcher -binarypathname "D:\env\bin\winfsp\bin\launcher-x64.exe"
set-service WinFsp.Launcher -status running
[environment]::setenvironmentvariable("path", $env:path + ";D:\env\bin\winfsp\bin", "machine")

``
for some reason it's only working when I run rclone with administrator privileges, I'd like to know what am I forgetting on?

**Comment by billziss-gh** [comment]
Place the `winfsp-x64.sys` and `winfsp-x64.dll` in a directory and run:

```
regsvr32 /s winfsp-x64.dll
```

This will perform a minimal installation. The FSD and DLL will be properly setup in the registry, but there will be no launcher. File systems will need to be able to locate the `winfsp-x64.dll` so you must also add it to their `PATH`.

**Comment by kindaweirdguy** [comment]
yep, that's actually working flawlessly!, and I know my case it's really unusual. I should have taken a look into deploy.bat before,  thanks.
