### ISSUE TITLE
is it possible to use winfsp/winfsp.h with clang or mingw gcc?

### ISSUE THREAD

**Issue by djdisodo** [billziss-gh/winfsp#412]
[log](https://pastebin.com/cFdVACPe)
it's the log i got

am i doing wrong or it isn't possible?

is there a way header can be compatible with clang or gcc?

**Comment by billziss-gh** [comment]
I have not tried to build a WinFsp project with mingw or clang, but I believe others have done it successfully.

For example, @lemourin recently introduced a small change in the `winfsp.h` header to allow compilation under mingw. @lemourin I am wondering if you have any pointers?

**Comment by lemourin** [comment]
I just tried building everything from scratch (reinstalled MSYS2) and it worked. You might be using wrong clang binary; the one I'm using is in `C:/msys64/mingw64/bin/clang++.exe` and it comes from `mingw-w64-x86_64-clang` package. I'm also using cmake which may be setting some extra flags; specifically `-DWIN32_LEAN_AND_MEAN -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_WIN32_WINNT=0x0600`.

**Comment by djdisodo** [comment]
@lemourin 
```
djdis@DESKTOP-TNBJ49B MINGW64 ~/winfsp
$ whereis clang
clang: /mingw64/bin/clang.exe

djdis@DESKTOP-TNBJ49B MINGW64 ~/winfsp
$ whereis clang++
clang++: /mingw64/bin/clang++.exe
```
can you give me the code and command you have used?

**Comment by lemourin** [comment]
`clang.exe -c foo.cc -I /c/Program\ Files\ \(x86\)/WinFsp/inc/` works for me.

```
$ cat foo.cc
#include <winfsp/winfsp.h>
```

```
$ clang.exe --version
clang version 13.0.0
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/mingw64/bin
```

**Comment by djdisodo** [comment]
which matters was the file extension(c for c, cc for cpp) i thought it was a c header
im not familiar with c/cpp but trying to make a bind

**Comment by djdisodo** [comment]
@billziss-gh btw then wasn't passthrough.c a c code?

**Comment by billziss-gh** [comment]
Yes.
