### ISSUE TITLE
cygfuse: can't cd into mount directory via Cygwin shell

### ISSUE THREAD

**Issue by mgeisert** [billziss-gh/winfsp#413]
I'm using a recent download of WinFSP and the memfs-x64 sample program. Running the program creates a Z: mount directory usable from Explorer and Command Prompt as expected. But trying to access the directory from a Cygwin bash shell results in
"-bash: cd: /z: Too many levels of symbolic links".

I can debug this from the Cygwin side but I wanted to make sure this kind of access from Cygwin is supposed to work and/or was working at some point in the past.
Thanks, ..mark

**Comment by billziss-gh** [comment]
This definitely used to work. I will investigate.

- Can you please let me know OS version and WinFsp version?
- What is the memfs command line you are using?

**Comment by mgeisert** [comment]
Windows 10 Home 21H2, build 19044.1348
WinFSP 2022, 1.10.22006
memfs-x64 -u \memfs64\share -m *
(the latter executed from Command Prompt in ...\WinFSP\bin)

**Comment by mgeisert** [comment]
I think you should hold off or suspend investigation for the moment. Today a patch was submitted against Cygwin internal path handling for UNC mounts e.g. Samba. The symptom is the same "Too many levels of symbolic links". I will update when I have more info. Thank you.

**Comment by mgeisert** [comment]
The issue is not present in Cygwin 3.3.4 or higher. It's present in 3.3.3. I don't know about earlier versions. It is unrelated to the patch mentioned in the comment immediately above. It appears to be a regression in recent Cygwin versions up to 3.3.3.

I'm closing this WinFSP issue since nothing needs fixing in WinFSP. Sorry for the noise. h/t to BZ
