### ISSUE TITLE
Allow setting security descriptor with directory mount points

### ISSUE THREAD

**Issue by efeat** [billziss-gh/winfsp#42]
Dear Bill,

WinFsp does not set any security attributes when it's mount on directories.
From my point of view, this is a nice behavior in users directories but not for others (i.e OK in C:\Users\XXX, but not in C:\).

In fact security attributes should be a choice of the application which uses WinFsp, don't you think so ?
This also joins issue #37.

WinFsp could have a default behavior and a customizable one with callbacks. 

Best Regards

**Comment by billziss-gh** [comment]
Hi, @efeat.

Are you talking about the security attributes of a directory that is being used as a mount point? Currently WinFsp creates those directories using `CreateDirectoryW` with default security:

https://github.com/billziss-gh/winfsp/blob/master/src/dll/fs.c#L172

Is this what you would like to have changed? If yes, we can perhaps introduce an `FspFileSystemSetMountPointEx` API which takes additional security attributes to use for directory creation.

BTW, if you are simply talking about the security attributes of the file system root `\`, this is completely under the control of the file system.

**Comment by efeat** [comment]
Hi @billziss-gh,

Yes I'am talking about the default security attributes when WinFsp is mounted on a directory.
I think that both, security attributes and directory creation should be under the final application control.

Thus we could test if the empty directory exists (https://github.com/billziss-gh/winfsp/blob/master/src/dll/fs.c#L172) and d'ont create it with default attributes in that case to avoid the second point of your reflexion in issue #37:

Inability to mount over a non-empty directory on Windows. On FUSE/UNIX this is possible, but not on Windows because NTFS disallows the creation of reparse points on non-empty directories.

**Comment by billziss-gh** [comment]
I understand. It is an easy fix to introduce a new API with this signature:

    FSP_API NTSTATUS FspFileSystemSetMountPointEx(
        FSP_FILE_SYSTEM *FileSystem,
        PWSTR MountPoint,
        PSECURITY_DESCRIPTOR SecurityDescriptor);

And use the security descriptor when creating the mount directory only.

My assumption is that you want this feature in order to control which users can access the file system. Unfortunately I have doubts that this scheme would work Unfortunately t
On further reflection though this security descriptor may not

**Comment by efeat** [comment]
I d'ont think this will cover all cases.
Doing nothing if the directory exists and is empty would be better.

Don't be hurry for that, it could be done later.

**Comment by billziss-gh** [comment]
Commit 12704a3a4aedf78170e3ebbc0acdc869b4d8461c adds `FspFileSystemSetMountPointEx`, which allows a security descriptor to be set when mounting on a directory.
