### ISSUE TITLE
WinFsp installer is not signed by Microsoft

### ISSUE THREAD

**Issue by efeat** [billziss-gh/winfsp#43]
Just to keep in mind that the driver is rejected in production environnement because it's not signed.

**Comment by billziss-gh** [comment]
> Just to keep in mind that the driver is rejected in production environnement because it's not signed.

Hi, @efeat. I am slightly confused by this issue. Are you talking about the installer or the driver not being signed? Your title says installer, but the message above says driver.

The driver is currently cross-signed using an EV certificate, which works on all OS'es from Win7 to Win10 before the Anniversary Update. It is also "attestation signed" (by Microsoft), which allows it to work on Win10 after the Anniversary Update. The only OS it does not work on currently is Server 2016, and this will be fixed in RC2.

The installer is cross signed using the same EV certificate.

Have you found an OS (other than Server 2016) where the released driver is not being loaded?

**Comment by efeat** [comment]
Hi @billziss-gh , I've installed winfsp-1.0.17009 on a company Windows 7 computer (not mine) which is a Production environment.

This WinFsp version was installed successfuly on mine but not on that company computer.
The error message is: 

Windows requiere a signed driver.
...
This driver is unavailable and the program will not work properly.

Please find in attachment the screen shot of the error message.

As it's said on the message, WinFsp does not work:
C:\Program Files (x86)\WinFsp\bin>memfs-x64.exe -m Y: -i
cannot create MEMFS
The service memfs has failed to start (Status=80070241).

I've found the test usefull because that company has thousands of computers all configured differently.

I'll investigate on that but any idea would be wellcome.

Best Regards

![winfsp-signature-error](https://cloud.githubusercontent.com/assets/25483919/22644437/d2241fb2-ec62-11e6-842c-f2a76c968963.png)

**Comment by billziss-gh** [comment]
I am suspecting that the Win7 computer that is exhibiting this problem, may be missing a hotfix (or service pack). Or I may have messed up in signing the driver.

There is a `diag.bat` batch file in the WinFsp `bin` directory. It would be very helpful if you run this tool and let me know what the output is. I am particularly interested in OS version and CPU type, as well as hotfixes installed (you may want to censor some of the tool's output, e.g. the registered owner/organization).

Can you also use Explorer to right click on the driver file (looks like `winfsp-x64.sys` from the screenshot above) and check all signatures under "Digital Signatures". Report to me if something looks wrong there.

**Comment by billziss-gh** [comment]
Hi, @efeat. I have found this security advisory from Microsoft. Does the computer that exhibits this problem have it installed:

https://technet.microsoft.com/en-us/library/security/3033929

**Comment by efeat** [comment]
Hi @billziss-gh,

Congratulation, the patch corrected it!

I'll try on few computers to find others installation issues.

Do you still want the `diag.bat` output ?

**Comment by billziss-gh** [comment]
If the problem has been corrected, then the diag.bat output is not necessary.

Let me know when you feel confident that we can close this issue.

**Comment by billziss-gh** [comment]
Hi, @efeat. I am wondering if you have an update for me as I would like to close this issue if it has been resolved.

**Comment by efeat** [comment]
Hi @billziss-gh,

I've installed WinFsp and tested memfs on few other computers of that company.
The single issue I've found have been resolved by this patch.

**Comment by netheril96** [comment]
Maybe WinFsp installer should check for the existence of this KB before it continues, for otherwise the users will be confused when they get the unexpected errors. The Dokany installer does a similar thing.

**Comment by billziss-gh** [comment]
Good idea, although I am not sure how to check for the existence of a hot fix through a Wix installer.

**Comment by fsgeek** [comment]
http://stackoverflow.com/questions/9478014/detect-and-require-a-windows-qfe-patch-for-during-installation/29946122

Describes one potential way to do so.

**Comment by billziss-gh** [comment]
@fsgeek, thanks. I had seen this stackoverflow answer but missed the truly relevant answer that you linked to (`util:ProductSearch`).

I will open a new issue to track this as an enhancement.

**Comment by Kaligula0** [comment]
Strange. I saw the error (about unsigned driver), tried to fix following this solution (according to FAQ#1 on WinFsp website), downloaded the hotfix but its installer told me I have it already installed. And I don't know what to do to solve this :/

**Comment by Masamune3210** [comment]
Make sure your time and date is set correctly, preferably through a Internet Time Server, signatures are very sensitive to incorrect clocks and it can play havoc with all sorts of things

**Comment by Kaligula0** [comment]
I synced my Windows time with time.nist.gov and installed latest WinFsp ("winfsp-1.12.22301.msi"). After a few seconds I still got the message that "Windows requires a digitally signed driver": 
![image](https://user-images.githubusercontent.com/3950811/209013180-39f6b1c2-fbfa-465d-a9c7-4bf495896b07.png)

I use Windows 7 SP1. Driver's signatures look fine (I think, I have zero knowledge in this):
![image](https://user-images.githubusercontent.com/3950811/209013828-ee33544e-b02b-4ff3-a630-21ca828b8b03.png)

Right after installation I tried to follow the instructions on runing WinFsp from https://winfsp.dev/rel/ and when trying to "Map network drive…" `\\memfs64\share` Windows says it can't.

Should I provide the `diag.bat` output? (And how to do it – file outputs to console and there are so many pages/screens that first part gets truncated.)

**Comment by Kaligula0** [comment]
I managed to output `diag.bat` to a file → [here](http://kaligula.uk/_kaligula/WinFsp_diag_output.txt).

**Comment by billziss-gh** [comment]
@Kaligula0 download the latest update [WinFsp 2022.2 Update1](https://github.com/winfsp/winfsp/releases/tag/v1.12.22339) which fixes a problem with signatures on Win7.

**Comment by Kaligula0** [comment]
Thank you, @billziss-gh ! There were no errors atfer installation of "_2022.2 Update1_" :)

**Comment by gnips** [comment]
I have same problem as Kaligula0, Win7 SP1, All SP's in place. I got the unsigned driver error when installing, and get "memfs has failed to start (Status=80070241)" on a \\memfs64\share mount. I have not tested 2022.2 Update1 yet. If you want diag.bat output let me know.

**Comment by Sepero** [comment]
I was able to resolve this error by downloading a different Windows 7 ISO. My original ISO was from year 201X, and the new ISO released 2020.
