### ISSUE TITLE
Building and Running WinFSP, minor documentation faults

### ISSUE THREAD

**Issue by efeat** [billziss-gh/winfsp#48]
Dear @billziss-gh,

I've build WinFsp from the sources successfully, but I've notice few minor faults:

- WinFsp must be build from a "git clone" not from the github zip (this may be noticed in the README.md file)
- To build the installer, x86 and x64 solution configuration must be built, then generate installer/CustomActions & installer/winfsp_msi projects
- To enable testsigning the command line is "bcdedit.exe -set testsigning on", not "bcdedit.exe -set testsigning" as it's specified in your documentation http://www.secfs.net/winfsp/develop/debug/

I've build WinFsp on Windows 7 and it's working perfectly on my Windows 8.1 Pro VM.
Do we really need to build it on Windows 10 ?

Best Regards

**Comment by efeat** [comment]
We could also note that WinFsp in debug configuration is much slower (around 10 time slower) than the release one.

**Comment by billziss-gh** [comment]
Hi, @efeat.

> I've build WinFsp from the sources successfully, but I've notice few minor faults:

Thanks, I will try to address those documentation issues.

> I've build WinFsp on Windows 7 and it's working perfectly on my Windows 8.1 Pro VM.
Do we really need to build it on Windows 10 ?

Perhaps not. I build WinFsp regularly on Windows 10 (where I do development) and Server 2012 (through AppVeyor builds). Since you confirm that this builds on Windows 7 we can fix this in the README file.

**Comment by billziss-gh** [comment]
I have update the `README.md` file as per your comments.

**Comment by efeat** [comment]
Very nice.

Thanks
