### ISSUE TITLE
Get version function?

### ISSUE THREAD

**Issue by netheril96** [billziss-gh/winfsp#52]
Is that any function to query the version of the linked WinFsp dll? Just as information to display to the user.

**Comment by billziss-gh** [comment]
Good idea.

There is not one currently, although you can get the WinFsp DLL version using `GetFileVersionInfoSizeW`, `GetFileVersionInfoW` and `VerQueryValueW`.

Perhaps a version describing the API could be added instead, although once v1.0 ("2017") is finally released any API changes should be backward compatible.

**Comment by billziss-gh** [comment]
Commit 50ed020e168d66241f246a2145051b02a5785636 adds `FspVersion` and a simple test. This returns a 32-bit value containing the major version in the `HIWORD` and the minor version in the `LOWORD`. For the current DLL the returned value is `0x00010000`, which translates to `1.0`.
