### ISSUE TITLE
Ways to pass user authorization through winfsp 

### ISSUE THREAD

**Issue by clicx** [billziss-gh/winfsp#56]
I use fuse interface, are there ways to archive these?
1. Pass through user log on authorization to  server, or need to implemented by myself?
2. Make windows  acl working on the network file system.

**Comment by billziss-gh** [comment]
Answers:

1. It is possible to use username/password authentication in a FUSE file system. You need to use the `Credentials` registry key in the file system launcher entry, accept the password on `stdin` and respond `OK` or `KO` for success / failure. [I am just realizing this is not documented.] For an example see the [SSHFS-Win](https://github.com/billziss-gh/sshfs-win) project.

2. The FUSE interface supports POSIX uid, gid, permissions only. The FUSE layer translates into Windows ACLs. If you want full ACL support you currently need to use the WinFsp native interface `FSP_FILE_SYSTEM_INTERFACE`. [We could also consider adding ACL support to the FUSE interface, perhaps through `getxattr`, `setxattr`.]

**Comment by clicx** [comment]
Thanks for your direction, I will search to it.

**Comment by billziss-gh** [comment]
@clicx I am closing in the assumption that you questions have been answered. Please reopen if this is not the case.
