### ISSUE TITLE
[fuse] support for setting volume label / name

### ISSUE THREAD

**Issue by samkelly** [billziss-gh/winfsp#64]
Continued from https://github.com/billziss-gh/winfsp/issues/58#issuecomment-287234546

Would like support for the ability to set the volume label on drives that use the WinFsp FUSE API.

> We should also find out how OSXFUSE does this (if in fact it does support volnames).

OSXFUSE apparently does this via the 'volname' option, which is specified at mount time: https://github.com/osxfuse/osxfuse/wiki/Mount-options

On Linux, I'm not 100% sure that there is even a notion of this. Ubuntu does have volume labels, but the only information I can find is for renaming partitions / etc, not for FUSE. In Ubuntu at least, however, when you mount a drive with fuse, it shows up in the side bar of the file explorer using the file name of the mount folder, so I've always just named my mount folder with the name I want to use as the label and this works.

**Comment by samkelly** [comment]
update: looks like fuse-bindings already does this for OSXFUSE:

```
ops.options.push('volname=' + path.basename(mnt))
```

**Comment by billziss-gh** [comment]
Agreed. We should add this option to WinFsp-FUSE.

Would you like to give it a go? The option would have to be added [here](https://github.com/billziss-gh/winfsp/blob/master/src/dll/fuse/fuse.c#L45) and stored in [`struct fsp_fuse_core_opt_data`](https://github.com/billziss-gh/winfsp/blob/master/src/dll/fuse/fuse.c#L31). Then copied into [`struct fuse`](https://github.com/billziss-gh/winfsp/blob/master/src/dll/fuse/library.h#L34) after option parsing is complete. Then it would be available to be returned at [`GetVolumeInfo`](https://github.com/billziss-gh/winfsp/blob/master/src/dll/fuse/fuse_intf.c#L632) time.

**Comment by billziss-gh** [comment]
@samkelly My apologies, because I forgot to mention something else that is important. While I am happy to accept contributions, I would also require that this [Contributor Agreement](https://github.com/billziss-gh/winfsp/blob/master/Contributors.asciidoc) is "signed" (by simply adding  your name to the Contributor list in your PR).

Basically the Contributor Agreement document says that we would have joint copyright over any changes to WinFsp that you may send and that are incorporated in the project. I will understand if you find this requirement unpalatable.

**Comment by billziss-gh** [comment]
Some additional info regarding this. A volume label maximum size is just 32 characters, so you could avoid memory allocations, etc. by simply adding a `WCHAR VolumeLabel[32]` at the end of `struct fsp_fuse_core_opt_data` and `struct fuse`.

**Comment by samkelly** [comment]
> by simply adding a `WCHAR VolumeLabel[32]` at the end of `struct fsp_fuse_core_opt_data` and `struct fuse`.

Where is `struct fuse` defined? I can't seem to locate it. In fuse.h there is `struct fuse;` but there are no members etc, so I'm thinking this isn't where I should look?

Do we want to stick with `volname` as the name of the option, to match OSXFUSE?

What does the `v` param do for `FSP_FUSE_CORE_OPT`? Is this like a boolean indicating whether a value was specified?

What I have right now:
`FSP_FUSE_CORE_OPT("volname=%s", VolumeLabel, 0),`

and then `WCHAR VolumeLabel[32];` in `struct fsp_fuse_core_opt_data`

**Comment by billziss-gh** [comment]
The `struct fuse` actual definition is at https://github.com/billziss-gh/winfsp/blob/master/src/dll/fuse/library.h#L34.

I like `volname` for compatibiity with OSXFUSE.

> What I have right now: `FSP_FUSE_CORE_OPT("volname=%s", VolumeLabel, 0),`

This would work if we wanted the FUSE opt parser to treat the `volname` option as a string that it allocates using `env->memalloc` that it then places into a `VolumeLabel` variable.

If you instead use `FUSE_OPT_KEY("volname=", 'v'),` what you are saying to the FUSE opt parser is that you want to get a call back in [`fsp_fuse_core_opt_proc`](https://github.com/billziss-gh/winfsp/blob/master/src/dll/fuse/fuse.c#L444) and write something along the lines of:

    case 'v':
        arg += sizeof "volname" - 1; /* skip the option name */
        /*
         * Carefully copy the remainder arg into opt_data.VolumeLabel;
         * make sure you do not overrun any buffers.
         */

**Comment by samkelly** [comment]
gotcha -- thanks
