### ISSUE TITLE
Maximum number of WinFsp mounts

### ISSUE THREAD

**Issue by efeat** [billziss-gh/winfsp#66]
Dear @billziss-gh,

Fuse limits the number of mount points with the file mount_max parameter in the */etc/fuse.conf* file.
By default this value is set to 1000.

What about WinFsp maximum number of mount points ?

Best Regards

**Comment by billziss-gh** [comment]
Hi, @efeat.

WinFsp does not have a hard limit in how many file systems can be created or how many processes can create file systems.

As of the commits required to fix #55, there is however a hash table inside the FSD that uses PID's (Process ID's) as keys. This hash table currently expects that in general there will not be more than 50 processes creating file systems. However this is not a hard limit.

https://github.com/billziss-gh/winfsp/blob/master/src/sys/psbuffer.c#L23

**Comment by billziss-gh** [comment]
I have now added an [FAQ](https://github.com/billziss-gh/winfsp/wiki/Frequently-Asked-Questions) section in the wiki and I am answering this question there as well.

I will close this question now, unless you find that the capacity of the process buffer hash table (50) is too low and you would rather have it increased. While this is not a hard limit, it could actually marginally affect performance if you somehow had 1000 file system processes.

**Comment by efeat** [comment]
Very nice.
Thanks
