### ISSUE TITLE
WinFsp Fuse port: functions signature

### ISSUE THREAD

**Issue by efeat** [billziss-gh/winfsp#67]
Dear @billziss-gh,

I am looking to the WinFsp fuse port and comparing the methods signatures with **Fuse 3.0**
It seems that some signatures are not the same.

For example, the readdir function:
Fuse
`static int readdir(const char *path, void *buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info *fi,enum fuse_readdir_flags flags)`

WinFsp Fuse
`static int readdir(const char *path, void *buf, fuse_fill_dir_t filler, fuse_off_t off,
    struct fuse_file_info *fi) `

The flags are missing.

Is WinFsp Fuse a port of an other version of Fuse ?

Best Regards

**Comment by billziss-gh** [comment]
Yes. WinFsp is compatible with FUSE 2.8.

I have thought about adding FUSE 3.0 compatibility and would probably do it by introducing new `fsp_fuse3_*` symbols.

**Comment by billziss-gh** [comment]
I am closing this issue for now, but if you would like to see FUSE 3 compatibility, feel free to add a new one as an enhancement.

**Comment by efeat** [comment]
Hi @billziss-gh 

Thanks for that fast answer, as usual :)
