### ISSUE TITLE
required operations for fuse rename to work?

### ISSUE THREAD

**Issue by samkelly** [billziss-gh/winfsp#79]
In my fuse-bindings-based file system, I have all the standard read and stat and getattr / etc operations working, and an implementation of rename() that works when my fs is mounted on linux. On WinFsp when I go to rename in explorer, I instead get "B:\ is not available" or "location unavailable" type error messages (message pops up when I try to rename anything and hit enter). Also in the context menu when I right-click a file, the UAC admin shield is shown next to the rename menu option. Is this maybe because I don't have write implemented? Just was curious if requiring write to be implemented for rename to work is a quirk of windows / WinFsp 

These are the operations that my fs currently implements:
readdir, access, readlink, getattr, open, opendir, release, utimens, rename, read

**Comment by billziss-gh** [comment]
Off the top of my head I cannot think of anything that would make `rename` fail like this. `Write` is not required for `rename` to work properly.

**Speculation**: If the file system works on other operations and fails with "location unavailable" etc. when `rename` is called, I am wondering if the file system goes away or crashes, etc. during `rename`, thus invalidating the file system and the underlying drive.

If this is publicly available I can help troubleshoot.

**Comment by samkelly** [comment]
Now that I think about it, I don't even think rename is showing up in the logs as getting called, so maybe the os is using some combination of operators to test if it can call rename. I'll confirm tonight when I'm back on my windows machine.

**Comment by billziss-gh** [comment]
Make sure to also enable the WinFsp debug logging to see whether the FSD actually sends the `Rename` to the DLL (you should see it as a `SetInformation [Rename]` line).

**Comment by billziss-gh** [comment]
Just wondering if you resolved the issue with `rename`?

**Comment by samkelly** [comment]
I've been adding a bunch of write-related operations and am going to re-test once they are all implemented, as I suspect this is the issue -- thanks for checking in.

**Comment by samkelly** [comment]
@billziss-gh I think this might be happening because I am returning file modes from a linux system in `getattr()`, maybe resulting in windows not thinking it has write privileges to the path I am trying to rename ... what should I be returning for mode in windows? Is there a default I can use?

**Comment by samkelly** [comment]
update: it looks like any fuse operations involving write access have this same issue. My guess is that it is indeed something wrong with permissions. One potential issue is that I am using the raw file modes (and thus the umask/user id) from my linux system, so maybe I need to change this. I can obtain the umask from node with `process.umask()`.

When I right-click any file or folder in my drive in explorer and hover over rename, it shows the UAC icon next to rename. The same goes for other "write" operations such as delete.

![permissions_issue_1](https://cloud.githubusercontent.com/assets/1855021/24837587/58d7e99e-1d05-11e7-945a-8132c6989358.png)

Likewise, if I right click on the background and do New >, I only am given the option to create a new folder (no blank text document, etc), and that option also has a UAC shield next to it, suggesting the system thinks it needs higher permissions to do this.

![permissions_issue_2](https://cloud.githubusercontent.com/assets/1855021/24837594/88a2ba82-1d05-11e7-9613-7f96616291ba.png)

When I go to Properties for any file or folder in my filesystem on windows, it says the file or folder is readonly in the attributes section.

If I try to create a new folder or actually do the rename, I get this message box (and it fails):
![permissions_issue_3](https://cloud.githubusercontent.com/assets/1855021/24837599/a7b0a5ce-1d05-11e7-9881-a7c493a36d73.png)

**Comment by samkelly** [comment]
update: changing all the modes returned by getattr to the following seems to have fixed this issue:

```javascript
        if(os.platform() == 'win32') {
          var prefix = node.ftype == scanning.FS_DIR ? S_IFDIR : S_IFREG;
          mode = prefix + 0777 & ~process.umask();
        }
```

**Comment by billziss-gh** [comment]
@samkelly This is definitely a permissions issue.

The easiest way to fix it for now is to pass the parameters: `-ouid=-1,gid=-1,umask=000` to your FUSE file system. [I do not know if you can do this easily in fuse-bindings, I recall that it did not seem possible to pass random FUSE parameters to it when I looked at it.] What this does is it forces `getattr` to report uid/gid as the current (Windows) user and a file mode of `rwxrwxrwx`.

Another approach is to hardcode the uid, gid, mode values in `getattr`. For example:

```
uid = 11            // Authenticated Users
gid = 65792         // Everyone
mode = 0777         // rwxrwxrwx
```

Since you are getting these values from Linux, the correct solution is to come up with a scheme that maps the Linux uid/gid to the Windows user. There are multiple ways of doing so depending on your environment. We may have to talk about this some more to see what works best for you.

> update: this happens with the "New Folder" menu option, but does not occur when creating a new folder from cmd. I end up with New Folder, New Folder (1), New Folder(2), New Folder (3)

I have seen this and it greatly concerned me when I first saw it. Turns out that it is actually Explorer retrying the directory creation when it fails because of a permission problem. Once we fix the permission problem it will go away.

**Comment by samkelly** [comment]
@billziss-gh hardcoding the uid and gid to 11 and 65792 respectively fixed this -- thanks!

**Comment by billziss-gh** [comment]
@samkelly glad that this worked. Keep in mind that this gives pretty much every authenticated user access to the file.

I should document some of these "magic" uid's in the FAQ. Perhaps even better create a tool to manage them.

Long term it might be worth while thinking about integrating some kind of user name/id mapping functionality into WinFsp. It is far too often needed when dealing with file systems.

**Comment by samkelly** [comment]
@billziss-gh on that note, is there a magic uid I can use that gives just the current user?

**Comment by billziss-gh** [comment]
There is no such magic uid that `getattr` can return. However one can use `-ouid=-1,gid=-1` on the command line to get the current user.
