### ISSUE TITLE
unsigned driver in the installer of WinFsp 1.0, 0.17, 0.15, maybe others to

### ISSUE THREAD

**Issue by j7th** [billziss-gh/winfsp#81]
after installing
https://github.com/billziss-gh/winfsp/releases/download/v1.0/winfsp-1.0.17072.msi
or
https://github.com/billziss-gh/winfsp/releases/download/v0.17/winfsp-0.17.16287.msi
or
https://github.com/billziss-gh/winfsp/releases/download/v0.15/winfsp-0.15.16210.msi
windows unsigned driver error window popup
![unsigned_driver](https://cloud.githubusercontent.com/assets/10299298/24949642/013d8ab2-1f77-11e7-97ac-e0a3836da854.png)

Windows 7 SP1

**Comment by billziss-gh** [comment]
Are you on Windows 7? Make sure that you install this security advisory:
https://technet.microsoft.com/en-us/library/security/3033929.aspx

**Comment by billziss-gh** [comment]
@j7th did you have the chance to retry the installation after installing the linked security advisory?

**Comment by j7th** [comment]
unfortunately, i can't use online Microsoft Update service, also can't find offline installer for this issue. So i will try to disable driver signing checking later.

**Comment by billziss-gh** [comment]
Glad to hear!
