### ISSUE TITLE
Feature/Stability/Robustness comparison with dokany

### ISSUE THREAD

**Issue by brunoklein99** [billziss-gh/winfsp#83]
I'm wondering, what are the pitfalls of WinFsp and Dokany, why would I create my project using one rather than the other?

**Comment by billziss-gh** [comment]
Duplicate of #19. Please see the discussion there, which may answer some of these questions.

I have my own views of course, but I am obviously biased.

**Comment by billziss-gh** [comment]
Closing this as I do not have anything else to add at this time.
