### ISSUE TITLE
Creation of a disk file system may fail

### ISSUE THREAD

**Issue by billziss-gh** [billziss-gh/winfsp#88]
There is a report that creation of a disk file system on 32-bit Windows may fail with `STATUS_NOT_IMPLEMENTED` (`c000002`) during `FspFsctlCreateVolume`. The issue happens on 32-bit Windows only. See issue hasse69/rar2fs#75.

According to @hasse69 this happens when mounting a cygfuse file system as a "disk" drive (`\Device\WinFsp.Disk`), but not a "network" drive (`\Device\WinFsp.Net`). After adding debug log instructions to the WinFsp DLL we were able to isolate this problem in the following `DeviceIoControl` call:

https://github.com/billziss-gh/winfsp/blob/v1.0/src/dll/fsctl.c#L83-L90

```C
    if (!DeviceIoControl(VolumeHandle, FSP_FSCTL_VOLUME_NAME,
        0, 0,
        VolumeNameBuf, (DWORD)VolumeNameSize,
        &Bytes, 0))
    {
        Result = FspNtStatusFromWin32(GetLastError());
        goto exit;
    }
```

This fails with `ERROR_INVALID_FUNCTION` (which gets translated to `STATUS_NOT_IMPLEMENTED`). The likely reason for the `ERROR_INVALID_FUNCTION` error return is a `STATUS_INVALID_DEVICE_REQUEST` response from the FSD.

I am unable to reproduce this problem on any of my local 32-bit VM's. Complete `diag.bat` output from @hasse69 below:

```
WINFSP INSTALLATION DIRECTORY AND LAUNCHER REGISTRATIONS

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp
    InstallDir    REG_SZ    C:\Program Files\WinFsp\

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services\memfs-dotnet
    Executable    REG_SZ    C:\Program Files\WinFsp\bin\memfs-dotnet-msil.exe
    CommandLine    REG_SZ    -i -F NTFS -n 65536 -s 67108864 -u %1 -m %2
    Security    REG_SZ    D:P(A;;RPWPLC;;;WD)
    JobControl    REG_DWORD    0x1

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services\memfs32
    Executable    REG_SZ    C:\Program Files\WinFsp\bin\memfs-x86.exe
    CommandLine    REG_SZ    -i -F NTFS -n 65536 -s 67108864 -u %1 -m %2
    Security    REG_SZ    D:P(A;;RPWPLC;;;WD)
    JobControl    REG_DWORD    0x1

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services\memfs64
    Executable    REG_SZ    C:\Program Files\WinFsp\bin\memfs-x64.exe
    CommandLine    REG_SZ    -i -F NTFS -n 65536 -s 67108864 -u %1 -m %2
    Security    REG_SZ    D:P(A;;RPWPLC;;;WD)
    JobControl    REG_DWORD    0x1


WINFSP DLL REGISTRATIONS

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order
    ProviderOrder    REG_SZ    LanmanWorkstation,RDPNP,webclient,Dokan1,WinFsp.Np


HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinFsp.Np\NetworkProvider
    Name    REG_SZ    Windows File System Proxy
    ProviderPath    REG_SZ    C:\Program Files\WinFsp\bin\winfsp-x86.dll


HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\WinFsp
    EventMessageFile    REG_SZ    C:\Program Files\WinFsp\bin\winfsp-x86.dll
    TypesSupported    REG_DWORD    0x7


WINFSP FSD CONFIGURATION AND STATUS

SERVICE_NAME: WinFsp
        TYPE               : 2  FILE_SYSTEM_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: WinFsp
        TYPE               : 2  FILE_SYSTEM_DRIVER
        START_TYPE         : 3   DEMAND_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : \??\C:\Program Files\WinFsp\bin\winfsp-x86.sys
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : WinFsp
        DEPENDENCIES       :
        SERVICE_START_NAME :

D:(A;;LCRP;;;WD)(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)

WINFSP LAUNCHER SERVICE CONFIGURATION AND STATUS

SERVICE_NAME: WinFsp.Launcher
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: WinFsp.Launcher
        TYPE               : 10  WIN32_OWN_PROCESS
        START_TYPE         : 2   AUTO_START
        ERROR_CONTROL      : 0   IGNORE
        BINARY_PATH_NAME   : "C:\Program Files\WinFsp\bin\launcher-x86.exe"
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : WinFsp.Launcher
        DEPENDENCIES       :
        SERVICE_START_NAME : LocalSystem

D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)

OS INFORMATION

Host Name:                 LURCH
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Hasse
Registered Organization:
Product ID:                00330-80000-00000-AA460
Original Install Date:     2016-08-09, 07:32:46
System Boot Time:          2017-05-22, 23:43:19
System Manufacturer:       System manufacturer
System Model:              P5K PRO
System Type:               X86-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: x64 Family 6 Model 23 Stepping 7 GenuineIntel ~2830 Mhz
BIOS Version:              American Megatrends Inc. 1303   , 2008-12-16
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             sv;Swedish
Input Locale:              sv;Swedish
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     3▒327 MB
Available Physical Memory: 1▒488 MB
Virtual Memory: Max Size:  6▒655 MB
Virtual Memory: Available: 3▒606 MB
Virtual Memory: In Use:    3▒049 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\LURCH
Hotfix(s):                 8 Hotfix(s) Installed.
                           [01]: KB3150513
                           [02]: KB3176936
                           [03]: KB3199209
                           [04]: KB3199986
                           [05]: KB3211320
                           [06]: KB4013418
                           [07]: KB4020821
                           [08]: KB4019472
Network Card(s):           2 NIC(s) Installed.
                           [01]: VMware Virtual Ethernet Adapter for VMnet1
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.119.254
                                 IP address(es)
                                 [01]: 192.168.119.1
                                 [02]: fe80::6023:349e:8ad2:ebe8
                           [02]: Marvell Yukon 88E8056 PCI-E Gigabit Ethernet Controller
                                 Connection Name: Local Area Connection
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.0.1
                                 IP address(es)
                                 [01]: 192.168.0.10
                                 [02]: fe80::60f4:ba3b:1d53:3521
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: No
                           Data Execution Prevention Available: Yes
```

**Comment by hasse69** [comment]
> According to @hasse69 this happens when mounting a cygfuse file system as a "disk" drive (\Device\WinFsp.Disk), but not a "network" drive (\Device\WinFsp.Net). After adding debug log instructions to the WinFsp DLL we were able to isolate this problem in the following DeviceIoControl call:

Just a minor clarification. It also does not work when mounting to a local folder. It gives the same error as trying to mount as a "disk" drive.

**Comment by billziss-gh** [comment]
> Just a minor clarification. It also does not work when mounting to a local folder. It gives the same error as trying to mount as a "disk" drive.

@hasse69 thanks for the clarification.

[The failing `DeviceIoControl` happens before "mounting" (but after file system creation), so it makes sense that both drive and directory mounts fail.]

**Comment by billziss-gh** [comment]
@hasse69 can you please let me know if this problem also happens with plain MEMFS?

From a `cmd.exe` prompt try the following:

```
> cd \Program Files\WinFsp\bin
> memfs-x86.exe -i -F NTFS -n 65536 -s 67108864 -m M:
```

This will help us understand whether this is a FUSE/CYGFUSE issue or a general issue on 32-bit Windows.

**Comment by hasse69** [comment]
Same problem with memfs-x86.exe
```
C:\Program Files\WinFsp\bin>memfs-x86.exe -i -F NTFS -n 65536 -s 67108864 -m M:
cannot create MEMFS
The service memfs has failed to start (Status=c0000002).
```

**Comment by billziss-gh** [comment]
> Same problem with memfs-x86.exe

Thanks. This confirms that the problem is more general than just the FUSE layer.

**Comment by billziss-gh** [comment]
@bonagerivenkatesh can you please confirm that your issue is not related to issue #177?

Have a look at the comments towards the end, especially the comments made by @thinkport.

**Comment by billziss-gh** [comment]
Also if #177 is not your issue, I would love if I could get debug access (or even just access) to one of the machines that exhibits this problem.

**Comment by bonagerivenkatesh** [comment]
@billziss-gh I added some logs to print the file name and number where this error was thrown and it is pointing to 
```
if (!DeviceIoControl(VolumeHandle, FSP_FSCTL_VOLUME_NAME,
        0, 0,
        VolumeNameBuf, (DWORD)VolumeNameSize,
        &Bytes, 0))
    {
        Result = FspNtStatusFromWin32(GetLastError());
        goto exit;
    }
```  in `fsctl.c`

I used `memfs.exe -i -F NTFS -n 65536 -s 67108864 -m M: -d -1 -D mountLogs.log` to mount.

The mount still failed with the error  c000002.
The console had the error 
![image](https://user-images.githubusercontent.com/21157876/53963111-9afedf00-40ba-11e9-9e20-2c26f127da4a.png)

Please let me know if any of these info helps to narrow down the issue.

**Comment by billziss-gh** [comment]
@bonagerivenkatesh thanks for the info, but it was already known. Please see top post of this thread.

As said before, I would love to get temporary access to one of the machines exhibiting the problem.

**Comment by bonagerivenkatesh** [comment]
@billziss-gh Unfortunately its happening only on my client machines and I am still in search of one who is ready to give the debug access to us.

**Comment by billziss-gh** [comment]
Understood.

It looks like you are able to run custom builds on those machines so it might be worth trying custom FSD builds to see if we can pinpoint the problem. I am currently on an iPad so I can only type so much detail, but here are some pointers:

- The kernel side handler for `FSP_FSCTL_VOLUME_NAME` is [`FspVolumeGetName`](
https://github.com/billziss-gh/winfsp/blob/v1.4.19049/src/sys/volume.c#L526). It would be good to add some `DbgPrint`’s and see if we ever get them using DbgView. Any alternative mechanism to `DbgPrint` is also acceptable of course.
- I would also add another `DbgPrint` [here](
https://github.com/billziss-gh/winfsp/blob/v1.4.19049/src/sys/fsctl.c#L81) to make sure that the test does not fail for some daft reason.

If we do not see any of these debug prints (and assuming that you have configured things correctly to get debug prints visible on the system) then it must mean that something else intercepts that call and fails it, likely a filter.

So can you also let me know what the `fltmc` command reports for running filters on the system?

**Comment by bonagerivenkatesh** [comment]
@billziss-gh ya I am able to run custom builds on those machine, I will try your suggestion of `DbgPrint` and update you. 
Meanwhile I collected the details of filter drivers and their instances along with the installed applications and services running on that machine. Hope it helps.
[filterInstances.txt](https://github.com/billziss-gh/winfsp/files/2954372/filterInstances.txt)
[filterVolumes.txt](https://github.com/billziss-gh/winfsp/files/2954373/filterVolumes.txt)
[InstalledPrograms.txt](https://github.com/billziss-gh/winfsp/files/2954374/InstalledPrograms.txt)
[AllDrivers.txt](https://github.com/billziss-gh/winfsp/files/2954375/AllDrivers.txt)
[filterDrivers.txt](https://github.com/billziss-gh/winfsp/files/2954376/filterDrivers.txt)

**Comment by billziss-gh** [comment]
@bonagerivenkatesh the filterDrivers.txt file does list a couple of third-party filters:

- WRkrn: [Webroot SecureAnywhere](https://www.freefixer.com/library/file/wrkrn.sys-74653/)
- stcvsm: [StorageCraft Volume Snapshot](https://www.freefixer.com/library/file/stcvsm.sys-115065/)

**Comment by billziss-gh** [comment]
@hasse69 if you are still on the thread and have access to the system that exhibited the original problem: could you check whether that system has any of the aforementioned filters? (Wrkrn and stcvsm?)

You can use the `fltmc` command to get installed and running filters.

**Comment by hasse69** [comment]
Sorry, I upgrade my system to 64-bit a long time ago. I no longer have access to it :(

**Comment by bonagerivenkatesh** [comment]
@billziss-gh luckily I was able to reproduce this issue by just installing the `ShadowProtect` application https://www.storagecraft.com/downloads/trials/spx-windows and then installing winfsp.
We could easily do any debugging if required to fix this.

**Comment by billziss-gh** [comment]
Aha, I suspected it may be StorageCraft once I saw that it was using a legacy filter driver.

**Comment by billziss-gh** [comment]
Let me see if I can easily install this software in one of the VM's I use for kernel debugging.

**Comment by bonagerivenkatesh** [comment]
@billziss-gh to add more info to the above the [line 81](https://github.com/billziss-gh/winfsp/blob/v1.4.19049/src/sys/fsctl.c#L81)  failed so it never entered the `FspVolumeGetName(FsctlDeviceObject, Irp, IrpSp);`

**Comment by billziss-gh** [comment]
Here is my debugging analysis.

In WinDbg I enabled WinFsp debug prints with:

```
kd> ?? fsp_debug |= fsp_debug_dp
int 0n285212674
```

Then got the following logs back:

```
[0] WinFsp!FspFileSystemControl(FFFFF98007902E50, CtlU, IRP_MJ_FILE_SYSTEM_CONTROL[IRP_MN_USER_FS_REQUEST], FSP_FSCTL_VOLUME_NAME, FileObject=FFFFFA8001BD06B0) = STATUS_INVALID_DEVICE_REQUEST[0]
[0] WinFsp!FspCleanup(FFFFF98008F58E50, CtlK, IRP_MJ_CLEANUP, FileObject=FFFFFA8001BD06B0) = STATUS_SUCCESS[0]
```

These logs make no sense: where is the `FspCreate` from when the WinFsp's control device (`WinFsp.Disk`) is opened? I should have seen something along the lines of:

```
[0] WinFsp!FspCreate(...)                       # open the WinFsp.Disk device
[0] WinFsp!FspFileSystemControl(...)            # send it FSCTL requests
...
```

It appears that `stcvsm` is swallowing our `IRP_MJ_CREATE`, but then forwards other IRP's for the same `FILE_OBJECT` anyway. The reason we get back `STATUS_INVALID_DEVICE_REQUEST` from `FSP_FSCTL_VOLUME_NAME` requests is because [this test](https://github.com/billziss-gh/winfsp/blob/v1.4.19049/src/sys/fsctl.c#L81) fails, which ultimately is because we never got the `IRP_MJ_CREATE` to properly initialize our control device `FILE_OBJECT`.

Let's confirm our suspicion. I placed a strategic breakpoint in `nt!NtCreateFile` and started MEMFS with `memfs-x64 -m Y:`. I also placed a breakpoint in WinFsp's `FspCreate`. Eventually I arrive at:

```
kd> k
 # Child-SP          RetAddr           Call Site
00 fffff880`04b6b518 fffff800`45e4cd26 stcvsm+0x8fd8
01 fffff880`04b6b520 fffff800`45c5a05b nt!IovCallDriver+0x3e6
02 fffff880`04b6b570 fffff800`45c56c5d nt!IopParseDevice+0x77b
03 fffff880`04b6b760 fffff800`45c5c2b8 nt!ObpLookupObjectName+0x7a1
04 fffff880`04b6b890 fffff800`45c6debe nt!ObOpenObjectByName+0x258
05 fffff880`04b6b960 fffff800`45c6e609 nt!IopCreateFile+0x37c
06 fffff880`04b6ba00 fffff800`45889053 nt!NtCreateFile+0x79
07 fffff880`04b6ba90 000007fb`97c430fa nt!KiSystemServiceCopyEnd+0x13
08 00000029`750ae718 000007fb`94dd52dc ntdll!NtCreateFile+0xa
09 00000029`750ae720 000007fb`94dd5411 KERNELBASE!CreateFileInternal+0x324
0a 00000029`750ae8a0 000007fb`8f138fb1 KERNELBASE!CreateFileW+0x6d
0b 00000029`750ae900 000007fb`8f13fe5d winfsp_x64_7fb8f100000!FspFsctlCreateVolume+0x281 [c:\users\billziss\projects\t\winfsp\src\dll\fsctl.c @ 79]
0c 00000029`750af0c0 000007f6`0777c315 winfsp_x64_7fb8f100000!FspFileSystemCreate+0xfd [c:\users\billziss\projects\t\winfsp\src\dll\fs.c @ 147]
0d 00000029`750af160 000007f6`07826038 memfs_x64!MemfsCreateFunnel+0x3d5 [c:\users\billziss\projects\t\winfsp\tst\memfs\memfs.cpp @ 2061]
```

I may add to this post as I discover additional information.

**Comment by billziss-gh** [comment]
> @billziss-gh to add more info to the above the line 81 failed so it never entered the FspVolumeGetName(FsctlDeviceObject, Irp, IrpSp);

@bonagerivenkatesh thanks for additional info. Yes, I have found the same. I am in the process of debugging this. See comments above.

**Comment by billziss-gh** [comment]
@bonagerivenkatesh I have updated my debugging analysis, which I posted above. The conclusion:

> To me this looks like a problem with stcvsm and I suggest that we contact their developers as the next step.

**Comment by billziss-gh** [comment]
I am trying to find a bug report or support email on their website, but have not been successful so far.

**Comment by bonagerivenkatesh** [comment]
@billziss-gh sounds good. I really appreciate your involvement and support.

I found this  https://support.storagecraft.com/s/contactsupport (requires registration though to post here)

But on a side note I heard today that some HP software manager also causing this issue (I could not reproduce the issue though), is there anyway the priority of the driver can be changed so that the request directly goes to WinFsp? If that is possible then it would be great as not sure how many legacy drivers are present that might cause similar issues..

**Comment by billziss-gh** [comment]
> But on a side note I heard today that some HP software manager also causing this issue (I could not reproduce the issue though), is there anyway the priority of the driver can be changed so that the request directly goes to WinFsp? If that is possible then it would be great as not sure how many legacy drivers are present that might cause similar issues..

WinFsp is a file system driver and has no "priority". Filters are free to intercept its requests and in some cases they may erroneously handle them. Unfortunately I am not aware of any method to get around that.

**Comment by billziss-gh** [comment]
Sent a mail to support@storagecraft.com. Will see what happens.

**Comment by billziss-gh** [comment]
StorageCraft resolved this issue a couple of days ago. My thanks to the StorageCraft people if you are reading this!

Their newest product SPX 6.8 includes an stcvsm.sys driver with an altitude of 388250. I have confirmed that SPX 6.8 fixes this issue.

@bonagerivenkatesh can you also confirm so that we can close this issue?

**Comment by hasse69** [comment]
@billziss-gh I will not be able to confirm since I am not even certain the original issue I reported has anything to do with SPX. It might have been another filter driver that caused the issue though but I do not think we will ever know for sure.

**Comment by bonagerivenkatesh** [comment]
@billziss-gh I was able to confirm that this is fixed in the latest version of SPX.
Thanks a lot for your assistance

**Comment by billziss-gh** [comment]
@hasse69 thanks. I knew that you had updated that system and you no longer had the original so you could not confirm. If there was another filter driver it will eventually turn up and we might be able to point to a similar cause as being the problem.

@bonagerivenkatesh you are welcome.

Closing this.
