### ISSUE TITLE
WinXP Support

### ISSUE THREAD

**Issue by Comos64** [billziss-gh/winfsp#92]
Hi,
is it possible to make a build to support also WinXP or there is no way on this system anymore? I tried to install it on my WinXP 32bit but I got the winfsp-x32.dll failed to register, HRESULT -2147024769 error during install.

Thanks
Tomas

**Comment by billziss-gh** [comment]
This would be a non-trivial task for WinFsp:

- It uses multiple Vista+ DDI's that would have to be replaced/rewritten. Some of them are only available on Win7+.
- It uses the new Vista+ MUP (Multiple UNC Provider) for network drive support [[link](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/mup-changes-in-microsoft-windows-vista)]. This would have to be rewritten and replaced with the older MUP.
- It has only been tested on Win7 and above.

Given that XP is no longer supported by Microsoft I doubt that WinFsp would ever be backported to it.

**Comment by fsgeek** [comment]
The old MUP interface is also incompatible with the new one - you can support one or the other but not both. 

In my prior work we'd let the file system choose but we had also grown from an NT 4 code base forward.

Windows XP is 15+ years old. It's increasingly insecure. People using it are ill-advised to continue doing so. Why back port at this point?

I can think of so many better uses of resources. If someone does wish to make this happen and wants to fund it, I know people capable of doing the work.

**Comment by Comos64** [comment]
The point is,that I still use XP as my devel & debug system for my C64 ,so no reason for a Win upgrade on my side.WinFSP is used in a conjunction with another tool to mount a image or CF card with specific filesystem for IDE64.
At first point I did not know what kind of function/calls the WinFSP uses,so wanted to ask, if there is way to have it also on WinXP.

**Comment by billziss-gh** [comment]
Commodore 64 has a special place in my heart. A childhood friend of mine owned one and it was the first machine I ever tried to program :)

**Comment by Comos64** [comment]
and we still use it up to day :)

**Comment by Comos64** [comment]
@fsgeek if you know somebody capable of porting it to WinXP, I'll be glad.Now depends how much they charge :)

**Comment by fsgeek** [comment]
I do know a few people that are capable of doing it.  I don't know their availability or any costs involved, however.  If you drop me a private e-mail, I can give you contact information for them.

**Comment by billziss-gh** [comment]
@Comos64 I am the WinFsp author and can definitely do this work. In general I implement new features / functionality for free (within time constraints) if I believe that a lot of users will benefit or that it will make WinFsp more useful. This is an open source project after all.

In this case I find that back porting WinFsp to XP:

- is a non-trivial task, and
- is unlikely to benefit a lot of users.

 For these reasons I am unwilling to do this work for free. So I propose the following alternatives:

- You can send me a private email at billziss at navimatics.com and we can discuss costs.

- You can try to add the functionality yourself and I will provide (free) support.

**Comment by billziss-gh** [comment]
@Comos64 I am closing this as part of an issue cleanup for the upcoming version `1.1`. As discussed over private email I am happy to help with specific questions if you are still pursuing a port. Feel free to post your questions here or in the WinFsp Google group.

**Comment by abubelinha** [comment]
Did this ever happen?
I can't find info about the minimum Windows system requirements in the main page. 
Also checked [this document](https://github.com/billziss-gh/winfsp/blob/master/doc/WinFsp-Tutorial.asciidoc#prerequisites) but nothing is said (perhaps it can be assumed somehow, but I don't catch it).

In our lab, I use a couple of old 32bit Win XP machines which cannot run Win10 (the only OS our university-IT supports by now). We only use them in a LAN, mainly for databasing and image scanning purposes (not for internet surfing, so we don't feel this to be so risky).

If [SSHFS-Win](https://github.com/billziss-gh/sshfs-win) is not possible, do you know which could be the best free alternative for me to easily map and have read/write access a SSH server we use as cloud storage?
Thanks a lot.

**Comment by billziss-gh** [comment]
Minimum supported OS is Windows 7.

**Comment by dreirund** [comment]
I have another use case:

Use Windows XP in QEMU/KVM and add virtio-fs drivers there (file sharing between host and guest). `virtio-win` drivers are not available for Windows XP.
