### ISSUE TITLE
testing winfsp 

### ISSUE THREAD

**Issue by dksqh1111** [billziss-gh/winfsp#98]
hello ! 
I have some question that using winFsp. testing on win 10, using passthrough sample. 
first, I want to implement close method when only real file was closed.
but close method was called too many times. for Example , i just run passthrough, in my console has multiple "CLOSE".
![image](https://user-images.githubusercontent.com/4531133/28857388-32618106-7784-11e7-8018-dedb897765e5.png)
I think ( "\\", "desktop.ini" , "folder.png"... )  in my log FIle when open(). so this causes a lot of close.
how can i know distinguish real file close from fake file close ? 
and then can i use multi root or multi mount point ? currently my passThrough and MountPoint is 1:1 but i want n:n structure. i want to use multi root location . could you give me some samples/?

thank you :)

**Comment by billziss-gh** [comment]
Hi and apologies for my late response. I am currently on vacation and do not regularly check GitHub.

I am not sure I understand your meaning when you say "real file" vs "fake file". Can you please elaborate?

You will get `Close` calls only for files that your file system has opened. So if your file system responds `STATUS_SUCCESS` during `Create` or `Open` you will eventually receive a `Close` call for the opened file. You will never receive a `Close` call for a file that was not previously opened through your file system.

> and then can i use multi root or multi mount point ? currently my passThrough and MountPoint is 1:1 but i want n:n structure. i want to use multi root location . could you give me some samples/?

That is an interesting idea. It is actually possible to do what you want on Windows.  You would have to create multiple drives and/or "junction" reparse points for the file system yourself. You can see how this is done by WinFsp (for a single drive/directory) by studying the [`FspFileSystemSetMountPoint`](https://github.com/billziss-gh/winfsp/blob/v1.1/src/dll/fs.c#L337) code.

**Comment by dksqh1111** [comment]
real file means that The root folder contains only files aa.txt .
![image](https://user-images.githubusercontent.com/4531133/28900318-5783ce7e-782b-11e7-9194-633c756ebd2f.png)
but during debugging, i can also see "desktop.ini" , "folder.png", "folder.jpg" and "\\" files open. these files  are referred to as fake file.
I want to separate these files.

**Comment by dksqh1111** [comment]
hello i have more question using winfsp.  i can't open file where located mount point. 
some files can open, but some files are not open when specific case likes "*.wmv" file with open with"default video player". 
i can see "0xc00d36c4" error . how can i open video file? 
thank you

**Comment by billziss-gh** [comment]
> but during debugging, i can also see "desktop.ini" , "folder.png", "folder.jpg" and "\" files open. these files are referred to as fake file.

These requests are usually sent by Explorer and other parts of the OS. For example, the "autorun.ini" file is used to support the "autorun" functionality and usually exists on CD's / DVD's.

The "\\" is the root directory and you should always be able to open it or you will not have a working file system.

> you means that multi root is possible? :)

I think so although I have not tried it.

> i excepted only write() but in my case, I could see both Write() and Read() called.

You should not make any assumptions about how individual programs perform their I/O. The only way to know for sure is to write your own program that exercises the `ReadFile` and `WriteFile` API's. Even in that case be prepared for surprises, especially if you enable caching in your file system.

> i can't open file where located mount point.
> some files can open, but some files are not open when specific case likes "*.wmv" file with open with"default video player".

Do you mount your file system on a drive or directory? If you mount on a directory you must make sure that your file system is case-insensitive. This is due to a Windows limitation.

> i can see "0xc00d36c4" error

I am not sure what this error code is. Which API or system component returns it?

**Comment by dksqh1111** [comment]
thank you for very much for helping me. 
file was in mounted point, I noticed that when I try to play audio files(*.wmv), an error message pops up saying that it could not be opened .
![image](https://user-images.githubusercontent.com/4531133/29149294-3289db26-7dae-11e7-9c46-ba1ba1d563da.png)
If i leave a file on another path, it does not happen.

**Comment by dksqh1111** [comment]
If i change the contents of a file in Write() , i must change the value of FileInfo() ?
for example, 
If i change the value of the "abcde" file inside the A.txt file to "qqqqqqqqqq" via Write ().

**Comment by billziss-gh** [comment]
> If i change the contents of a file in Write() , i must change the value of Handle or FileInfo ?

The `FileInfo` should always reflect the latest metadata information about a particular file. For example, `Write` will often extend the file size. `FileInfo` should reflect this.

**Comment by dksqh1111** [comment]
hello 
i have one more question.

In my case, the paths are likes this.
	- passThrough Path : "C:\\WinFSP\\STORAGE"
	- mountPoint Path : "C:\\WinFSP\\MOUNT_0"

Set link for mountPoint while running passthrough program.
Instructions are as follows 
	- mklink /D C:\\WinFSP\ccc  C:\WinFSP\MOUNT_0

after setting link, share a ccc folder on my machine. 
in the cmd windows, files are listed. but when accessed by Explorer, the files are not visible.

![image](https://user-images.githubusercontent.com/4531133/29599111-8b472034-8808-11e7-8949-c0b2c4297218.png)

![image](https://user-images.githubusercontent.com/4531133/29599117-9734cc52-8808-11e7-8d24-5645202e3d8d.png)
-this folder is empty.

![image](https://user-images.githubusercontent.com/4531133/29599147-bf84d030-8808-11e7-94da-281cfca7cd02.png)
- this folder is my mount directory 

can you explain this to me?  thank you :)

**Comment by dksqh1111** [comment]
I'm testing passThrough.
What is the meaning of the fourth item **GrantedAccess**, which is the fourth item of the function when calling Create() function?

  if i have not only Read permission but also  Write  permission, i receive  1507743 value.
  if i do not have Read permission, and i have only the Write  permission, i receive  1179785 value.

Does this result related to User account ?
Is it normal to always see the same value regardless of User ? 

I think this is related to ACCESS_MASK(https://msdn.microsoft.com/en-us/library/windows/desktop/aa374892(v=vs.85).aspx) , but it seems to be too large compared to ACCESS_MASK.

I'd like to know what the combination is.
can you explain to me?

**Comment by billziss-gh** [comment]
WinFsp does security checking for you (using `GetSecurityByName`) before sending the `Create` or `Open` calls. It either denies access or computes the access rights that are granted for a particular `Create` or `Open` request. `GrantedAccess` describes those granted access rights and they consist of [standard access rights](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379607(v=vs.85).aspx) and [file access rights](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364399(v=vs.85).aspx).

Most file systems do not need to worry about `GrantedAccess` as all permission checks are done by WinFsp. In a few cases `GrantedAccess` may be of use to determine the actual rights granted for a file descriptor.

**Comment by dksqh1111** [comment]
Inside the mounted Folder, playing video won't play. 
i can see the following error : 
![image](https://user-images.githubusercontent.com/4531133/29644694-22bef946-88b3-11e7-9a3e-ebda1799d5cd.png)
![image](https://user-images.githubusercontent.com/4531133/29644712-4d2c57dc-88b3-11e7-8fb6-96d2d04828bf.png)

also I can’t Play vedio Files in Window Media Player.
![image](https://user-images.githubusercontent.com/4531133/29644905-0b8c01c2-88b5-11e7-967f-bde33f410e92.png)
i can see this error.

video plays normally in a non-mounted path.
if i take a log(PBytesTransferred, Buffer, Length , ... ), this won't be recorded sequentially.
Does Winfsp supports multi-threading??

**Comment by dksqh1111** [comment]
and also, 
Within a function Write() ,Can I put a header in a file and make it appear as the size of the original file?

If the size of the A.txt file is 6K, the size of the file will be 10 K by adding header 4K.
But I would like to see the size of the file in the explorer or in the cmd. 

thank you.

**Comment by dksqh1111** [comment]
I think these video players seem to have lots of threads and approaches in a random access.
Other applications have accessed files sequentially.

**Comment by billziss-gh** [comment]
WinFsp is fully multi-threaded and takes appropriate locks when needed. However the user mode file system must also be multi-threaded and take appropriate locks.

WinFsp also supports a "mutual exclusion" mode, where it will serialize all file system requests. See the comments here: https://github.com/billziss-gh/winfsp/blob/master/inc/winfsp/winfsp.h#L98-L127

You may want to run your file system with `FSP_FILE_SYSTEM_OPERATION_GUARD_STRATEGY_COARSE` and see if it improves matters.

**Comment by dksqh1111** [comment]
I find it rather difficult to understand what you say.
how can I run file system with FSP_FILE_SYSTEM_OPERATION_GUARD_STRATEGY_COARSE  ? 

Can you test the video how I played it ? I hope this works well.

1. run PassThrough.exe    
my options are as follows : 
	PassThrough = L"C:\\WinFSP\\STORAGE_0";
	MountPoint = L"C:\\WinFSP\\MOUNT_0";

2. move to "C:\\WinFSP\\MOUNT_0" folder and play video.

3. play the video.


I will send you 2 video files by mail. the file is too large to upload.
Both videos are work well.
However the goodCase video is executed well insize the "C:\\WinFSP\\MOUNT_0" folder, but the badCase video is not executed. 
Can you tell me what difference is there ?



thank you !

**Comment by dksqh1111** [comment]
and also, can i run passThrough as Service ?

**Comment by dksqh1111** [comment]
this problem has been resolved . 
thank you ! :)

**Comment by billziss-gh** [comment]
@dksqh1111 Apologies for the late response. I just got back from my vacation and should be able to respond more timely.

> this problem has been resolved

Glad to hear!

> how can I run file system with FSP_FILE_SYSTEM_OPERATION_GUARD_STRATEGY_COARSE ?
you means
> Ptfs->FileSystem->OpGuardStrategy = FSP_FILE_SYSTEM_OPERATION_GUARD_STRATEGY_COARSE;
this line after PftsCreate() ?


To set `FSP_FILE_SYSTEM_OPERATION_GUARD_STRATEGY_COARSE` you use the `FspFileSystemSetOperationGuardStrategy` API on the file system object returned by `FspFileSystemCreate`.

**Comment by billziss-gh** [comment]
I am closing this issue as the questions seem to have been resolved. Please open another issue if you have additional questions.

**Comment by yogendersolanki91** [comment]
@dksqh1111 I am facing similar issue.. How did you resolved it ?
